-- Counts of Status and Priority

-- A list of all priority levels, how many future students are at what priority and with what status.

WITH STATUS_PRIORITY_CAPTURE AS
(
  SELECT
  	EXP_FORM_RUN,
  	STUDENT_ID,
    GENDER.GENDER_ID,
    STUDENT_STATUS_ID,
    PRIORITY_ID,
    PRIORITY_ID AS "PRIORITY_ORDER"
  
  FROM TABLE(EDUMATE.GETALLSTUDENTSTATUS(current_date)) ALLKIDS
  
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = ALLKIDS.CONTACT_ID
  INNER JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID

  WHERE EXP_FORM_RUN = '[[Starting Year and Form=query_list(SELECT form_run.form_run FROM form_run WHERE form_run > TO_CHAR(YEAR(current date) + 1) || ' Year %' ORDER BY form_run)]]'
),

COUNTS AS
(
  SELECT
  	EXP_FORM_RUN,
    PRIORITY_ORDER AS "PRIORITY_LEVEL",
    PRIORITY,
    COUNT(CASE WHEN GENDER_ID IN (2,3) THEN 1 ELSE null END) AS "Boys and Girls Total",

    -- Boys
    COUNT(CASE WHEN GENDER_ID = 2 THEN 1 ELSE null END) AS "Boys Subtotal",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 1 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Application Cancelled",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 2 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Alumni",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 3 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Past Enrolment",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 4 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Returning Enrolment",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 5 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Current Enrolment",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 6 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Place Accepted",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 7 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Offered Place",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 8 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Interview Pending",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 9 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Wait Listed",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 10 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Application Received",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 11 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Information Sent",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 12 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Enquiry",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 13 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Interview Complete",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 14 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Expired Offer",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 15 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "(Boys) Expired Application",
    
    -- Girls
    COUNT(CASE WHEN GENDER_ID = 3 THEN 1 ELSE null END) AS "Girls Total",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 1 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Application Cancelled",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 2 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Alumni",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 3 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Past Enrolment",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 4 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Returning Enrolment",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 5 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Current Enrolment",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 6 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Place Accepted",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 7 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Offered Place",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 8 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Interview Pending",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 9 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Wait Listed",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 10 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Application Received",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 11 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Information Sent",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 12 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Enquiry",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 13 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Interview Complete",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 14 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Expired Offer",
    COUNT(CASE WHEN STUDENT_STATUS_ID = 15 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "(Girls) Expired Application"
  
  FROM STATUS_PRIORITY_CAPTURE
  
  INNER JOIN PRIORITY ON PRIORITY.PRIORITY_ID = STATUS_PRIORITY_CAPTURE.PRIORITY_ID
  
  GROUP BY EXP_FORM_RUN, PRIORITY, PRIORITY_ORDER
  
  ORDER BY PRIORITY_ORDER
)

SELECT * FROM COUNTS