WITH CURRENT_STUDENTS AS (
  SELECT GCES.STUDENT_ID, GSFR.FORM_RUN_ID
  FROM TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS(CURRENT_DATE)) GCES
  INNER JOIN TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) GSFR ON GSFR.STUDENT_ID = GCES.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
),

NEXT_YEAR AS (
  SELECT ACCEPTED.STUDENT_ID, FORM_RUN.FORM_RUN_ID
  FROM TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT_DATE)) ACCEPTED
  
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = ACCEPTED.EXP_FORM_RUN_ID
  
  WHERE
    ACCEPTED.STUDENT_STATUS_ID = 6
    AND
    EXP_START_YEAR = (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = TO_CHAR((CURRENT DATE + 1 YEAR), 'YYYY'))
),

ALL_STUDENTS AS (
  SELECT * FROM CURRENT_STUDENTS
    UNION
  SELECT * FROM NEXT_YEAR
)

SELECT
  CONTACT.SURNAME,
  CONTACT.FIRSTNAME,
  FORM_RUN.FORM_RUN,
  VIEW_CONTACT_HOME_ADDRESS.ADDRESS1,
  VIEW_CONTACT_HOME_ADDRESS.ADDRESS2,
  VIEW_CONTACT_HOME_ADDRESS.ADDRESS3,
  UPPER(VIEW_CONTACT_HOME_ADDRESS.COUNTRY) AS COUNTRY,
  VIEW_CONTACT_HOME_ADDRESS.SUBURB,
  VIEW_CONTACT_HOME_ADDRESS.STATE_CODE,
  VIEW_CONTACT_HOME_ADDRESS.POST_CODE

FROM ALL_STUDENTS

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = ALL_STUDENTS.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
INNER JOIN VIEW_CONTACT_HOME_ADDRESS ON VIEW_CONTACT_HOME_ADDRESS.CONTACT_ID = CONTACT.CONTACT_ID
INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = ALL_STUDENTS.FORM_RUN_ID

WHERE
  FORM_RUN NOT LIKE '%%%% Year 12'

ORDER BY FORM_RUN