WITH FORMS AS (
  SELECT * FROM TABLE(EDUMATE.get_enroled_students_form_run(current date))
)

SELECT
  STUDENT.STUDENT_NUMBER,
  (CASE WHEN CONTACT.PREFERRED_NAME IS NULL THEN CONTACT.FIRSTNAME ELSE CONTACT.PREFERRED_NAME END) || ' ' || CONTACT.SURNAME AS "STUDENT_NAME",
  FORM_RUN.FORM_RUN,
  house.house,
  VSMC.SALUTATION,
  VSMC.SALUTATION2,
  VSMC.FIRSTNAMES,
  CARER_EMAIL.EMAIL_ADDRESS,
  (CASE WHEN VCPA.ADDRESS3 IS NULL THEN VCHA.ADDRESS1 ELSE VCPA.ADDRESS1 END) AS "ADDRESS1",
  (CASE WHEN VCPA.ADDRESS3 IS NULL THEN VCHA.ADDRESS2 ELSE VCPA.ADDRESS2 END) AS "ADDRESS2",
  (CASE WHEN VCPA.ADDRESS3 IS NULL THEN VCHA.ADDRESS3 ELSE VCPA.ADDRESS3 END) AS "ADDRESS3"

FROM VIEW_STUDENT_MAIL_CARERS VSMC

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = VSMC.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
INNER JOIN house ON house.house_id = student.house_id

INNER JOIN FORMS ON FORMS.STUDENT_ID = VSMC.STUDENT_ID
INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = FORMS.FORM_RUN_ID

LEFT JOIN VIEW_CONTACT_POSTAL_ADDRESS VCPA ON VCPA.CONTACT_ID = VSMC.CARER1_CONTACT_ID
LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID = VSMC.CARER1_CONTACT_ID
LEFT JOIN CONTACT CARER_EMAIL ON CARER_EMAIL.CONTACT_ID = VSMC.CARER1_CONTACT_ID

WHERE
  (house.house LIKE '%[[House=query_list(SELECT house FROM house WHERE status_flag = 0 ORDER BY LEFT(house,1))]]%'
  AND
  form_run.form_run LIKE '%[[Form=query_list(SELECT form_run.form_run FROM TABLE(edumate.get_current_form_runs(current date)) INNER JOIN form_run ON form_run.form_run_id = get_current_form_runs.form_run_id ORDER BY get_current_form_runs.form_id)]]%')

ORDER BY house.house, form_run.form_run, CONTACT.SURNAME, contact.preferred_name, CONTACT.FIRSTNAME