SELECT
  CONTACT.CONTACT_ID

FROM TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS(CURRENT DATE)) GCES

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GCES.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID

INNER JOIN VIEW_STUDENT_FORM_RUN VSFR ON VSFR.STUDENT_ID = GCES.STUDENT_ID AND (VSFR.FORM_RUN LIKE (TO_CHAR((CURRENT DATE), 'YYYY')) || ' %')

WHERE VSFR.FORM_RUN != (TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 07')

ORDER BY VSFR.FORM_RUN_ID