-- Future Students by Academic Year

-- This report presents the following information: Surname, Firstname, Expected Form Run, Status, Current School, and Next Interview Date.

SELECT
	CONTACT.SURNAME,
	CONTACT.FIRSTNAME,
	GENDER.GENDER,
	EXP_FORM_RUN,
	CASE student_status_id
		WHEN 1 THEN 'Application Cancelled'
		WHEN 2 THEN 'Alumni'
		WHEN 3 THEN 'Past Enrolment'
		WHEN 4 THEN 'Returning Enrolment'
		WHEN 5 THEN 'Current Enrolment'
		WHEN 6 THEN 'Place Accepted'
		WHEN 7 THEN 'Offered Place'
		WHEN 8 THEN 'Interview Pending'
		WHEN 9 THEN 'Wait Listed'
		WHEN 10 THEN 'Application Received'
		WHEN 11 THEN 'Information Sent'
		WHEN 12 THEN 'Enquiry'
		WHEN 13 THEN 'Interview Complete'
		WHEN 14 THEN 'Expired Offer'
		WHEN 15 THEN 'Expired Application'
		ELSE 'No Status'
	END AS "STATUS",
	PRIORITY.PRIORITY,
	EXTERNAL_SCHOOL.EXTERNAL_SCHOOL,
	ALLKIDS.NEXT_INTERVIEW

FROM TABLE(EDUMATE.GETALLSTUDENTSTATUS(current_date)) ALLKIDS

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = ALLKIDS.CONTACT_ID
INNER JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID
LEFT JOIN PRIORITY ON PRIORITY.PRIORITY_ID = ALLKIDS.PRIORITY_ID
INNER JOIN STU_ENROLMENT ON ALLKIDS.STUDENT_ID = STU_ENROLMENT.STUDENT_ID
INNER JOIN EXTERNAL_SCHOOL ON STU_ENROLMENT.PREV_SCHOOL_ID = EXTERNAL_SCHOOL.EXTERNAL_SCHOOL_ID

WHERE
	ALLKIDS.STUDENT_STATUS_ID NOT IN (12, 5)
		AND
	ALLKIDS.EXP_FORM_RUN = '[[Starting Year and Form=query_list(SELECT form_run.form_run FROM form_run WHERE form_run > TO_CHAR(YEAR(current date) + 1) || ' Year %' ORDER BY form_run)]]'

ORDER BY EXP_FORM_RUN ASC, ALLKIDS.PRIORITY_ID ASC, ALLKIDS.STUDENT_STATUS_ID ASC, GENDER.GENDER DESC, SURNAME ASC, EXTERNAL_SCHOOL ASC