WITH report_vars AS (
  SELECT
    ('[[As at=date]]') AS "REPORT_DATE"

  FROM SYSIBM.sysdummy1
),

raw_data AS (
  SELECT
    student.student_number,
    gender.gender_id,
    vsce.class,
    student.house_id,
    house.house
  
  FROM TABLE(edumate.getallstudentstatus((SELECT report_date FROM report_vars))) gass
  
  INNER JOIN student ON student.student_id = gass.student_id
  INNER JOIN contact ON contact.contact_id = student.contact_id
  LEFT JOIN gender ON gender.gender_id = contact.gender_id
  LEFT JOIN house ON house.house_id = student.house_id
  LEFT JOIN view_student_class_enrolment vsce ON vsce.student_id = gass.student_id AND vsce.class_type_id = 2 AND vsce.start_date <= (SELECT report_date FROM report_vars) AND vsce.end_date > (current date)
  
  WHERE gass.student_status_id = 5
)

SELECT
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Brady' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M1_M_BRADY",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Brady' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M1_F_BRADY",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Brady' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M2_M_BRADY",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Brady' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M2_F_BRADY",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Brady' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M3_M_BRADY",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Brady' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M3_F_BRADY",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Brady' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M4_M_BRADY",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Brady' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M4_F_BRADY",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Brady' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S1_M_BRADY",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Brady' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S1_F_BRADY",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Brady' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S2_M_BRADY",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Brady' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S2_F_BRADY",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Brady' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S3_M_BRADY",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Brady' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S3_F_BRADY",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Cassidy' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M1_M_CASSIDY",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Cassidy' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M1_F_CASSIDY",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Cassidy' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M2_M_CASSIDY",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Cassidy' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M2_F_CASSIDY",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Cassidy' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M3_M_CASSIDY",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Cassidy' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M3_F_CASSIDY",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Cassidy' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M4_M_CASSIDY",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Cassidy' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M4_F_CASSIDY",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Cassidy' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S1_M_CASSIDY",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Cassidy' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S1_F_CASSIDY",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Cassidy' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S2_M_CASSIDY",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Cassidy' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S2_F_CASSIDY",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Cassidy' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S3_M_CASSIDY",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Cassidy' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S3_F_CASSIDY",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Caulfield' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M1_M_CAULFIELD",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Caulfield' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M1_F_CAULFIELD",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Caulfield' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M2_M_CAULFIELD",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Caulfield' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M2_F_CAULFIELD",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Caulfield' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M3_M_CAULFIELD",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Caulfield' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M3_F_CAULFIELD",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Caulfield' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M4_M_CAULFIELD",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Caulfield' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M4_F_CAULFIELD",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Caulfield' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S1_M_CAULFIELD",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Caulfield' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S1_F_CAULFIELD",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Caulfield' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S2_M_CAULFIELD",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Caulfield' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S2_F_CAULFIELD",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Caulfield' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S3_M_CAULFIELD",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Caulfield' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S3_F_CAULFIELD",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Delaney' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M1_M_DELANEY",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Delaney' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M1_F_DELANEY",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Delaney' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M2_M_DELANEY",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Delaney' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M2_F_DELANEY",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Delaney' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M3_M_DELANEY",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Delaney' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M3_F_DELANEY",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Delaney' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M4_M_DELANEY",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Delaney' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M4_F_DELANEY",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Delaney' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S1_M_DELANEY",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Delaney' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S1_F_DELANEY",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Delaney' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S2_M_DELANEY",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Delaney' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S2_F_DELANEY",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Delaney' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S3_M_DELANEY",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Delaney' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S3_F_DELANEY",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Dwyer' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M1_M_DWYER",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Dwyer' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M1_F_DWYER",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Dwyer' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M2_M_DWYER",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Dwyer' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M2_F_DWYER",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Dwyer' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M3_M_DWYER",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Dwyer' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M3_F_DWYER",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Dwyer' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M4_M_DWYER",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Dwyer' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M4_F_DWYER",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Dwyer' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S1_M_DWYER",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Dwyer' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S1_F_DWYER",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Dwyer' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S2_M_DWYER",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Dwyer' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S2_F_DWYER",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Dwyer' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S3_M_DWYER",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Dwyer' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S3_F_DWYER",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'McLaughlin' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M1_M_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'McLaughlin' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M1_F_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'McLaughlin' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M2_M_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'McLaughlin' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M2_F_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'McLaughlin' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M3_M_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'McLaughlin' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M3_F_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'McLaughlin' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M4_M_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'McLaughlin' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M4_F_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'McLaughlin' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S1_M_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'McLaughlin' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S1_F_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'McLaughlin' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S2_M_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'McLaughlin' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S2_F_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'McLaughlin' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S3_M_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'McLaughlin' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S3_F_MCLAUGHLIN",
  SUM(CASE WHEN class LIKE '%MS1' AND house LIKE '%Connor' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M1_M_OCONNOR",
  SUM(CASE WHEN class LIKE '%MS1' AND house LIKE '%Connor' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M1_F_OCONNOR",
  SUM(CASE WHEN class LIKE '%MS2' AND house LIKE '%Connor' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M2_M_OCONNOR",
  SUM(CASE WHEN class LIKE '%MS2' AND house LIKE '%Connor' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M2_F_OCONNOR",
  SUM(CASE WHEN class LIKE '%MS3' AND house LIKE '%Connor' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M3_M_OCONNOR",
  SUM(CASE WHEN class LIKE '%MS3' AND house LIKE '%Connor' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M3_F_OCONNOR",
  SUM(CASE WHEN class LIKE '%MS4' AND house LIKE '%Connor' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M4_M_OCONNOR",
  SUM(CASE WHEN class LIKE '%MS4' AND house LIKE '%Connor' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M4_F_OCONNOR",
  SUM(CASE WHEN class LIKE '%SS1' AND house LIKE '%Connor' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S1_M_OCONNOR",
  SUM(CASE WHEN class LIKE '%SS1' AND house LIKE '%Connor' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S1_F_OCONNOR",
  SUM(CASE WHEN class LIKE '%SS2' AND house LIKE '%Connor' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S2_M_OCONNOR",
  SUM(CASE WHEN class LIKE '%SS2' AND house LIKE '%Connor' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S2_F_OCONNOR",
  SUM(CASE WHEN class LIKE '%SS3' AND house LIKE '%Connor' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S3_M_OCONNOR",
  SUM(CASE WHEN class LIKE '%SS3' AND house LIKE '%Connor' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S3_F_OCONNOR",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Vaughan' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M1_M_VAUGHAN",
  SUM(CASE WHEN class LIKE '%MS1' AND house = 'Vaughan' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M1_F_VAUGHAN",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Vaughan' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M2_M_VAUGHAN",
  SUM(CASE WHEN class LIKE '%MS2' AND house = 'Vaughan' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M2_F_VAUGHAN",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Vaughan' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M3_M_VAUGHAN",
  SUM(CASE WHEN class LIKE '%MS3' AND house = 'Vaughan' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M3_F_VAUGHAN",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Vaughan' AND gender_id = 2 THEN 1 ELSE 0 END) AS "M4_M_VAUGHAN",
  SUM(CASE WHEN class LIKE '%MS4' AND house = 'Vaughan' AND gender_id = 3 THEN 1 ELSE 0 END) AS "M4_F_VAUGHAN",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Vaughan' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S1_M_VAUGHAN",
  SUM(CASE WHEN class LIKE '%SS1' AND house = 'Vaughan' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S1_F_VAUGHAN",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Vaughan' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S2_M_VAUGHAN",
  SUM(CASE WHEN class LIKE '%SS2' AND house = 'Vaughan' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S2_F_VAUGHAN",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Vaughan' AND gender_id = 2 THEN 1 ELSE 0 END) AS "S3_M_VAUGHAN",
  SUM(CASE WHEN class LIKE '%SS3' AND house = 'Vaughan' AND gender_id = 3 THEN 1 ELSE 0 END) AS "S3_F_VAUGHAN",
  SUM(CASE WHEN class LIKE '%MS1' THEN 1 ELSE 0 END) AS "TOTAL_M1",
  SUM(CASE WHEN class LIKE '%MS2' THEN 1 ELSE 0 END) AS "TOTAL_M2",
  SUM(CASE WHEN class LIKE '%MS3' THEN 1 ELSE 0 END) AS "TOTAL_M3",
  SUM(CASE WHEN class LIKE '%MS4' THEN 1 ELSE 0 END) AS "TOTAL_M4",
  SUM(CASE WHEN class LIKE '%SS1' THEN 1 ELSE 0 END) AS "TOTAL_S1",
  SUM(CASE WHEN class LIKE '%SS2' THEN 1 ELSE 0 END) AS "TOTAL_S2",
  SUM(CASE WHEN class LIKE '%SS3' THEN 1 ELSE 0 END) AS "TOTAL_S3",

  SUM(CASE WHEN house = 'Brady' THEN 1 ELSE 0 END) AS "TOTAL_BRADY",
  SUM(CASE WHEN house = 'Cassidy' THEN 1 ELSE 0 END) AS "TOTAL_CASSIDY",
  SUM(CASE WHEN house = 'Caulfield' THEN 1 ELSE 0 END) AS "TOTAL_CAULFIELD",
  SUM(CASE WHEN house = 'Delaney' THEN 1 ELSE 0 END) AS "TOTAL_DELANEY",
  SUM(CASE WHEN house = 'Dwyer' THEN 1 ELSE 0 END) AS "TOTAL_DWYER",
  SUM(CASE WHEN house = 'McLaughlin' THEN 1 ELSE 0 END) AS "TOTAL_MCLAUGHLIN",
  SUM(CASE WHEN house LIKE '%Connor' THEN 1 ELSE 0 END) AS "TOTAL_OCONNOR",
  SUM(CASE WHEN house = 'Vaughan' THEN 1 ELSE 0 END) AS "TOTAL_VAUGHAN",
  SUM(CASE WHEN house IS NOT null THEN 1 ELSE 0 END) AS "TOTAL_ALL_HOUSES",

  SUM(CASE WHEN house = 'Brady' AND gender_id = 2 THEN 1 ELSE 0 END) AS "TOTAL_BRADY_MALES",
  SUM(CASE WHEN house = 'Cassidy' AND gender_id = 2 THEN 1 ELSE 0 END) AS "TOTAL_CASSIDY_MALES",
  SUM(CASE WHEN house = 'Caulfield' AND gender_id = 2 THEN 1 ELSE 0 END) AS "TOTAL_CAULFIELD_MALES",
  SUM(CASE WHEN house = 'Delaney' AND gender_id = 2 THEN 1 ELSE 0 END) AS "TOTAL_DELANEY_MALES",
  SUM(CASE WHEN house = 'Dwyer' AND gender_id = 2 THEN 1 ELSE 0 END) AS "TOTAL_DWYER_MALES",
  SUM(CASE WHEN house = 'McLaughlin' AND gender_id = 2 THEN 1 ELSE 0 END) AS "TOTAL_MCLAUGHLIN_MALES",
  SUM(CASE WHEN house LIKE '%Connor' AND gender_id = 2 THEN 1 ELSE 0 END) AS "TOTAL_OCONNOR_MALES",
  SUM(CASE WHEN house = 'Vaughan' AND gender_id = 2 THEN 1 ELSE 0 END) AS "TOTAL_VAUGHAN_MALES",
  SUM(CASE WHEN house = 'Brady' AND gender_id = 3 THEN 1 ELSE 0 END) AS "TOTAL_BRADY_FEMALES",
  SUM(CASE WHEN house = 'Cassidy' AND gender_id = 3 THEN 1 ELSE 0 END) AS "TOTAL_CASSIDY_FEMALES",
  SUM(CASE WHEN house = 'Caulfield' AND gender_id = 3 THEN 1 ELSE 0 END) AS "TOTAL_CAULFIELD_FEMALES",
  SUM(CASE WHEN house = 'Delaney' AND gender_id = 3 THEN 1 ELSE 0 END) AS "TOTAL_DELANEY_FEMALES",
  SUM(CASE WHEN house = 'Dwyer' AND gender_id = 3 THEN 1 ELSE 0 END) AS "TOTAL_DWYER_FEMALES",
  SUM(CASE WHEN house = 'McLaughlin' AND gender_id = 3 THEN 1 ELSE 0 END) AS "TOTAL_MCLAUGHLIN_FEMALES",
  SUM(CASE WHEN house LIKE '%Connor' AND gender_id = 3 THEN 1 ELSE 0 END) AS "TOTAL_OCONNOR_FEMALES",
  SUM(CASE WHEN house = 'Vaughan' AND gender_id = 3 THEN 1 ELSE 0 END) AS "TOTAL_VAUGHAN_FEMALES",
  SUM(CASE WHEN house IS NOT null AND gender_id = 2 THEN 1 ELSE 0 END) AS "TOTAL_ALL_MALES",
  SUM(CASE WHEN house IS NOT null AND gender_id = 3 THEN 1 ELSE 0 END) AS "TOTAL_ALL_FEMALES",
  SUM(CASE WHEN house IS null THEN 1 ELSE 0 END) AS "MISSING_HOUSES",
  SUM(CASE WHEN class IS null THEN 1 ELSE 0 END) AS "MISSING_HOMEROOMS"

FROM raw_data