WITH ALL_FAMILIES AS (
SELECT
  ROW_NUMBER() OVER () AS "SORT_ORDER",
  STUDENT.STUDENT_NUMBER AS "LOOKUP_CODE",
  CONTACT.CONTACT_ID,
  CONTACT.SURNAME,
  CONTACT.FIRSTNAME,
  FORM_RUN.FORM_RUN,
  VSCE.CLASS

FROM TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS(CURRENT DATE)) CES

INNER JOIN STUDENT ON CES.STUDENT_ID = STUDENT.STUDENT_ID
INNER JOIN CONTACT ON STUDENT.CONTACT_ID = CONTACT.CONTACT_ID
INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID =
(
    SELECT FORM_RUN.FORM_RUN_ID
    FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) GRSFR
    INNER JOIN FORM_RUN ON GRSFR.FORM_RUN_ID = FORM_RUN.FORM_RUN_ID
    WHERE GRSFR.STUDENT_ID = CES.STUDENT_ID
    FETCH FIRST 1 ROW ONLY
)
INNER JOIN FORM ON FORM.FORM_ID = FORM_RUN.FORM_ID
-- Get Homeroom
LEFT JOIN view_student_class_enrolment vsce ON vsce.student_id = ces.student_id AND
(
  vsce.class_type_id = 2
  AND
  vsce.academic_year = YEAR(current date)
  AND
  vsce.start_date <= (current date)
  AND
  vsce.end_date >= (current date)
)

LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON CONTACT.CONTACT_ID = VCHA.CONTACT_ID

WHERE
  CES.STUDENT_ID = (
    SELECT CESINNER.STUDENT_ID
    FROM TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS(CURRENT DATE)) CESINNER
    INNER JOIN STUDENT ON CESINNER.STUDENT_ID = STUDENT.STUDENT_ID
    INNER JOIN CONTACT ON STUDENT.CONTACT_ID = CONTACT.CONTACT_ID
    INNER JOIN CONTACT_ADDRESS CAINNER ON STUDENT.CONTACT_ID = CAINNER.CONTACT_ID
    WHERE VCHA.ADDRESS_ID = CAINNER.ADDRESS_ID
    -- Oldest child only
    ORDER BY CONTACT.BIRTHDATE ASC
    FETCH FIRST 1 ROW ONLY
  ) AND FORM.SHORT_NAME != '7'

ORDER BY FORM_RUN.FORM_RUN, VSCE.CLASS, CONTACT.SURNAME, SORT_ORDER
),

COUNTS AS (
SELECT COUNT(CONTACT_ID) AS "TOTAL" FROM ALL_FAMILIES
)

SELECT
  LOOKUP_CODE,
  SURNAME,
  FIRSTNAME,
  FORM_RUN,
  CLASS,
  (CASE WHEN ALL_FAMILIES.SORT_ORDER = 1 THEN COUNTS.TOTAL ELSE NULL END) AS "TOTAL_FAMILIES"

FROM ALL_FAMILIES

CROSS JOIN COUNTS