-- Students by Start Date

-- A filterable list of students by start date.

SELECT
  GASS.START_DATE,
  STUDENT.STUDENT_NUMBER AS "LOOKUP_CODE",
  CONTACT.SURNAME,
  CONTACT.FIRSTNAME,
  FORM.SHORT_NAME AS "FORM",
  VSCE.CLASS,
  STUDENT_STATUS.STUDENT_STATUS,
  EXTERNAL_SCHOOL.EXTERNAL_SCHOOL AS "PREVIOUS_SCHOOL",
  STU_ENROLMENT.DATE_APPLICATION

FROM STUDENT

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
INNER JOIN TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT DATE)) GASS ON GASS.STUDENT_ID = STUDENT.STUDENT_ID
INNER JOIN form_run ON form_run.form_run_id =
  (
    SELECT form_run.form_run_id
    FROM TABLE(EDUMATE.get_enroled_students_form_run(current date)) grsfr
    INNER JOIN form_run ON grsfr.form_run_id = form_run.form_run_id
    WHERE grsfr.student_id = gass.student_id
    FETCH FIRST 1 ROW ONLY
  )
INNER JOIN FORM ON FORM.FORM_ID = FORM_RUN.FORM_ID
INNER JOIN VIEW_STUDENT_CLASS_ENROLMENT VSCE ON VSCE.STUDENT_ID = STUDENT.STUDENT_ID
    AND VSCE.CLASS_TYPE_ID = 2
    AND VSCE.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY')
    AND
      (VSCE.START_DATE <= (CURRENT DATE)
      AND
      VSCE.END_DATE >= (CURRENT DATE))
LEFT JOIN STUDENT_STATUS ON STUDENT_STATUS.STUDENT_STATUS_ID = GASS.STUDENT_STATUS_ID
LEFT JOIN STU_ENROLMENT ON STU_ENROLMENT.STUDENT_ID = STUDENT.STUDENT_ID
LEFT JOIN EXTERNAL_SCHOOL ON EXTERNAL_SCHOOL.EXTERNAL_SCHOOL_ID = STU_ENROLMENT.PREV_SCHOOL_ID

WHERE GASS.START_DATE BETWEEN
  '[[Start Date (Start)=date]]'
  AND
  '[[Start Date (End)=date]]'

ORDER BY GASS.FORM_RUNS, SURNAME, START_DATE