SELECT
  CONTACT.FIRSTNAME,
  CONTACT.SURNAME,
  '(' || PHONE.AREA_CODE || ')' || ' ' || PHONE.PHONE AS "HOME_PHONE",
  CONTACT.MOBILE_PHONE

FROM STAFF

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN CONTACT_ADDRESS ON CONTACT_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN ADDRESS ON ADDRESS.ADDRESS_ID = CONTACT_ADDRESS.ADDRESS_ID
INNER JOIN PHONE ON PHONE.PHONE_ID = ADDRESS.PHONE_NUMBER
INNER JOIN STAFF_EMPLOYMENT SE ON STAFF.STAFF_ID = SE.STAFF_ID
INNER JOIN EMPLOYMENT_TYPE ON EMPLOYMENT_TYPE.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID
INNER JOIN GROUP_MEMBERSHIP ON GROUP_MEMBERSHIP.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN GROUPS ON GROUPS.GROUPS_ID = GROUP_MEMBERSHIP.GROUPS_ID AND GROUPS.GROUPS_ID = 3

WHERE
  GROUPS.GROUPS_ID = 3
    AND
  CONTACT.SURNAME NOT LIKE 'Coach'
    AND
  SE.EMPLOYMENT_TYPE_ID IN (1,2,4)
    AND
  STAFF.STAFF_ID NOT IN (1,1057)
    AND
  --Remove 'non staff' staff
  STAFF.STAFF_NUMBER NOT IN (10144, 25463, 8982, 11016, 10258, 11936, 23406, 7651, 24846, 10257, 23795, 25088, 8903)
    AND
  SE.START_DATE <= current_date
    AND
  (SE.END_DATE IS NULL
    OR
  SE.END_DATE > current_date)

ORDER BY SURNAME