SELECT
  GSOD.ID AS "GROUPINGS",
  GSOD.REPLACEMENT,
  (TO_CHAR((CURRENT DATE), 'Day DD Month YYYY')) || '<br>' || GSOD.PERIOD || ' (' || CHAR(TIME(GSOD.START_TIME),USA) || ' to ' || CHAR(TIME(GSOD.END_TIME + 1 MINUTE),USA) || ')' AS "PERIOD_TIME_AND_DATE",
  GSOD.CLASS,
  GSOD.ID AS "CLASS_ID",
  GSOD.LOCATION,
  GSOD.STUDENT_COUNT,
  GSOD.FIRSTNAME || ' ' || GSOD.SURNAME AS "ORIGINAL"

FROM TABLE(EDUMATE.GET_SCHEDULES_ON_DATE ('[[As at date=date]]')) GSOD

WHERE 
  GSOD.REPLACEMENT_STAFF_ID IS NOT NULL
  AND
  GSOD.REPLACEMENT_STAFF_ID IN (SELECT STAFF_ID FROM STAFF_EMPLOYMENT WHERE EMPLOYMENT_TYPE_ID IN (3,4))

ORDER BY GSOD.REPLACEMENT_STAFF_ID, GSOD.PERIOD_ID