WITH STAFF_ABSENCES AS
(
  SELECT
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SA.STAFF_ID,
    AWAY_REASON.AWAY_REASON,
    FROM_DATE,
    TO_DATE
  
  FROM STAFF_AWAY SA
  
  INNER JOIN STAFF ON STAFF.STAFF_ID = SA.STAFF_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
  INNER JOIN AWAY_REASON ON SA.AWAY_REASON_ID = AWAY_REASON.AWAY_REASON_ID
),

CASUALS AS
(
  SELECT
    CONTACT.FIRSTNAME AS "CASUAL_FIRSTNAME",
    CONTACT.SURNAME AS "CASUAL_SURNAME",
    SCHEDS.STAFF_ID,
    REPLACEMENT_STAFF_ID

  FROM TABLE(EDUMATE.GET_SCHEDULES_ON_DATE(CURRENT DATE)) SCHEDS

  INNER JOIN STAFF ON STAFF.STAFF_ID = SCHEDS.REPLACEMENT_STAFF_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID

  WHERE REPLACEMENT_STAFF_ID IS NOT NULL
),

COMBINED_REPORT AS
(
  SELECT DISTINCT
    FIRSTNAME,
    SURNAME,
    STAFF_ABSENCES.AWAY_REASON,
    FROM_DATE AS "AWAY_FROM",
    TO_DATE AS "AWAY_TO",
    CASUALS.CASUAL_FIRSTNAME,
    CASUALS.CASUAL_SURNAME

  FROM STAFF_ABSENCES

  LEFT JOIN CASUALS ON CASUALS.STAFF_ID = STAFF_ABSENCES.STAFF_ID
)

SELECT * FROM COMBINED_REPORT ORDER BY SURNAME