WITH CASUAL_HISTORY AS
(
	SELECT 
	    CONTACT.FIRSTNAME,
	    CONTACT.SURNAME,
	    CONTACT.CONTACT_ID,
	    TO_CHAR(EFFECTIVE_DATE,'DD/MM/YYYY') AS DATE_ON,
	    FLOAT(TIME_WORKED)/2 AS TIME_WORKED

	FROM AVAILABLE_CASUAL AC

    INNER JOIN STAFF ON STAFF.STAFF_ID = AC.STAFF_ID
    INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID

	WHERE
		AC.FROM_DATE >= [[mainquery.FNIGHT_BEGIN]]
			AND
		AC.TO_DATE <= [[mainquery.FNIGHT_END]]
),

CASUAL_TOTALS AS
(
	SELECT
	    FIRSTNAME,
	    SURNAME,
	    CONTACT_ID,
	    'TOTAL' AS DATE_ON,
	    SUM(TIME_WORKED) AS TIME_WORKED

	FROM CASUAL_HISTORY

	GROUP BY SURNAME, FIRSTNAME, CONTACT_ID
),

RAW_REPORT AS
(
	SELECT * FROM CASUAL_HISTORY
	UNION ALL
	SELECT * FROM CASUAL_TOTALS
)

SELECT
    FIRSTNAME || ' ' || SURNAME AS "CASUAL_FULLNAME",
    FIRSTNAME,
    SURNAME,
    DATE_ON AS "CASUAL_DATE_ON",
    TIME_WORKED AS "CASUAL_TIME_WORKED"

FROM RAW_REPORT

ORDER BY SURNAME, FIRSTNAME, CASUAL_DATE_ON