WITH CASUALS_DATA AS (
  SELECT
    CONTACT.SURNAME,
    CONTACT.FIRSTNAME,
    TO_CHAR((FROM_DATE), 'DD Mon, YYYY') AS "FROM_DATE",
    TO_DATE,
    CASE WHEN AC.TIME_WORKED = 1 THEN 'Half Day' ELSE 'Full day' END AS "ALLOCATION"
  
  FROM AVAILABLE_CASUAL AC
  
  INNER JOIN STAFF ON STAFF.STAFF_ID = AC.STAFF_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
  INNER JOIN STAFF_EMPLOYMENT SE ON SE.STAFF_ID = AC.STAFF_ID

  WHERE
    DATE(AC.FROM_DATE) >= DATE(current date - 13 days)
    AND
    DATE(AC.TO_DATE) <= DATE(current date)
)

SELECT
  CD.SURNAME,
  CD.FIRSTNAME,
  CD.FROM_DATE AS "DATES",
  CD.ALLOCATION

FROM CASUALS_DATA CD

ORDER BY CD.SURNAME, CD.FROM_DATE