WITH STAFF_ABSENCES AS
	(
	SELECT
		CONTACT.FIRSTNAME || ' ' || CONTACT.SURNAME AS "FULLNAME",
    CONTACT.SURNAME,	
		AWAY_REASON.AWAY_REASON,
		FROM_DATE,
		TO_DATE,
		CASE WHEN FROM_DATE < DATE('[[Fortnight Beginning=date]]') THEN TO_CHAR('[[Fortnight Beginning=date]]', 'Month DD') ELSE TO_CHAR(FROM_DATE, 'Month DD - HH:MM PM') END AS EFFECTIVE_START,
		CASE WHEN TO_DATE > DATE('[[Fortnight Ending=date]]') THEN TO_CHAR('[[Fortnight Ending=date]]', 'Month DD') ELSE TO_CHAR(TO_DATE, 'Month DD - HH:MM PM') END AS EFFECTIVE_END,
		DATE('[[Fortnight Beginning=date]]') AS "FNIGHT_BEGIN",
		DATE('[[Fortnight Ending=date]]') AS "FNIGHT_END",
		COMMENT AS "REASON",
		CASE WHEN SA.AWAY_REASON_ID IN (74,5) THEN COMMENT END AS "PD_REASON"
	
	FROM STAFF_AWAY SA
	
	INNER JOIN STAFF ON SA.STAFF_ID = STAFF.STAFF_ID
	INNER JOIN CONTACT ON STAFF.CONTACT_ID = CONTACT.CONTACT_ID
	INNER JOIN AWAY_REASON ON SA.AWAY_REASON_ID = AWAY_REASON.AWAY_REASON_ID
	
	WHERE
		FROM_DATE <= DATE('[[Fortnight Ending=date]]')
			AND
		TO_DATE > DATE('[[Fortnight Beginning=date]]')
	)
		
SELECT *
FROM STAFF_ABSENCES	
ORDER BY SURNAME, AWAY_REASON