WITH CASUAL_HISTORY AS
(
	SELECT 
	    CONTACT.FIRSTNAME,
	    CONTACT.SURNAME,
	    CONTACT.CONTACT_ID,
	    TO_CHAR(EFFECTIVE_DATE,'DD/MM/YYYY') AS DATE_ON,
	    FLOAT(TIME_WORKED)/2 AS TIME_WORKED

	FROM AVAILABLE_CASUAL

    INNER JOIN STAFF ON STAFF.STAFF_ID = AVAILABLE_CASUAL.STAFF_ID
    INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID

	WHERE
		FROM_DATE >= DATE(CURRENT DATE - 42 DAYS)
	    AND
	    TO_DATE <= DATE(CURRENT DATE)
),

CASUAL_TOTALS AS
(
	SELECT
	    FIRSTNAME,
	    SURNAME,
	    CONTACT_ID,
	    'TOTAL' AS DATE_ON,
	    SUM(TIME_WORKED) AS TIME_WORKED

	FROM CASUAL_HISTORY

	GROUP BY SURNAME, FIRSTNAME, CONTACT_ID
),

RAW_REPORT AS
(
	SELECT * FROM CASUAL_HISTORY
	UNION ALL
	SELECT * FROM CASUAL_TOTALS
)

SELECT
    FIRSTNAME,
    SURNAME,
    DATE_ON,
    TIME_WORKED

FROM RAW_REPORT

ORDER BY SURNAME, FIRSTNAME, DATE_ON