WITH STAFFBASE AS
(
  SELECT
    STAFF_NUMBER,
    CONTACT.CONTACT_ID,
    CONTACT.SURNAME,
    CONTACT.FIRSTNAME,
    (CASE
      WHEN VIEW_CONTACT_HOME_ADDRESS.ADDRESS1 = ''
      THEN VIEW_CONTACT_HOME_ADDRESS.ADDRESS2 || '<br>' || VIEW_CONTACT_HOME_ADDRESS.ADDRESS3
      ELSE VIEW_CONTACT_HOME_ADDRESS.ADDRESS1 || '<br>' || VIEW_CONTACT_HOME_ADDRESS.ADDRESS2 || '<br>' || VIEW_CONTACT_HOME_ADDRESS.ADDRESS3
    END) AS "HOME_ADDRESS",
    '(' || PHONE.AREA_CODE || ')' || ' ' || PHONE.PHONE AS "HOME_PHONE",
    CONTACT.MOBILE_PHONE,
    CAR.CAR_MAKE,
    CAR.CAR_MODEL,
    CAR.CAR_REGO,
    CONTACT.BIRTHDATE,
    SE.EMPLOYMENT_TYPE_ID,
    EMPLOYMENT_TYPE.EMPLOYMENT_TYPE,
    SE.START_DATE,
    SE.END_DATE,
    CONTACT_QUALIFICATION.YEAR_TEACHING AS "YEAR_TEACHING"

  FROM STAFF

  LEFT JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN CONTACT_ADDRESS ON CONTACT_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN ADDRESS ON ADDRESS.ADDRESS_ID = CONTACT_ADDRESS.ADDRESS_ID
  LEFT JOIN PHONE ON PHONE.PHONE_ID = ADDRESS.PHONE_NUMBER
  LEFT JOIN VIEW_CONTACT_HOME_ADDRESS ON VIEW_CONTACT_HOME_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN CAR ON CAR.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN STAFF_EMPLOYMENT SE ON STAFF.STAFF_ID = SE.STAFF_ID
  LEFT JOIN EMPLOYMENT_TYPE ON EMPLOYMENT_TYPE.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID

  LEFT JOIN CONTACT_QUALIFICATION ON CONTACT_QUALIFICATION.CONTACT_ID = STAFF.CONTACT_ID
  
  WHERE
    CONTACT.SURNAME NOT LIKE 'Coach'
      AND
    SE.EMPLOYMENT_TYPE_ID IN (1,2,4)
      AND
    STAFF.STAFF_ID != '1'
      AND
    SE.START_DATE <= current_date
      AND
    SE.END_DATE IS NULL
      OR
    SE.END_DATE > current_date
)

SELECT
  STAFFBASE.CONTACT_ID,
  STAFFBASE.STAFF_NUMBER,
  SURNAME,
  FIRSTNAME,
  EMPLOYMENT_TYPE,
  HOME_ADDRESS,
  HOME_PHONE,
  MOBILE_PHONE,
  CAR_MAKE,
  CAR_MODEL,
  CAR_REGO,
  BIRTHDATE,
  YEAR_TEACHING,
  START_DATE,
  END_DATE

FROM STAFFBASE

ORDER BY SURNAME