WITH RAW_DATA AS
(
	SELECT
		ROW_NUMBER() OVER (PARTITION BY CONTACT.CONTACT_ID ORDER BY SURNAME),
		CONTACT.SURNAME,
		CONTACT.FIRSTNAME,
		TO_CHAR(FROM_DATE, 'Month DD, YYYY') AS "FROM",
		TO_CHAR(TO_DATE, 'Month DD, YYYY') AS "TO",
		AWAY_REASON.AWAY_REASON
	
	FROM STAFF_AWAY SA
	
	INNER JOIN STAFF ON SA.STAFF_ID = STAFF.STAFF_ID
	INNER JOIN CONTACT ON STAFF.CONTACT_ID = CONTACT.CONTACT_ID
	INNER JOIN AWAY_REASON ON SA.AWAY_REASON_ID = AWAY_REASON.AWAY_REASON_ID
	
	WHERE
		FROM_DATE >= (CURRENT DATE - 21 DAYS)
			AND
		TO_DATE <= (CURRENT DATE)
)

SELECT
	CASE WHEN ROWNUM = 1 THEN FIRSTNAME ELSE '' END AS "FIRSTNAME",
    CASE WHEN ROWNUM = 1 THEN SURNAME ELSE '' END AS "SURNAME",
    FROM,
    TO,
    AWAY_REASON

FROM RAW_DATA

ORDER BY RAW_DATA.SURNAME, RAW_DATA.FIRSTNAME, RAW_DATA.ROWNUM