SELECT
  STAFF_NUMBER,
  C2.FIRSTNAME || ' ' || C2.SURNAME AS "EMERGENCY_CONTACT_NAME",
  REPLACE(
      CASE WHEN RELATIONSHIP_TYPE.SYSTEM = 'CHILD' THEN '(PARENT)' 
          WHEN RELATIONSHIP_TYPE.SYSTEM = 'SREPCHILD' THEN '(STEPPARENT)'
          WHEN RELATIONSHIP_TYPE.SYSTEM = 'NIECENEWPHE' THEN '(AUNT/UCLE)'
          WHEN RELATIONSHIP_TYPE.SYSTEM = 'GRANDCHILD' THEN '(GRANDPARENT)'
          WHEN RELATIONSHIP_TYPE.SYSTEM = 'GODCHILD' THEN '(GODPARENT)'
          WHEN RELATIONSHIP_TYPE.SYSTEM = 'CHARGE' THEN '(GUARDIAN)'
          WHEN RELATIONSHIP_TYPE.SYSTEM = 'HOMESTAYCH' THEN '(HOMESTAYPARENT)'
          WHEN RELATIONSHIP_TYPE.SYSTEM = 'GRANDNIECE' THEN '(GRAND AUNT/UNCLE)'
          WHEN RELATIONSHIP_TYPE.SYSTEM = 'GODNIECENE' THEN '(GOD AUNT/UNCLE)'
          WHEN RELATIONSHIP_TYPE.SYSTEM = 'CHILDINLAW' THEN '(PARENTINLAW)'
          WHEN RELATIONSHIP_TYPE.SYSTEM = 'FOSTERCHIL' THEN '(FOSTERPARENT)'
          ELSE '(' || RELATIONSHIP_TYPE.RELATIONSHIP_TYPE || ')' END,'_','/'
  ) AS "EMERGENCY_CONTACT_RELATION",
  CASE WHEN HOME2.PHONE != '' THEN 'Home: ' || HOME2.PHONE || (CASE WHEN WP2.PHONE IS NOT NULL OR C2.MOBILE_PHONE IS NOT NULL THEN ' | ' ELSE '' END) ELSE '' END ||
  CASE WHEN WP2.PHONE IS NOT NULL THEN 'Work: ' || '(' || WP2.AREA_CODE || ')' || WP2.PHONE || (CASE WHEN C2.MOBILE_PHONE IS NOT NULL THEN ' | ' ELSE '' END) ELSE '' END ||
  CASE WHEN C2.MOBILE_PHONE IS NOT NULL THEN 'Mobile: ' || C2.MOBILE_PHONE ELSE '' END
  AS EMERGENCY_NUMBERS

FROM STAFF

LEFT JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
LEFT JOIN CONTACT_ADDRESS ON CONTACT_ADDRESS.CONTACT_ID = CONTACT.CONTACT_ID
LEFT JOIN ADDRESS ON ADDRESS.ADDRESS_ID = CONTACT_ADDRESS.ADDRESS_ID AND ADDRESS.ADDRESS_TYPE_ID = 1
LEFT JOIN RELATIONSHIP ON (RELATIONSHIP.CONTACT_ID1 = CONTACT.CONTACT_ID OR RELATIONSHIP.CONTACT_ID2 = CONTACT.CONTACT_ID)
LEFT JOIN RELATIONSHIP_TYPE ON RELATIONSHIP_TYPE.RELATIONSHIP_TYPE_ID = RELATIONSHIP.RELATIONSHIP_TYPE_ID AND CALL_ORDER IN (1,2,3,4,5)
LEFT JOIN CONTACT C2 ON (C2.CONTACT_ID = RELATIONSHIP.CONTACT_ID1 OR C2.CONTACT_ID = RELATIONSHIP.CONTACT_ID2) AND C2.CONTACT_ID != CONTACT.CONTACT_ID
LEFT JOIN CARER CAR2 ON CAR2.CONTACT_ID = C2.CONTACT_ID
LEFT JOIN SALUTATION SAL2 ON SAL2.SALUTATION_ID = C2.SALUTATION_ID AND SAL2.SALUTATION != 'UNSPECIFIED'
LEFT JOIN WORK_DETAIL WD2 ON WD2.CONTACT_ID = C2.CONTACT_ID
LEFT JOIN PHONE WP2 ON WP2.PHONE_ID = WD2.DIRECT_LINE
LEFT JOIN VIEW_CONTACT_HOME_ADDRESS HOME2 ON HOME2.CONTACT_ID = C2.CONTACT_ID

WHERE CONTACT.CONTACT_ID = [[mainquery.contact_id]]

ORDER BY EMERGENCY_CONTACT_NAME