WITH TRAINING_COURSES_RAW AS
(
  SELECT
      STAFF.STAFF_NUMBER,
      STAFF_COURSE.DETAILS || ' (' || TO_CHAR(STAFF_COURSE.STARTDATE, 'DD Month YYYY') || ')' AS "DETAILS"
  
  FROM STAFF_COURSE
  
  LEFT JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF_COURSE.CONTACT_ID
  LEFT JOIN STAFF ON STAFF_COURSE.CONTACT_ID = STAFF.CONTACT_ID
  
  WHERE CONTACT.CONTACT_ID = [[mainquery.contact_id]]
    AND STARTDATE > (current_date - 1 YEAR)
    AND DETAILS IS NOT NULL
    AND STAFF_COURSE IS NOT NULL
    AND DETAILS NOT LIKE '$%'
    AND DETAILS NOT LIKE 'Free'
    AND DETAILS NOT LIKE 'nil'
)

SELECT
  STAFF_NUMBER,
  LISTAGG(DETAILS, ', ') WITHIN GROUP(ORDER BY STAFF_NUMBER) "ALL_COURSES"

FROM TRAINING_COURSES_RAW

GROUP BY STAFF_NUMBER