WITH QUALS_RAW AS
(
  SELECT
    QUALIFICATION,
    QUALIFICATION_TYPE.QUALIFICATION_TYPE,
    institute.institute AS "QUALIFICATION_INSTITUTE",
    TO_CHAR(QYEAR) AS "QYEAR"
  
  FROM QUALIFICATION
  
  LEFT JOIN CONTACT ON CONTACT.CONTACT_ID = QUALIFICATION.CONTACT_ID
  LEFT JOIN STAFF ON QUALIFICATION.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN QUALIFICATION_TYPE ON QUALIFICATION_TYPE.QUALIFICATION_TYPE_ID = QUALIFICATION.QUALIFICATION_TYPE_ID
  LEFT JOIN institute ON institute.institute_id = qualification.institute_id
  
  WHERE CONTACT.CONTACT_ID = [[mainquery.contact_id]]
)

SELECT * FROM quals_raw ORDER BY QYEAR DESC