WITH report_vars AS (SELECT '[[Due by=date]]' AS "DEADLINE" FROM SYSIBM.sysdummy1),

cars AS (
  SELECT
    contact_id,
    LISTAGG(COALESCE(car_make, '') || ' ' || COALESCE(car_model, '') || ' (' || COALESCE(car_rego, '') || ')', ', ') WITHIN GROUP(ORDER BY car_make, car_model, car_rego) AS "CARS"
    
  FROM car
  
  GROUP BY contact_id
),

STAFFBASE AS
(
  SELECT
    STAFF_NUMBER,
    CONTACT.CONTACT_ID,
    salutation.salutation,
    CONTACT.SURNAME,
    CONTACT.FIRSTNAME,
    CONTACT.PREFERRED_NAME,
    CONTACT.BIRTHDATE,
    gender.gender,
    house.house,
    GROUPS.GROUPS,
    (CASE
      WHEN VIEW_CONTACT_HOME_ADDRESS.ADDRESS1 = ''
      THEN VIEW_CONTACT_HOME_ADDRESS.ADDRESS2 || '<br>' || VIEW_CONTACT_HOME_ADDRESS.ADDRESS3
      ELSE VIEW_CONTACT_HOME_ADDRESS.ADDRESS1 || '<br>' || VIEW_CONTACT_HOME_ADDRESS.ADDRESS2 || '<br>' || VIEW_CONTACT_HOME_ADDRESS.ADDRESS3
    END) AS "HOME_ADDRESS",
    COALESCE(
      VIEW_CONTACT_DEFAULT_ADDRESS.PHONE,
      VIEW_CONTACT_HOME_ADDRESS.PHONE,
      VIEW_CONTACT_POSTAL_ADDRESS.PHONE
    ) AS "HOME_PHONE",
    CONTACT.MOBILE_PHONE,
    work_type.work_type AS "OCCUPATION",
    work_detail.title,
    CARS.CARS,
    SE.EMPLOYMENT_TYPE_ID,
    EMPLOYMENT_TYPE.EMPLOYMENT_TYPE,
    SE.START_DATE,
    SE.END_DATE,
    CONTACT_QUALIFICATION.YEAR_TEACHING,
    CONTACT_QUALIFICATION.YEAR_TEACH_AUSTRALIA,
    CONTACT_QUALIFICATION.YEAR_TEACH_STATE,
    CONTACT_QUALIFICATION.YEAR_TEACH_SCHOOL AS "YEAR_TEACHING_ROSEBANK",
    CONTACT.WWC_NUMBER,
    CONTACT.WWC_EXPIRY_DATE,
    religion.religion

  FROM STAFF

  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN salutation ON salutation.salutation_id = contact.salutation_id
  LEFT JOIN gender ON gender.gender_id = contact.gender_id
  LEFT JOIN house ON house.house_id = staff.house_id
  
  INNER JOIN GROUP_MEMBERSHIP ON GROUP_MEMBERSHIP.CONTACT_ID = STAFF.CONTACT_ID
  INNER JOIN GROUPS ON GROUPS.GROUPS_ID = GROUP_MEMBERSHIP.GROUPS_ID AND (GROUPS.GROUPS_ID = 386)
  
  LEFT JOIN VIEW_CONTACT_DEFAULT_ADDRESS ON VIEW_CONTACT_DEFAULT_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN VIEW_CONTACT_HOME_ADDRESS ON VIEW_CONTACT_HOME_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN VIEW_CONTACT_POSTAL_ADDRESS ON VIEW_CONTACT_POSTAL_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN VIEW_CONTACT_WORK_ADDRESS ON VIEW_CONTACT_WORK_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
  
  LEFT JOIN CARS ON CARS.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN STAFF_EMPLOYMENT SE ON STAFF.STAFF_ID = SE.STAFF_ID
  LEFT JOIN EMPLOYMENT_TYPE ON EMPLOYMENT_TYPE.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID
  LEFT JOIN WORK_DETAIL ON WORK_DETAIL.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN work_type ON work_type.work_type_id = work_detail.work_type_id
  
  LEFT JOIN religion ON religion.religion_id = contact.religion_id

  LEFT JOIN CONTACT_QUALIFICATION ON CONTACT_QUALIFICATION.CONTACT_ID = STAFF.CONTACT_ID
  
  WHERE group_membership.groups_id = 386
)

SELECT
  STAFFBASE.CONTACT_ID,
  STAFFBASE.STAFF_NUMBER,
  (SELECT TO_CHAR(deadline, 'Day DD Month') FROM report_vars) AS "DEADLINE",
  salutation,
  SURNAME,
  FIRSTNAME,
  (CASE WHEN PREFERRED_NAME IS NULL THEN NULL ELSE '(' || PREFERRED_NAME || ')' END) AS "PREFERRED_NAME",
  gender,
  house,
  EMPLOYMENT_TYPE,
  occupation,
  title,
  HOME_ADDRESS,
  HOME_PHONE,
  MOBILE_PHONE,
  CARS,
  TO_CHAR(BIRTHDATE, 'Month DD, YYYY') as "BIRTHDATE",
  religion,
  YEAR_TEACHING,
  YEAR_TEACH_AUSTRALIA,
  YEAR_TEACH_STATE,
  YEAR_TEACHING_ROSEBANK,
  TO_CHAR(START_DATE, 'Month DD, YYYY') as "START_DATE",
  END_DATE,
  WWC_NUMBER,
  WWC_EXPIRY_DATE

FROM STAFFBASE

ORDER BY LOWER(surname)