WITH RAW_DATA AS
(
	SELECT
		ROW_NUMBER() OVER (PARTITION BY CONTACT.CONTACT_ID ORDER BY SURNAME),
		SA.STAFF_ID,
		CONTACT.SURNAME,
		CONTACT.FIRSTNAME,
		TO_CHAR(FROM_DATE, 'Month DD, YYYY') AS "FROM",
		TO_CHAR(TO_DATE, 'Month DD, YYYY') AS "TO",
    CASE WHEN FROM_DATE < DATE(CURRENT DATE - 14 DAYS) THEN TO_CHAR((CURRENT DATE - 14 DAYS), 'Month DD') ELSE TO_CHAR(FROM_DATE, 'Month DD - HH:MM PM') END AS EFFECTIVE_START,
    CASE WHEN TO_DATE > DATE(CURRENT DATE) THEN TO_CHAR((CURRENT DATE), 'Month DD') ELSE TO_CHAR(TO_DATE, 'Month DD - HH:MM PM') END AS EFFECTIVE_END,
		AWAY_REASON.AWAY_REASON,
		CASE WHEN TO_CHAR((TO_DATE), 'DD-MM-YYYY') != TO_CHAR((FROM_DATE), 'DD-MM-YYYY') THEN (DAYS (TO_DATE) - DAYS (FROM_DATE)) ELSE 1 END AS "DAYS_ABSENT"
	
	FROM STAFF_AWAY SA
	
	INNER JOIN STAFF ON SA.STAFF_ID = STAFF.STAFF_ID
	INNER JOIN CONTACT ON STAFF.CONTACT_ID = CONTACT.CONTACT_ID
	INNER JOIN AWAY_REASON ON SA.AWAY_REASON_ID = AWAY_REASON.AWAY_REASON_ID
	
  WHERE
    FROM_DATE <= DATE(CURRENT DATE)
      AND
    TO_DATE > DATE(CURRENT DATE - 14 DAYS)
),

YTD_COUNT AS
(
  SELECT
    YTD.STAFF_ID,
    COUNT(AWAY_REASON) AS "YTD_COUNT"
  
  FROM STAFF_AWAY YTD

  INNER JOIN AWAY_REASON ON AWAY_REASON.AWAY_REASON_ID = YTD.AWAY_REASON_ID
  
  WHERE TO_CHAR((FROM_DATE), 'YYYY') = TO_CHAR((CURRENT DATE), 'YYYY')
  
  GROUP BY YTD.STAFF_ID
)

SELECT
  RAW_DATA.STAFF_ID,
  ROWNUM,
  DATE(CURRENT DATE - 14 DAYS) AS "FNIGHT_BEGIN",
  DATE(CURRENT DATE) AS "FNIGHT_END",
	CASE WHEN ROWNUM = 1 THEN FIRSTNAME ELSE '' END AS "FIRSTNAME",
  CASE WHEN ROWNUM = 1 THEN SURNAME ELSE '' END AS "SURNAME",
  EFFECTIVE_START,
  EFFECTIVE_END,
  DAYS_ABSENT,
  AWAY_REASON,
  YTD_COUNT.YTD_COUNT

FROM RAW_DATA

INNER JOIN YTD_COUNT ON YTD_COUNT.STAFF_ID = RAW_DATA.STAFF_ID

ORDER BY RAW_DATA.SURNAME, RAW_DATA.FIRSTNAME, RAW_DATA.ROWNUM, RAW_DATA.EFFECTIVE_START ASC, RAW_DATA.EFFECTIVE_END