WITH QUALS_RAW AS
(
  SELECT
    STAFF.STAFF_NUMBER,
    QUALIFICATION,
    QUALIFICATION_TYPE.QUALIFICATION_TYPE,
    TO_CHAR(QYEAR) AS "QYEAR"
  
  FROM QUALIFICATION
  
  LEFT JOIN CONTACT ON CONTACT.CONTACT_ID = QUALIFICATION.CONTACT_ID
  LEFT JOIN STAFF ON QUALIFICATION.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN QUALIFICATION_TYPE ON QUALIFICATION_TYPE.QUALIFICATION_TYPE_ID = QUALIFICATION.QUALIFICATION_TYPE_ID
  
  WHERE CONTACT.CONTACT_ID = [[mainquery.contact_id]]
)

SELECT
  STAFF_NUMBER,
  LISTAGG(QUALIFICATION || ' (' || QUALIFICATION_TYPE || ' - ' || CASE WHEN QYEAR IS NULL THEN 'Year Unknown' ELSE QYEAR END || ')',  ', ') WITHIN GROUP(ORDER BY STAFF_NUMBER) "ALL_QUALIFICATIONS"

FROM QUALS_RAW

GROUP BY STAFF_NUMBER