WITH REPORT_VARS AS (
  SELECT
    TO_CHAR((CURRENT DATE), 'YYYY') AS "CURRENT_YEAR",
    (SELECT START_DATE FROM TERM WHERE TERM = 'Term 1' AND START_DATE LIKE (TO_CHAR((CURRENT DATE), 'YYYY')) || '-%%-%%' FETCH FIRST 1 ROW ONLY) AS "YEAR_START",
    ('[[Report From Date=date]]') AS "REPORT_START",
    ('[[Report To Date=date]]') AS "REPORT_END"

    --DATE((CURRENT DATE - 14 DAYS)) AS "REPORT_START",
    --DATE(CURRENT DATE) AS "REPORT_END"

  FROM SYSIBM.SYSDUMMY1
),

STUDENT_ATTENDANCE_DATA AS (
  SELECT DISTINCT
    REPORT_VARS.REPORT_START,
    REPORT_VARS.REPORT_END,
    REPORT_VARS.YEAR_START,
    (SELECT
      (SUM(CASE WHEN GTRD.TERM_DATE <= (REPORT_VARS.REPORT_END) THEN 1 ELSE 0 END) / 10)
    FROM TABLE(EDUMATE.GET_TIMETABLE_RUNNING_DATES(
      (SELECT TIMETABLE_ID
      FROM TERM WHERE TERM = 'Term 1'
      AND
      START_DATE LIKE (TO_CHAR((CURRENT DATE), 'YYYY')) || '-%%-%%' FETCH FIRST 1 ROW ONLY))) GTRD
    INNER JOIN TERM ON TERM.TERM_ID = GTRD.TERM_ID
    WHERE GTRD.DAY_INDEX NOT IN (888, 999)
    ) AS "DIFF",
    GSFR.STUDENT_ID AS "ABSENCES_STUDENT_ID",
    CONTACT.FIRSTNAME AS "ABSENCES_FIRSTNAME",
    CONTACT.SURNAME AS "ABSENCES_SURNAME",
    FORM_RUN.FORM_RUN AS "ABSENCES_FORM_RUN",
    CLASS.CLASS AS "ABSENCES_HOMEROOM",
    DA.DATE_ON AS "ABSENCES_DATE_ON",
    ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID AS "ALL_ABSENCES"
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) GSFR
  
  INNER JOIN DAILY_ATTENDANCE DA ON DA.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  
  INNER JOIN TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS(CURRENT DATE)) GCES ON GCES.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN VIEW_STUDENT_CLASS_ENROLMENT VSCE ON VSCE.STUDENT_ID = GCES.STUDENT_ID
  INNER JOIN CLASS ON CLASS.CLASS_ID = VSCE.CLASS_ID AND CLASS.CLASS_TYPE_ID = 2 AND VSCE.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY') AND VSCE.END_DATE > (CURRENT_DATE)
  CROSS JOIN REPORT_VARS
  
  -- Absences join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DA.DAILY_ATTENDANCE_STATUS_ID
    AND (DA.DATE_ON BETWEEN REPORT_VARS.YEAR_START AND REPORT_VARS.REPORT_END)
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID IN (2,3,4,5,6,7)

  WHERE ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID IS NOT NULL

  ORDER BY FORM_RUN.FORM_RUN, CLASS.CLASS, CONTACT.SURNAME
),

ABSENCES_COUNTS AS (
  SELECT
    SAD.ABSENCES_STUDENT_ID,
    SUM(CASE WHEN SAD.ABSENCES_DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND SAD.ALL_ABSENCES IS NOT NULL THEN 1 ELSE 0 END) AS "FORTNIGHT_ABSENCES",
    SUM(CASE WHEN SAD.ABSENCES_DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND SAD.ALL_ABSENCES IN (3,5,6) THEN 1 ELSE 0 END) AS "EXPLAINED_ABSENCES",
    SUM(CASE WHEN SAD.ABSENCES_DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND SAD.ALL_ABSENCES IN (2,4,7) THEN 1 ELSE 0 END) AS "UNEXPLAINED_ABSENCES",
    COUNT(SAD.ALL_ABSENCES) AS "ABSENCES_YTD",
    SUM(CASE WHEN SAD.ALL_ABSENCES IN (3,5,6) THEN 1 ELSE 0 END) AS "EXPLAINED_ABSENCES_YTD",
    SUM(CASE WHEN SAD.ALL_ABSENCES IN (2,4,7) THEN 1 ELSE 0 END) AS "UNEXPLAINED_ABSENCES_YTD"
  
  FROM STUDENT_ATTENDANCE_DATA SAD
  
  GROUP BY SAD.ABSENCES_STUDENT_ID, SAD.ABSENCES_FORM_RUN
  
  ORDER BY SAD.ABSENCES_FORM_RUN
)

SELECT DISTINCT
  SAD.ABSENCES_FIRSTNAME,
  SAD.ABSENCES_SURNAME,
  SAD.ABSENCES_FORM_RUN,
  SAD.ABSENCES_HOMEROOM,
  AC.FORTNIGHT_ABSENCES,
  AC.EXPLAINED_ABSENCES,
  AC.UNEXPLAINED_ABSENCES,
  AC.ABSENCES_YTD,
  AC.EXPLAINED_ABSENCES_YTD,
  AC.UNEXPLAINED_ABSENCES_YTD,
  CAST((CAST(AC.ABSENCES_YTD AS DECIMAL(3,1)) / CAST(SAD.DIFF AS DECIMAL(3,1))) AS DECIMAL(3,2)) AS "CUMULATIVE_ABSENCES_AVG"

FROM STUDENT_ATTENDANCE_DATA SAD

INNER JOIN ABSENCES_COUNTS AC ON AC.ABSENCES_STUDENT_ID = SAD.ABSENCES_STUDENT_ID

WHERE SAD.ABSENCES_FORM_RUN LIKE '[[Form=query_list(SELECT FORM_RUN FROM FORM_RUN WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') ||  ' Year %%')]]'

ORDER BY SAD.ABSENCES_FORM_RUN, AC.FORTNIGHT_ABSENCES DESC, SAD.ABSENCES_HOMEROOM, SAD.ABSENCES_SURNAME