WITH REPORT_VARS AS (
  SELECT
    TO_CHAR((CURRENT DATE), 'YYYY') AS "CURRENT_YEAR",
    (SELECT START_DATE FROM TERM WHERE TERM = 'Term 1' AND START_DATE LIKE (TO_CHAR((CURRENT DATE), 'YYYY')) || '-%%-%%' FETCH FIRST 1 ROW ONLY) AS "YEAR_START",

/*
    ('[[Report From Date=date]]') AS "REPORT_START",
    ('[[Report To Date=date]]') AS "REPORT_END"
*/

    (DATE(CURRENT DATE - 21 DAYS)) AS "REPORT_START",
    (DATE(CURRENT DATE)) AS "REPORT_END"


  FROM SYSIBM.SYSDUMMY1
),

STUDENT_ATTENDANCE_DATA AS (
  SELECT DISTINCT
    REPORT_VARS.REPORT_START,
    REPORT_VARS.REPORT_END,
    REPORT_VARS.YEAR_START,
    (SELECT
      (SUM(CASE WHEN GTRD.TERM_DATE <= (REPORT_VARS.REPORT_END) THEN 1 ELSE 0 END) / 10)
    FROM TABLE(EDUMATE.GET_TIMETABLE_RUNNING_DATES(
      (SELECT TIMETABLE_ID
      FROM TERM WHERE TERM = 'Term 1'
      AND
      START_DATE LIKE (TO_CHAR((CURRENT DATE), 'YYYY')) || '-%%-%%' FETCH FIRST 1 ROW ONLY))) GTRD
    INNER JOIN TERM ON TERM.TERM_ID = GTRD.TERM_ID
    WHERE GTRD.DAY_INDEX NOT IN (888, 999)
    ) AS "DIFF",
    GSFR.STUDENT_ID,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    FORM_RUN.FORM_RUN,
    CLASS.CLASS AS "HOMEROOM",
    DA.DATE_ON,
    ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID AS "ALL_ABSENCES",
    ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID AS "ALL_LATES" 
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) GSFR
  
  INNER JOIN DAILY_ATTENDANCE DA ON DA.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  
  INNER JOIN TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS(CURRENT DATE)) GCES ON GCES.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN VIEW_STUDENT_CLASS_ENROLMENT VSCE ON VSCE.STUDENT_ID = GCES.STUDENT_ID
  INNER JOIN CLASS ON CLASS.CLASS_ID = VSCE.CLASS_ID AND CLASS.CLASS_TYPE_ID = 2 AND VSCE.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY') AND VSCE.END_DATE > (CURRENT_DATE)
  CROSS JOIN REPORT_VARS
  
  -- Absences join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DA.DAILY_ATTENDANCE_STATUS_ID
    AND (DA.DATE_ON BETWEEN REPORT_VARS.YEAR_START AND REPORT_VARS.REPORT_END)
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID IN (2,3,4,5,6,7)
  
  -- Lates join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DA.AM_ATTENDANCE_STATUS_ID
    AND (DA.DATE_ON BETWEEN REPORT_VARS.YEAR_START AND REPORT_VARS.REPORT_END)
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID IN (14,15,16,17,18,19)

  ORDER BY FORM_RUN, SURNAME
),

ABSENCES_LATES_COUNTS AS (
  SELECT
    ROWNUMBER() OVER () AS "ROWNUMBER",
    SAD.STUDENT_ID,
    SUM(CASE WHEN SAD.DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND SAD.ALL_ABSENCES IS NOT NULL THEN 1 ELSE 0 END) AS "FORTNIGHT_ABSENCES",
    SUM(CASE WHEN SAD.ALL_ABSENCES IN (3,5,6) THEN 1 ELSE 0 END) AS "EXPLAINED_ABSENCES",
    SUM(CASE WHEN SAD.ALL_ABSENCES IN (2,4,7) THEN 1 ELSE 0 END) AS "UNEXPLAINED_ABSENCES",
    COUNT(SAD.ALL_ABSENCES) AS "ABSENCES_YTD",
    SUM(CASE WHEN SAD.DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND SAD.ALL_LATES IS NOT NULL THEN 1 ELSE 0 END) AS "FORTNIGHT_LATES",
    SUM(CASE WHEN SAD.ALL_LATES IN (16,17,18,19) THEN 1 ELSE 0 END) AS "EXPLAINED_LATES",
    SUM(CASE WHEN SAD.ALL_LATES IN (14,15) THEN 1 ELSE 0 END) AS "UNEXPLAINED_LATES",
    COUNT(SAD.ALL_LATES) AS "LATES_YTD",
    SUM(CASE WHEN SAD.DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND (SAD.ALL_ABSENCES IS NOT NULL OR SAD.ALL_LATES IS NOT NULL) THEN 1 ELSE 0 END) AS "TOTAL_FORTNIGHT"
  
  FROM STUDENT_ATTENDANCE_DATA SAD
  
  GROUP BY SAD.STUDENT_ID, SAD.FORM_RUN
  
  ORDER BY SAD.FORM_RUN
)

SELECT DISTINCT
  SAD.FIRSTNAME,
  SAD.SURNAME,
  SAD.FORM_RUN,
  SAD.HOMEROOM,
  ALC.FORTNIGHT_ABSENCES,
  ALC.FORTNIGHT_LATES,
  ALC.TOTAL_FORTNIGHT,
  ALC.EXPLAINED_ABSENCES,
  ALC.UNEXPLAINED_ABSENCES,
  ALC.ABSENCES_YTD,
  CAST((CAST(ALC.ABSENCES_YTD AS DECIMAL(3,1)) / CAST(SAD.DIFF AS DECIMAL(3,1))) AS DECIMAL(3,2)) AS "CUMULATIVE_ABSENCES_AVG",
  ALC.EXPLAINED_LATES,
  ALC.UNEXPLAINED_LATES,
  ALC.LATES_YTD,
  CAST((CAST(ALC.LATES_YTD AS DECIMAL(3,1)) / CAST(SAD.DIFF AS DECIMAL(3,1))) AS DECIMAL(3,2)) AS "CUMULATIVE_LATES_AVG"

FROM STUDENT_ATTENDANCE_DATA SAD

INNER JOIN ABSENCES_LATES_COUNTS ALC ON ALC.STUDENT_ID = SAD.STUDENT_ID

--WHERE SAD.FORM_RUN LIKE '[[Form=query_list(SELECT FORM_RUN FROM FORM_RUN WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') ||  ' Year %%')]]'

ORDER BY SAD.FORM_RUN, ALC.ABSENCES_YTD DESC, SAD.HOMEROOM, SAD.SURNAME