WITH REPORT_VARS AS (
  SELECT
    TO_CHAR((CURRENT DATE), 'YYYY') AS "CURRENT_YEAR",
    (DATE((CURRENT DATE) - 14 DAYS)) AS "REPORT_START",
    (DATE(CURRENT DATE)) AS "REPORT_END",
    (SELECT START_DATE FROM TERM WHERE TERM = 'Term 1' AND START_DATE LIKE (TO_CHAR((CURRENT DATE), 'YYYY')) || '-%%-%%' FETCH FIRST 1 ROW ONLY) AS "YEAR_START"

  FROM SYSIBM.SYSDUMMY1
),

STUDENT_ATTENDANCE_DATA AS (
  SELECT DISTINCT
    REPORT_VARS.REPORT_START,
    REPORT_VARS.REPORT_END,
    REPORT_VARS.YEAR_START,
    (SELECT
      (SUM(CASE WHEN GTRD.TERM_DATE <= (CURRENT DATE) THEN 1 ELSE 0 END) / 10)
    FROM TABLE(EDUMATE.GET_TIMETABLE_RUNNING_DATES(
      (SELECT TIMETABLE_ID
      FROM TERM WHERE TERM = 'Term 1'
      AND
      START_DATE LIKE (TO_CHAR((CURRENT DATE), 'YYYY')) || '-%%-%%' FETCH FIRST 1 ROW ONLY))) GTRD
    INNER JOIN TERM ON TERM.TERM_ID = GTRD.TERM_ID
    WHERE GTRD.DAY_INDEX NOT IN (888, 999)
    ) AS "DIFF",
    GSFR.STUDENT_ID,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    FORM_RUN.FORM_RUN,
    DA.DATE_ON,
    ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID AS "ALL_ABSENCES",
    ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID AS "ALL_LATES" 
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) GSFR
  
  INNER JOIN DAILY_ATTENDANCE DA ON DA.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN REPORT_VARS
  
  -- Absences join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DA.DAILY_ATTENDANCE_STATUS_ID
    AND (DA.DATE_ON BETWEEN REPORT_VARS.YEAR_START AND REPORT_VARS.REPORT_END)
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID IN (2,3,4,5,6,7)
  
  -- Lates join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DA.AM_ATTENDANCE_STATUS_ID
    AND (DA.DATE_ON BETWEEN REPORT_VARS.YEAR_START AND REPORT_VARS.REPORT_END)
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID IN (14,15,16,17,18,19)

  ORDER BY FORM_RUN, SURNAME
),

ABSENCES_LATES_COUNTS AS (
  SELECT
    ROWNUMBER() OVER () AS "ROWNUMBER",
    SAD.STUDENT_ID,
    SUM(CASE WHEN SAD.DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND SAD.ALL_ABSENCES IS NOT NULL THEN 1 ELSE 0 END) AS "FORTNIGHT_ABSENCES",
    SUM(CASE WHEN SAD.ALL_ABSENCES IN (3,5,6) THEN 1 ELSE 0 END) AS "EXPLAINED_ABSENCES",
    SUM(CASE WHEN SAD.ALL_ABSENCES IN (2,4,7) THEN 1 ELSE 0 END) AS "UNEXPLAINED_ABSENCES",
    SUM(CASE WHEN SAD.DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND SAD.ALL_LATES IS NOT NULL THEN 1 ELSE 0 END) AS "FORTNIGHT_LATES",
    COUNT(SAD.ALL_ABSENCES) AS "ABSENCES_YTD",
    COUNT(SAD.ALL_LATES) AS "LATES_YTD"
  
  FROM STUDENT_ATTENDANCE_DATA SAD
  
  GROUP BY SAD.STUDENT_ID, SAD.FORM_RUN
  
  ORDER BY SAD.FORM_RUN
)

SELECT DISTINCT
  SAD.FIRSTNAME,
  SAD.SURNAME,
  SAD.FORM_RUN,
  ALC.FORTNIGHT_ABSENCES,
  ALC.EXPLAINED_ABSENCES,
  ALC.UNEXPLAINED_ABSENCES,
  ALC.FORTNIGHT_LATES,
  ALC.ABSENCES_YTD,
  ALC.LATES_YTD,
  CAST((CAST(ALC.ABSENCES_YTD AS DECIMAL(3,1)) / CAST(SAD.DIFF AS DECIMAL(3,1))) AS DECIMAL(3,2)) AS "CUMULATIVE_ABSENCES_AVG"

FROM STUDENT_ATTENDANCE_DATA SAD

INNER JOIN ABSENCES_LATES_COUNTS ALC ON ALC.STUDENT_ID = SAD.STUDENT_ID

ORDER BY SAD.FORM_RUN, SAD.SURNAME