WITH REPORT_VARS AS (
  SELECT
    TO_CHAR((CURRENT DATE), 'YYYY') AS "CURRENT_YEAR",
    (SELECT START_DATE FROM TERM WHERE TERM = 'Term 1' AND START_DATE LIKE (TO_CHAR((CURRENT DATE), 'YYYY')) || '-%%-%%' FETCH FIRST 1 ROW ONLY) AS "YEAR_START",
    ('[[Report From Date=date]]') AS "REPORT_START",
    ('[[Report To Date=date]]') AS "REPORT_END"

    --DATE((CURRENT DATE - 14 DAYS)) AS "REPORT_START",
    --DATE(CURRENT DATE) AS "REPORT_END"

  FROM SYSIBM.SYSDUMMY1
),

STUDENT_ATTENDANCE_DATA AS (
  SELECT DISTINCT
    REPORT_VARS.REPORT_START,
    REPORT_VARS.REPORT_END,
    REPORT_VARS.YEAR_START,
    (SELECT
      (SUM(CASE WHEN GTRD.TERM_DATE <= (REPORT_VARS.REPORT_END) THEN 1 ELSE 0 END) / 10)
    FROM TABLE(EDUMATE.GET_TIMETABLE_RUNNING_DATES(
      (SELECT TIMETABLE_ID
      FROM TERM WHERE TERM = 'Term 1'
      AND
      START_DATE LIKE (TO_CHAR((CURRENT DATE), 'YYYY')) || '-%%-%%' FETCH FIRST 1 ROW ONLY))) GTRD
    INNER JOIN TERM ON TERM.TERM_ID = GTRD.TERM_ID
    WHERE GTRD.DAY_INDEX NOT IN (888, 999)
    ) AS "DIFF",
    GSFR.STUDENT_ID AS "LATES_STUDENT_ID",
    CONTACT.FIRSTNAME AS "LATES_FIRSTNAME",
    CONTACT.SURNAME AS "LATES_SURNAME",
    FORM_RUN.FORM_RUN AS "LATES_FORM_RUN",
    CLASS.CLASS AS "LATES_HOMEROOM",
    DA.DATE_ON AS "LATES_DATE_ON",
    ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID AS "ALL_LATES"
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) GSFR
  
  INNER JOIN DAILY_ATTENDANCE DA ON DA.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  
  INNER JOIN TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS(CURRENT DATE)) GCES ON GCES.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN VIEW_STUDENT_CLASS_ENROLMENT VSCE ON VSCE.STUDENT_ID = GCES.STUDENT_ID
  INNER JOIN CLASS ON CLASS.CLASS_ID = VSCE.CLASS_ID AND CLASS.CLASS_TYPE_ID = 2 AND VSCE.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY') AND VSCE.END_DATE > (CURRENT_DATE)
  CROSS JOIN REPORT_VARS
  
  -- Lates join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DA.AM_ATTENDANCE_STATUS_ID
    AND (DA.DATE_ON BETWEEN REPORT_VARS.YEAR_START AND REPORT_VARS.REPORT_END)
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID IN (14,15,16,17,18,19)

  WHERE ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID IS NOT NULL

  ORDER BY FORM_RUN.FORM_RUN, CLASS.CLASS, CONTACT.SURNAME
),

LATES_COUNTS AS (
  SELECT
    SAD.LATES_STUDENT_ID,
    SUM(CASE WHEN SAD.LATES_DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND SAD.ALL_LATES IS NOT NULL THEN 1 ELSE 0 END) AS "FORTNIGHT_LATES",
    SUM(CASE WHEN SAD.LATES_DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND SAD.ALL_LATES IN (16,17,18,19) THEN 1 ELSE 0 END) AS "EXPLAINED_LATES",
    SUM(CASE WHEN SAD.LATES_DATE_ON BETWEEN SAD.REPORT_START AND SAD.REPORT_END AND SAD.ALL_LATES IN (14,15) THEN 1 ELSE 0 END) AS "UNEXPLAINED_LATES",
    COUNT(SAD.ALL_LATES) AS "LATES_YTD",
    SUM(CASE WHEN SAD.ALL_LATES IN (16,17,18,19) THEN 1 ELSE 0 END) AS "EXPLAINED_LATES_YTD",
    SUM(CASE WHEN SAD.ALL_LATES IN (14,15) THEN 1 ELSE 0 END) AS "UNEXPLAINED_LATES_YTD"
  
  FROM STUDENT_ATTENDANCE_DATA SAD
  
  GROUP BY SAD.LATES_STUDENT_ID, SAD.LATES_FORM_RUN
  
  ORDER BY SAD.LATES_FORM_RUN
)

SELECT DISTINCT
  SAD.LATES_FIRSTNAME,
  SAD.LATES_SURNAME,
  SAD.LATES_FORM_RUN,
  SAD.LATES_HOMEROOM,
  LC.FORTNIGHT_LATES,
  LC.EXPLAINED_LATES,
  LC.UNEXPLAINED_LATES,
  LC.LATES_YTD,
  LC.EXPLAINED_LATES_YTD,
  LC.UNEXPLAINED_LATES_YTD,
  CAST((CAST(LC.LATES_YTD AS DECIMAL(3,1)) / CAST(SAD.DIFF AS DECIMAL(3,1))) AS DECIMAL(3,2)) AS "CUMULATIVE_LATES_AVG"

FROM STUDENT_ATTENDANCE_DATA SAD

INNER JOIN LATES_COUNTS LC ON LC.LATES_STUDENT_ID = SAD.LATES_STUDENT_ID

WHERE SAD.LATES_FORM_RUN LIKE '[[Form=query_list(SELECT FORM_RUN FROM FORM_RUN WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') ||  ' Year %%')]]'

ORDER BY SAD.LATES_FORM_RUN, LC.FORTNIGHT_LATES DESC, SAD.LATES_HOMEROOM, SAD.LATES_SURNAME