CREATE OR REPLACE FUNCTION DB2INST1.DATE_RANGE (LOW_DATE DATE, HIGH_DATE DATE)

RETURNS TABLE
(
    DATE_RANGE DATE
)

LANGUAGE SQL
BEGIN ATOMIC
RETURN
  WITH DATE_RANGE(DAY1) AS
  (
    SELECT (LOW_DATE)
    FROM SYSIBM.SYSDUMMY1
        UNION ALL
    SELECT DAY1+1 DAY
    FROM DATE_RANGE
  
    WHERE
      DAY1 < (HIGH_DATE)
  )
  
  SELECT DAY1 AS "DATE_RANGE"
  FROM DATE_RANGE
  WHERE DAYOFWEEK(DAY1) BETWEEN 2 AND 6;
END