-- Alumni Information Audit

-- Lists all students with the status of 'Alumni' or 'Past Enrolment'.
-- The results of this report are used to audit the accuracy of contact information for ex-students.

SELECT
  CONTACT.CONTACT_ID,
  gass.STUDENT_NUMBER,
  SALUTATION.SALUTATION,
  CONTACT.FIRSTNAME,
  CONTACT.SURNAME,
  CONTACT.OTHER_NAME,
  CONTACT.PREFERRED_NAME,
  CONTACT.MAIDEN_NAME,
  GENDER.GENDER,
  CONTACT.BIRTHDATE,
  VCHA.ADDRESS1 || VCHA.ADDRESS2 AS "ADDRESS1",
  VCHA.SUBURB AS "ADDRESS2",
  VCHA.STATE_CODE AS "STATE",
  VCHA.POST_CODE AS "POSTCODE",
  VCHA.PHONE AS "HOME_PHONE",
  CONTACT.MOBILE_PHONE,
  CONTACT.EMAIL_ADDRESS,
  RELIGION.RELIGION,
  LANGUAGE.LANGUAGE,
  CONTACT.DECEASED_FLAG,
  CONTACT.DECEASED_DATE,
  CLASS_OF,
  START_DATE,
  END_DATE,
  FORM_RUN_INFO,
  house.house
  
FROM TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT DATE)) GASS

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = GASS.CONTACT_ID
INNER JOIN student ON student.student_id = gass.student_id
LEFT JOIN SALUTATION ON SALUTATION.SALUTATION_ID = CONTACT.SALUTATION_ID
LEFT JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID
LEFT JOIN RELIGION ON RELIGION.RELIGION_ID = CONTACT.RELIGION_ID
LEFT JOIN CHURCH ON CHURCH.CHURCH_ID = CONTACT.CHURCH_ID
LEFT JOIN LANGUAGE ON LANGUAGE.LANGUAGE_ID = CONTACT.LANGUAGE_ID
LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID = GASS.CONTACT_ID
LEFT JOIN house ON house.house_id = student.house_id

WHERE
  STUDENT_STATUS_ID IN (2,3)
  AND
  CLASS_OF = '[[Class of=query_list(SELECT DISTINCT CLASS_OF FROM TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT DATE)) WHERE STUDENT_STATUS_ID IN (2,3))]]'

ORDER BY CLASS_OF, SURNAME