WITH DATA_BLOB AS (
  SELECT 
  	CARERS.CONTACT_ID,
  	CARERS.SURNAME,
  	CARERS.FIRSTNAME, 
  	CARERS.PREFERRED_NAME,
  	CARERS.OTHER_NAME,
  	CARERS.MAIDEN_NAME,
    CARERS.DECEASED_FLAG,
    ALUMNI.FORM_RUN_INFO,
    KIDS.FIRSTNAME AS "CHILD_FIRSTNAME",
    KIDS.SURNAME AS "CHILD_SURNAME",
    SS.STUDENT_STATUS
  
  FROM STUDENT
  
  LEFT JOIN TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT DATE)) GASS ON GASS.STUDENT_ID = STUDENT.STUDENT_ID
  INNER JOIN RELATIONSHIP ON RELATIONSHIP.CONTACT_ID2 = STUDENT.CONTACT_ID
  INNER JOIN CARER ON CARER.CONTACT_ID = RELATIONSHIP.CONTACT_ID1
  LEFT JOIN CONTACT CARERS ON CARERS.CONTACT_ID = CARER.CONTACT_ID
  INNER JOIN STUDENT_STATUS SS ON SS.STUDENT_STATUS_ID = GASS.STUDENT_STATUS_ID
  LEFT JOIN TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT DATE)) ALUMNI ON ALUMNI.CONTACT_ID = CARERS.CONTACT_ID AND ALUMNI.STUDENT_STATUS_ID IN (2,3)
  INNER JOIN CONTACT KIDS ON KIDS.CONTACT_ID = STUDENT.CONTACT_ID
  
  WHERE
    GASS.STUDENT_STATUS_ID IN (5,6,9)
    AND
    CARERS.DECEASED_FLAG IS NULL
    AND
    ALUMNI.FORM_RUN_INFO IS NOT NULL
    
  UNION ALL
  
  SELECT 
  	CARERS.CONTACT_ID,
  	CARERS.SURNAME,
  	CARERS.FIRSTNAME, 
  	CARERS.PREFERRED_NAME,
  	CARERS.OTHER_NAME,
  	CARERS.MAIDEN_NAME,
    CARERS.DECEASED_FLAG,
    ALUMNI.FORM_RUN_INFO,
    KIDS.FIRSTNAME AS "CHILD_FIRSTNAME",
    KIDS.SURNAME AS "CHILD_SURNAME",
    SS.STUDENT_STATUS
  
  FROM STUDENT
  
  LEFT JOIN TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT DATE)) GASS ON GASS.STUDENT_ID = STUDENT.STUDENT_ID
  INNER JOIN RELATIONSHIP ON RELATIONSHIP.CONTACT_ID1 = STUDENT.CONTACT_ID
  INNER JOIN CARER ON CARER.CONTACT_ID = RELATIONSHIP.CONTACT_ID2
  LEFT JOIN CONTACT CARERS ON CARERS.CONTACT_ID = CARER.CONTACT_ID
  INNER JOIN STUDENT_STATUS SS ON SS.STUDENT_STATUS_ID = GASS.STUDENT_STATUS_ID
  LEFT JOIN TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT DATE)) ALUMNI ON ALUMNI.CONTACT_ID = CARERS.CONTACT_ID AND ALUMNI.STUDENT_STATUS_ID IN (2,3)
  INNER JOIN CONTACT KIDS ON KIDS.CONTACT_ID = STUDENT.CONTACT_ID
  
  WHERE
    GASS.STUDENT_STATUS_ID IN (5,6,9)
    AND
    CARERS.DECEASED_FLAG IS NULL
    AND
    ALUMNI.FORM_RUN_INFO IS NOT NULL
)

SELECT
  DATA_BLOB.FIRSTNAME,
  DATA_BLOB.SURNAME,
  DATA_BLOB.PREFERRED_NAME,
  DATA_BLOB.OTHER_NAME,
  DATA_BLOB.MAIDEN_NAME,
  DATA_BLOB.DECEASED_FLAG,
  DATA_BLOB.FORM_RUN_INFO,
  DATA_BLOB.CHILD_FIRSTNAME,
  DATA_BLOB.CHILD_SURNAME,
  DATA_BLOB.STUDENT_STATUS

FROM DATA_BLOB

ORDER BY DATA_BLOB.FORM_RUN_INFO, DATA_BLOB.SURNAME, DATA_BLOB.STUDENT_STATUS