WITH BASE_DATA AS (
  SELECT
    CARER.CARER_NUMBER AS "LOOKUP_CODE",
    CONTACT.CONTACT_ID,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    ALUMNI.FORM_RUN_INFO,
    (CASE WHEN VCPA.ADDRESS_ID IS NULL THEN
      (VCDA.ADDRESS1 || (CASE WHEN VCDA.ADDRESS1 = '' THEN '' ELSE '/' END) || VCDA.ADDRESS2) ELSE
      (VCPA.ADDRESS1 || ' ' || VCPA.ADDRESS2) END
    ) AS "CARER_ADDRESS1",
    (CASE WHEN VCPA.ADDRESS_ID IS NULL THEN
      VCDA.ADDRESS3 ELSE
      VCPA.ADDRESS3 END
    ) AS "CARER_ADDRESS2",
    (CASE WHEN VCPA.ADDRESS_ID IS NULL THEN
      VCDA.COUNTRY ELSE
      VCPA.COUNTRY END
    ) AS "CARER_COUNTRY",
    (CASE WHEN VCPA.ADDRESS_ID IS NULL THEN
      (CASE WHEN VCDA.PHONE = '' THEN NULL ELSE VCDA.PHONE END) ELSE
      (CASE WHEN VCPA.PHONE = '' THEN NULL ELSE VCPA.PHONE END) END
    ) AS "CARER_PHONE",
    CONTACT.EMAIL_ADDRESS,
    CONTACT.MOBILE_PHONE
  
  FROM TABLE(EDUMATE.GETCURRCARERCONTACTINFO(CURRENT DATE, null)) CARERS
  
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = CARERS.CONTACT_ID
  LEFT JOIN TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT DATE)) ALUMNI ON ALUMNI.CONTACT_ID = CARERS.CONTACT_ID AND ALUMNI.STUDENT_STATUS_ID IN (2,3)
  INNER JOIN CARER ON CARER.CONTACT_ID = CARERS.CONTACT_ID
  
  LEFT JOIN VIEW_CONTACT_POSTAL_ADDRESS VCPA ON VCPA.CONTACT_ID = CARERS.CONTACT_ID
  LEFT JOIN VIEW_CONTACT_DEFAULT_ADDRESS VCDA ON VCDA.CONTACT_ID = CARERS.CONTACT_ID
  
  WHERE
    CARERS.DECEASED_FLAG IS NULL
    AND
    ALUMNI.FORM_RUN_INFO IS NOT NULL

ORDER BY ALUMNI.FORM_RUN_INFO, CONTACT.SURNAME
),

ALL_EMAILS AS (
  SELECT LISTAGG(EMAIL_ADDRESS, ', ') AS "ALL_EMAILS" FROM BASE_DATA
)

SELECT
  (CASE WHEN ROWNUM = 1 THEN ALL_EMAILS.ALL_EMAILS ELSE NULL END) AS "ALL_EMAILS",
  BASE_DATA.LOOKUP_CODE,
  BASE_DATA.CONTACT_ID,
  BASE_DATA.FIRSTNAME,
  BASE_DATA.SURNAME,
  BASE_DATA.FORM_RUN_INFO,
  BASE_DATA.CARER_ADDRESS1,
  BASE_DATA.CARER_ADDRESS2,
  BASE_DATA.CARER_COUNTRY,
  BASE_DATA.CARER_PHONE,
  BASE_DATA.EMAIL_ADDRESS,
  BASE_DATA.MOBILE_PHONE

FROM BASE_DATA

CROSS JOIN ALL_EMAILS

ORDER BY BASE_DATA.FORM_RUN_INFO, BASE_DATA.SURNAME