SELECT
  STUDENT_NUMBER,
  SALUTATION.SALUTATION,
  CONTACT.FIRSTNAME,
  CONTACT.SURNAME,
  CONTACT.OTHER_NAME,
  CONTACT.PREFERRED_NAME,
  CONTACT.PRONOUNCED_NAME,
  CONTACT.MAIDEN_NAME,
  GENDER.GENDER,
  CONTACT.BIRTHDATE,
  VCHA.ADDRESS1 || VCHA.ADDRESS2 AS "ADDRESS1",
  VCHA.SUBURB AS "ADDRESS2",
  VCHA.STATE_CODE AS "STATE",
  VCHA.POST_CODE AS "POSTCODE",
  VCHA.PHONE AS "HOME_PHONE",
  CONTACT.MOBILE_PHONE,
  CONTACT.EMAIL_ADDRESS,
  RELIGION.RELIGION,
  CHURCH.CHURCH,
  LANGUAGE.LANGUAGE,
  CONTACT.DECEASED_FLAG,
  CONTACT.DECEASED_DATE,
  CASE WHEN CONTACT.DO_NOT_SMS_FLAG = 0 THEN NULL ELSE CONTACT.DO_NOT_SMS_FLAG END AS "DO_NOT_SMS",
  CLASS_OF,
  START_DATE,
  END_DATE,
  FORM_RUN_INFO
  
FROM TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT DATE)) GASS

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = GASS.CONTACT_ID
INNER JOIN SALUTATION ON SALUTATION.SALUTATION_ID = CONTACT.SALUTATION_ID
INNER JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID
INNER JOIN RELIGION ON RELIGION.RELIGION_ID = CONTACT.RELIGION_ID
INNER JOIN CHURCH ON CHURCH.CHURCH_ID = CONTACT.CHURCH_ID
INNER JOIN LANGUAGE ON LANGUAGE.LANGUAGE_ID = CONTACT.LANGUAGE_ID
LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID = GASS.CONTACT_ID

WHERE STUDENT_STATUS_ID IN (2,3)

ORDER BY CLASS_OF, SURNAME