SELECT
	STAFF_NUMBER,
	UPPER(CONTACT.SURNAME) as "SURNAME",
	CONTACT.FIRSTNAME,
	EMPLOYMENT_TYPE.EMPLOYMENT_TYPE,
	WORK_TYPE.WORK_TYPE AS "OCCUPATION",
	WORK_DETAIL.TITLE AS "WORK_TITLE",
	SE.START_DATE,
	SE.END_DATE

FROM STAFF

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN STAFF_EMPLOYMENT SE ON STAFF.STAFF_ID = SE.STAFF_ID
INNER JOIN EMPLOYMENT_TYPE ON EMPLOYMENT_TYPE.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID
INNER JOIN WORK_DETAIL ON WORK_DETAIL.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN WORK_TYPE ON WORK_TYPE.WORK_TYPE_ID = WORK_DETAIL.WORK_TYPE_ID

WHERE
	SURNAME NOT LIKE 'Coach'
		AND
	SE.EMPLOYMENT_TYPE_ID = 1
		AND
	STAFF.STAFF_ID != '1'
		AND
	SE.START_DATE <= current_date
		AND
	SE.END_DATE IS NULL
		OR
	SE.END_DATE > current_date
		AND
	SE.EMPLOYMENT_TYPE_ID NOT IN (2,3,4)	

ORDER BY CONTACT.SURNAME