SELECT
	STAFF_NUMBER,
	CONTACT.SURNAME,
	CONTACT.FIRSTNAME,
	EMPLOYMENT_TYPE.EMPLOYMENT_TYPE,
	SE.START_DATE,
	SE.END_DATE

FROM STAFF

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN STAFF_EMPLOYMENT SE ON STAFF.STAFF_ID = SE.STAFF_ID
INNER JOIN EMPLOYMENT_TYPE ON EMPLOYMENT_TYPE.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID

WHERE
	CONTACT.SURNAME NOT LIKE 'Coach'
		AND
	SE.EMPLOYMENT_TYPE_ID = 1
		AND
	STAFF.STAFF_ID != '1'
		AND
	SE.START_DATE <= current_date
		AND
	SE.END_DATE IS NULL
		OR
	SE.END_DATE > current_date
		AND
	SE.EMPLOYMENT_TYPE_ID NOT IN (2,3,4)	

ORDER BY CONTACT.SURNAME