SELECT
  STAFF_NUMBER AS "DISTRICT_NO",
  CONTACT.SURNAME AS "LAST_NAME",
  CONTACT.FIRSTNAME AS "FIRST_NAME",
  CONTACT.PREFERRED_NAME AS "NICKNAME",
  CONTACT.BIRTHDATE,
  GENDER.GENDER,
  NULL AS "HOMEROOM",
  'B' || STAFF.STAFF_NUMBER || '1844' AS "BARCODE",
  CONTACT.EMAIL_ADDRESS AS "EMAIL_1",
  VCHA.ADDRESS1 || VCHA.ADDRESS2 AS "ADDRESS1",
  VCHA.SUBURB AS "ADDRESS2",
  NULL AS "ADDRESS3",
  VCHA.STATE_CODE AS "STATE",
  VCHA.POST_CODE AS "POSTCODE",
  '(' || PHONE.AREA_CODE || ')' || ' ' || PHONE.PHONE AS "HOME_PHONE",
  CONTACT.MOBILE_PHONE AS "MAIN_MOBILE",
  STAFF.STAFF_NUMBER || '.jpg' AS "IMAGE_FILE_NAME",
  NULL AS "GRAD_YEAR",
  -- USERNAME
  -- PATRON TYPE
  -- GRADE LEVEL
  -- STATUS

FROM STAFF

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID
LEFT JOIN CONTACT_ADDRESS ON CONTACT_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
LEFT JOIN ADDRESS ON ADDRESS.ADDRESS_ID = CONTACT_ADDRESS.ADDRESS_ID
LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID = STAFF.CONTACT_ID
LEFT JOIN PHONE ON PHONE.PHONE_ID = ADDRESS.PHONE_NUMBER

ORDER BY SURNAME