WITH GRAD_YEAR AS
(
  SELECT
    STUDENT_ID,
    MAX(ACADEMIC_YEAR) AS "GRAD_YEAR"

  FROM VIEW_STUDENT_FORM_RUN
  
  GROUP BY STUDENT_ID
)

SELECT
  STUDENT.STUDENT_NUMBER AS "DISTRICT_NO",
  CONTACT.SURNAME AS "LAST_NAME",
  CONTACT.FIRSTNAME AS "FIRST_NAME",
  CONTACT.PREFERRED_NAME AS "NICKNAME",
  TO_CHAR(CONTACT.BIRTHDATE, 'DD/MM/YY') AS "BIRTHDATE",
  GENDER.GENDER,
  CLASS.CLASS AS "HOMEROOM",
  'B' || STUDENT.STUDENT_NUMBER || '1844' AS "BARCODE",
  CONTACT.EMAIL_ADDRESS AS "EMAIL_1",
  VCHA.ADDRESS1 || VCHA.ADDRESS2 AS "ADDRESS1",
  VCHA.SUBURB AS "ADDRESS2",
  NULL AS "ADDRESS3",
  VCHA.STATE_CODE AS "STATE",
  VCHA.POST_CODE AS "POSTCODE",
  VCHA.PHONE AS "HOME_PHONE",
  CONTACT.MOBILE_PHONE AS "MAIN_MOBILE",
  STUDENT.STUDENT_NUMBER || '.jpg' AS "IMAGE_FILE_NAME",
  GRAD_YEAR.GRAD_YEAR,
  SYS_USER.USERNAME AS "USER_NAME",
  CONTACT_TYPE.CONTACT_TYPE AS "PATRON_TYPE",
  CASE SUBSTR((VSFR.FORM_RUN),6,7)
    WHEN 'Year 07' THEN 'Year 7'
    WHEN 'Year 08' THEN 'Year 8'
    WHEN 'Year 09' THEN 'Year 9'
    WHEN 'Year 10' THEN 'Year 10'
    WHEN 'Year 11' THEN 'Year 11'
    WHEN 'Year 12' THEN 'Year 12'
    ELSE NULL
  END AS "GRADE_LEVEL",
  'Active' AS "STATUS"

FROM TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS(CURRENT DATE)) GCES

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GCES.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
LEFT JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID

INNER JOIN VIEW_STUDENT_CLASS_ENROLMENT VSCE ON VSCE.STUDENT_ID = GCES.STUDENT_ID
INNER JOIN CLASS ON CLASS.CLASS_ID = VSCE.CLASS_ID AND CLASS.CLASS_TYPE_ID = 2 AND VSCE.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY')

LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID = STUDENT.CONTACT_ID

INNER JOIN GRAD_YEAR ON GRAD_YEAR.STUDENT_ID = GCES.STUDENT_ID
INNER JOIN VIEW_STUDENT_FORM_RUN VSFR ON VSFR.STUDENT_ID = GCES.STUDENT_ID AND VSFR.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY')

LEFT JOIN SYS_USER ON SYS_USER.CONTACT_ID = STUDENT.CONTACT_ID
LEFT JOIN CONT_MEMBERSHIP ON CONT_MEMBERSHIP.CONTACT_ID = STUDENT.CONTACT_ID
INNER JOIN CONTACT_TYPE ON CONTACT_TYPE.CONTACT_TYPE_ID = CONT_MEMBERSHIP.CONTACT_TYPE_ID AND CONTACT_TYPE.CONTACT_TYPE_ID = 3