-- Destiny Export

-- Exports relevant data to a CSV with fields named to match Destiny's requirements.

WITH STAFF_LIST AS
(
  SELECT
    STAFF_NUMBER AS "DISTRICT_NO",
    CONTACT.SURNAME AS "LAST_NAME",
    CONTACT.FIRSTNAME AS "FIRST_NAME",
    CONTACT.PREFERRED_NAME AS "NICKNAME",
    null AS "BIRTHDATE",
    GENDER.GENDER,
    HOUSE.HOUSE AS "HOMEROOM",
    HOUSE.HOUSE AS "HOUSE",
    'B' || STAFF.STAFF_NUMBER || '1844' AS "BARCODE",
    CONTACT.EMAIL_ADDRESS AS "EMAIL_1",
    null AS "ADDRESS1",
    null AS "ADDRESS2",
    null AS "ADDRESS3",
    null AS "STATE",
    null AS "POSTCODE",
    null AS "HOME_PHONE",
    null AS "MAIN_MOBILE",
    STAFF.STAFF_NUMBER || '.jpg' AS "IMAGE_FILE_NAME",
    null AS "GRAD_YEAR",
    SYS_USER.USERNAME AS "USER_NAME",
    'Staff' AS "PATRON_TYPE",
    null AS "GRADE_LEVEL",
    'Active' AS "STATUS"
  
  FROM STAFF
  
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID AND CONTACT.DECEASED_DATE IS NULL
  INNER JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID
  LEFT JOIN CONTACT_ADDRESS ON CONTACT_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN ADDRESS ON ADDRESS.ADDRESS_ID = CONTACT_ADDRESS.ADDRESS_ID
  LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN PHONE ON PHONE.PHONE_ID = ADDRESS.PHONE_NUMBER
  LEFT JOIN SYS_USER ON SYS_USER.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN CONT_MEMBERSHIP ON CONT_MEMBERSHIP.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN CONTACT_TYPE ON CONTACT_TYPE.CONTACT_TYPE_ID = CONT_MEMBERSHIP.CONTACT_TYPE_ID AND CONTACT_TYPE.CONTACT_TYPE_ID = 4
  LEFT JOIN STAFF_EMPLOYMENT SE ON STAFF.STAFF_ID = SE.STAFF_ID
  LEFT JOIN EMPLOYMENT_TYPE ON EMPLOYMENT_TYPE.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID
  INNER JOIN GROUP_MEMBERSHIP ON GROUP_MEMBERSHIP.CONTACT_ID = STAFF.CONTACT_ID
  INNER JOIN GROUPS ON GROUPS.GROUPS_ID = GROUP_MEMBERSHIP.GROUPS_ID
  -- Houses
  LEFT JOIN house ON house.house_id = staff.house_id
  
  WHERE
    GROUPS.GROUPS_ID IN (386, 530)
      AND
    GROUP_MEMBERSHIP.effective_start <= (current date)
      AND
    (GROUP_MEMBERSHIP.effective_end IS NULL
      OR
    GROUP_MEMBERSHIP.effective_end > (current date))
      AND  
    CONTACT.SURNAME NOT LIKE 'Coach'
      AND
    STAFF.STAFF_ID != '1'
),

GRAD_YEAR AS
(
  SELECT
    STUDENT_ID,
    MAX(ACADEMIC_YEAR) AS "GRAD_YEAR"

  FROM VIEW_STUDENT_FORM_RUN

  GROUP BY STUDENT_ID
),

STUDENTS_LIST AS
(
  SELECT
    STUDENT.STUDENT_NUMBER AS "DISTRICT_NO",
    CONTACT.SURNAME AS "LAST_NAME",
    CONTACT.FIRSTNAME AS "FIRST_NAME",
    CONTACT.PREFERRED_NAME AS "NICKNAME",
    null AS "BIRTHDATE",
    GENDER.GENDER,
    VSCE.CLASS AS "HOMEROOM",
    HOUSE.HOUSE AS "HOUSE",
    'B' || STUDENT.STUDENT_NUMBER || '1844' AS "BARCODE",
    CONTACT.EMAIL_ADDRESS AS "EMAIL_1",
    null AS "ADDRESS1",
    null AS "ADDRESS2",
    null AS "ADDRESS3",
    null AS "STATE",
    null AS "POSTCODE",
    null AS "HOME_PHONE",
    null AS "MAIN_MOBILE",
    STUDENT.STUDENT_NUMBER || '.jpg' AS "IMAGE_FILE_NAME",
    GRAD_YEAR.GRAD_YEAR,
    SYS_USER.USERNAME AS "USER_NAME",
    CONTACT_TYPE.CONTACT_TYPE AS "PATRON_TYPE",
    CASE SUBSTR((vsfr.FORM_RUN),6,7)
      WHEN 'Year 07' THEN 'Year 7'
      WHEN 'Year 08' THEN 'Year 8'
      WHEN 'Year 09' THEN 'Year 9'
      WHEN 'Year 10' THEN 'Year 10'
      WHEN 'Year 11' THEN 'Year 11'
      WHEN 'Year 12' THEN 'Year 12'
      ELSE NULL
    END AS "GRADE_LEVEL",
    'Active' AS "STATUS"
  
  FROM TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS('[[For date=date]]')) GCES
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GCES.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID AND CONTACT.DECEASED_DATE IS NULL
  LEFT JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID
  
  LEFT JOIN VIEW_STUDENT_CLASS_ENROLMENT VSCE ON VSCE.STUDENT_ID = GCES.STUDENT_ID AND VSCE.CLASS_TYPE_ID = 2 AND VSCE.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY') AND VSCE.END_DATE > (CURRENT_DATE)
  
  LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID = STUDENT.CONTACT_ID
  
  INNER JOIN GRAD_YEAR ON GRAD_YEAR.STUDENT_ID = GCES.STUDENT_ID
  INNER JOIN VIEW_STUDENT_FORM_RUN VSFR ON VSFR.STUDENT_ID = GCES.STUDENT_ID AND VSFR.ACADEMIC_YEAR = YEAR(current date)

  LEFT JOIN SYS_USER ON SYS_USER.CONTACT_ID = STUDENT.CONTACT_ID
  LEFT JOIN CONT_MEMBERSHIP ON CONT_MEMBERSHIP.CONTACT_ID = STUDENT.CONTACT_ID
  INNER JOIN CONTACT_TYPE ON CONTACT_TYPE.CONTACT_TYPE_ID = CONT_MEMBERSHIP.CONTACT_TYPE_ID AND CONTACT_TYPE.CONTACT_TYPE_ID = 3
  
  LEFT JOIN HOUSE ON HOUSE.HOUSE_ID = STUDENT.HOUSE_ID
)

SELECT DISTINCT * FROM STAFF_LIST
UNION ALL
SELECT DISTINCT * FROM STUDENTS_LIST

ORDER BY LAST_NAME