-- Destiny Export

-- Exports relevant data to a CSV with fields named to match Destiny's requirements.

WITH STAFF_LIST AS
(
  SELECT
    STAFF_NUMBER AS "DISTRICT_NO",
    CONTACT.SURNAME AS "LAST_NAME",
    CONTACT.FIRSTNAME AS "FIRST_NAME",
    CONTACT.PREFERRED_NAME AS "NICKNAME",
    TO_CHAR(CONTACT.BIRTHDATE, 'DD/MM/YY') AS "BIRTHDATE",
    GENDER.GENDER,
    HOUSE.HOUSE AS "HOMEROOM",
    'B' || STAFF.STAFF_NUMBER || '1844' AS "BARCODE",
    CONTACT.EMAIL_ADDRESS AS "EMAIL_1",
    VCHA.ADDRESS1 || VCHA.ADDRESS2 AS "ADDRESS1",
    VCHA.SUBURB AS "ADDRESS2",
    NULL AS "ADDRESS3",
    VCHA.STATE_CODE AS "STATE",
    VCHA.POST_CODE AS "POSTCODE",
    VCHA.PHONE AS "HOME_PHONE",
    CONTACT.MOBILE_PHONE AS "MAIN_MOBILE",
    STAFF.STAFF_NUMBER || '.jpg' AS "IMAGE_FILE_NAME",
    NULL AS "GRAD_YEAR",
    SYS_USER.USERNAME AS "USER_NAME",
    CONTACT_TYPE.CONTACT_TYPE AS "PATRON_TYPE",
    NULL AS "GRADE_LEVEL",
    'Active' AS "STATUS"
  
  FROM STAFF
  
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID AND CONTACT.DECEASED_DATE IS NULL
  INNER JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID
  LEFT JOIN CONTACT_ADDRESS ON CONTACT_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN ADDRESS ON ADDRESS.ADDRESS_ID = CONTACT_ADDRESS.ADDRESS_ID
  LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID = STAFF.CONTACT_ID
  LEFT JOIN PHONE ON PHONE.PHONE_ID = ADDRESS.PHONE_NUMBER
  LEFT JOIN SYS_USER ON SYS_USER.CONTACT_ID = STAFF.CONTACT_ID
  INNER JOIN CONT_MEMBERSHIP ON CONT_MEMBERSHIP.CONTACT_ID = STAFF.CONTACT_ID
  INNER JOIN CONTACT_TYPE ON CONTACT_TYPE.CONTACT_TYPE_ID = CONT_MEMBERSHIP.CONTACT_TYPE_ID AND CONTACT_TYPE.CONTACT_TYPE_ID = 4
  LEFT JOIN STAFF_EMPLOYMENT SE ON STAFF.STAFF_ID = SE.STAFF_ID
  LEFT JOIN EMPLOYMENT_TYPE ON EMPLOYMENT_TYPE.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID
  INNER JOIN GROUP_MEMBERSHIP ON GROUP_MEMBERSHIP.CONTACT_ID = STAFF.CONTACT_ID
  INNER JOIN GROUPS ON GROUPS.GROUPS_ID = GROUP_MEMBERSHIP.GROUPS_ID
  -- Houses
  left JOIN house ON house.house_id = staff.house_id
  
  WHERE
    GROUPS.GROUPS_ID = 3
      AND
    CONTACT.SURNAME NOT LIKE 'Coach'
      AND
    STAFF.STAFF_ID != '1'
      AND
    SE.START_DATE <= CURRENT DATE
      AND
    SE.END_DATE IS NULL
      OR
    SE.END_DATE > CURRENT DATE
),

GRAD_YEAR AS
(
  SELECT
    STUDENT_ID,
    MAX(ACADEMIC_YEAR) AS "GRAD_YEAR"

  FROM VIEW_STUDENT_FORM_RUN

  GROUP BY STUDENT_ID
),

STUDENTS_LIST AS
(
  SELECT
    STUDENT.STUDENT_NUMBER AS "DISTRICT_NO",
    CONTACT.SURNAME AS "LAST_NAME",
    CONTACT.FIRSTNAME AS "FIRST_NAME",
    CONTACT.PREFERRED_NAME AS "NICKNAME",
    TO_CHAR(CONTACT.BIRTHDATE, 'DD/MM/YY') AS "BIRTHDATE",
    GENDER.GENDER,
    HOUSE.HOUSE AS "HOMEROOM",
    'B' || STUDENT.STUDENT_NUMBER || '1844' AS "BARCODE",
    CONTACT.EMAIL_ADDRESS AS "EMAIL_1",
    VCHA.ADDRESS1 || VCHA.ADDRESS2 AS "ADDRESS1",
    VCHA.SUBURB AS "ADDRESS2",
    NULL AS "ADDRESS3",
    VCHA.STATE_CODE AS "STATE",
    VCHA.POST_CODE AS "POSTCODE",
    VCHA.PHONE AS "HOME_PHONE",
    CONTACT.MOBILE_PHONE AS "MAIN_MOBILE",
    STUDENT.STUDENT_NUMBER || '.jpg' AS "IMAGE_FILE_NAME",
    GRAD_YEAR.GRAD_YEAR,
    SYS_USER.USERNAME AS "USER_NAME",
    CONTACT_TYPE.CONTACT_TYPE AS "PATRON_TYPE",
    CASE SUBSTR((FORM_RUN.FORM_RUN),6,7)
      WHEN 'Year 07' THEN 'Year 7'
      WHEN 'Year 08' THEN 'Year 8'
      WHEN 'Year 09' THEN 'Year 9'
      WHEN 'Year 10' THEN 'Year 10'
      WHEN 'Year 11' THEN 'Year 11'
      WHEN 'Year 12' THEN 'Year 12'
      ELSE NULL
    END AS "GRADE_LEVEL",
    'Active' AS "STATUS"
  
  FROM TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS('[[For date=date]]')) GCES
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GCES.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID AND CONTACT.DECEASED_DATE IS NULL
  LEFT JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID
  
  LEFT JOIN VIEW_STUDENT_CLASS_ENROLMENT VSCE ON VSCE.STUDENT_ID = GCES.STUDENT_ID
  LEFT JOIN CLASS ON CLASS.CLASS_ID = VSCE.CLASS_ID AND CLASS.CLASS_TYPE_ID = 2 AND VSCE.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY') AND VSCE.END_DATE > (CURRENT_DATE)
  
  LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID = STUDENT.CONTACT_ID
  
  INNER JOIN GRAD_YEAR ON GRAD_YEAR.STUDENT_ID = GCES.STUDENT_ID
  --INNER JOIN VIEW_STUDENT_FORM_RUN VSFR ON VSFR.STUDENT_ID = GCES.STUDENT_ID AND VSFR.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY')

  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = (
      SELECT FORM_RUN.FORM_RUN_ID
      FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) GRSFR
      INNER JOIN FORM_RUN ON GRSFR.FORM_RUN_ID = FORM_RUN.FORM_RUN_ID
      WHERE GRSFR.STUDENT_ID = GCES.STUDENT_ID
      FETCH FIRST 1 ROW ONLY
  )

  LEFT JOIN SYS_USER ON SYS_USER.CONTACT_ID = STUDENT.CONTACT_ID
  LEFT JOIN CONT_MEMBERSHIP ON CONT_MEMBERSHIP.CONTACT_ID = STUDENT.CONTACT_ID
  INNER JOIN CONTACT_TYPE ON CONTACT_TYPE.CONTACT_TYPE_ID = CONT_MEMBERSHIP.CONTACT_TYPE_ID AND CONTACT_TYPE.CONTACT_TYPE_ID = 3
  
  LEFT JOIN HOUSE ON HOUSE.HOUSE_ID = STUDENT.HOUSE_ID
)

SELECT DISTINCT * FROM STAFF_LIST
UNION ALL
SELECT DISTINCT * FROM STUDENTS_LIST

ORDER BY LAST_NAME