SELECT
  STAFF_NUMBER AS "DISTRICT_NO",
  CONTACT.SURNAME AS "LAST_NAME",
  CONTACT.FIRSTNAME AS "FIRST_NAME",
  CONTACT.PREFERRED_NAME AS "NICKNAME",
  TO_CHAR(CONTACT.BIRTHDATE, 'DD/MM/YY') AS "BIRTHDATE",
  GENDER.GENDER,
  NULL AS "HOMEROOM",
  'B' || STAFF.STAFF_NUMBER || '1844' AS "BARCODE",
  CONTACT.EMAIL_ADDRESS AS "EMAIL_1",
  VCHA.ADDRESS1 || VCHA.ADDRESS2 AS "ADDRESS1",
  VCHA.SUBURB AS "ADDRESS2",
  NULL AS "ADDRESS3",
  VCHA.STATE_CODE AS "STATE",
  VCHA.POST_CODE AS "POSTCODE",
  '(' || PHONE.AREA_CODE || ')' || ' ' || PHONE.PHONE AS "HOME_PHONE",
  CONTACT.MOBILE_PHONE AS "MAIN_MOBILE",
  STAFF.STAFF_NUMBER || '.jpg' AS "IMAGE_FILE_NAME",
  NULL AS "GRAD_YEAR",
  SYS_USER.USERNAME AS "USER_NAME",
  CONTACT_TYPE.CONTACT_TYPE AS "PATRON_TYPE",
  NULL AS "GRADE_LEVEL",
  'Active' AS "STATUS"

FROM STAFF

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID
LEFT JOIN CONTACT_ADDRESS ON CONTACT_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
LEFT JOIN ADDRESS ON ADDRESS.ADDRESS_ID = CONTACT_ADDRESS.ADDRESS_ID
LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID = STAFF.CONTACT_ID
LEFT JOIN PHONE ON PHONE.PHONE_ID = ADDRESS.PHONE_NUMBER
LEFT JOIN SYS_USER ON SYS_USER.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN CONT_MEMBERSHIP ON CONT_MEMBERSHIP.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN CONTACT_TYPE ON CONTACT_TYPE.CONTACT_TYPE_ID = CONT_MEMBERSHIP.CONTACT_TYPE_ID AND CONTACT_TYPE.CONTACT_TYPE_ID = 4
LEFT JOIN STAFF_EMPLOYMENT SE ON STAFF.STAFF_ID = SE.STAFF_ID
LEFT JOIN EMPLOYMENT_TYPE ON EMPLOYMENT_TYPE.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID
INNER JOIN GROUP_MEMBERSHIP ON GROUP_MEMBERSHIP.CONTACT_ID = STAFF.CONTACT_ID
INNER JOIN GROUPS ON GROUPS.GROUPS_ID = GROUP_MEMBERSHIP.GROUPS_ID

WHERE
  GROUPS.GROUPS_ID = 3
    AND
  CONTACT.SURNAME NOT LIKE 'Coach'
    AND
  SE.EMPLOYMENT_TYPE_ID IN (1,2,4)
    AND
  STAFF.STAFF_ID != '1'
    AND
  SE.START_DATE <= current_date
    AND
  SE.END_DATE IS NULL
    OR
  SE.END_DATE > current_date