SELECT
  CONTACT.FIRSTNAME,
  CONTACT.SURNAME,
  VSFR.FORM_RUN,
  VSMC.SALUTATION,
  VCHA.ADDRESS1 || (CASE WHEN VCHA.ADDRESS1 = '' THEN '' ELSE '/' END) || VCHA.ADDRESS2 AS "ADDRESS1",
  CASE WHEN VCHA.ADDRESS3 = '' THEN COUNTRY ELSE VCHA.ADDRESS3 END AS "ADDRESS2"

FROM TABLE(EDUMATE.GET_CURRENTLY_ENROLED_STUDENTS(CURRENT DATE)) GCES

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GCES.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
INNER JOIN VIEW_STUDENT_FORM_RUN VSFR ON VSFR.STUDENT_ID = GCES.STUDENT_ID AND VSFR.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY')
INNER JOIN VIEW_STUDENT_MAIL_CARERS VSMC ON VSMC.STUDENT_ID = GCES.STUDENT_ID AND VSMC.LIVES_WITH_FLAG = 0

LEFT JOIN VIEW_CONTACT_HOME_ADDRESS VCHA ON VCHA.CONTACT_ID IN (VSMC.CARER1_CONTACT_ID,VSMC.CARER2_CONTACT_ID,VSMC.CARER3_CONTACT_ID,VSMC.CARER4_CONTACT_ID)

WHERE VSFR.FORM_RUN LIKE '[[Form=query_list(SELECT FORM_RUN.FORM_RUN FROM FORM_RUN WHERE FORM_RUN like TO_CHAR(YEAR(CURRENT DATE)) || ' Year %' ORDER BY FORM_RUN)]]'

ORDER BY FORM_RUN, SURNAME