WITH EDITS AS
(
	SELECT
		CONTACT.SURNAME AS "STAFF_SURNAME",
		CONTACT.FIRSTNAME AS "STAFF_FIRSTNAME",
		STUDENT_ID,
		SUMMATION_REPORT_ID,
		SUMMATION_REPORT.LAST_UPDATED
	
	FROM SUMMATION_REPORT
	
	INNER JOIN SYS_USER ON SYS_USER.SYS_USER_ID = SUMMATION_REPORT.LAST_UPDATED_BY_ID
	INNER JOIN CONTACT ON CONTACT.CONTACT_ID = SYS_USER.CONTACT_ID
	
	WHERE SUMMATION_REPORT.LAST_UPDATED LIKE '2013-03%'
)

SELECT
	STAFF_SURNAME,
	STAFF_FIRSTNAME,
	CONTACT.SURNAME AS "STU_SURNAME",
	CONTACT.FIRSTNAME AS "STU_FIRSTNAME",
	EDITS.LAST_UPDATED

FROM EDITS

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = EDITS.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID

ORDER BY STAFF_SURNAME, LAST_UPDATED DESC, SUMMATION_REPORT_ID, STU_SURNAME