SELECT
  CONTACT.FIRSTNAME AS "Firstname",
  CONTACT.SURNAME AS "Surname",
  ET.EMPLOYMENT_TYPE AS "Employment Type",
  SESSION_GENERATOR.START_DATE AS "Logon Date/Time",
  (CASE WHEN SESSION_GENERATOR.IP_ADDRESS LIKE '192.168.%' THEN 'Rosebank Network' ELSE 'Off-site Network' END) AS "Logon Source"
  

FROM SESSION_GENERATOR

INNER JOIN SYS_USER ON SESSION_GENERATOR.USER_ID = SYS_USER.SYS_USER_ID
INNER JOIN CONTACT ON SYS_USER.CONTACT_ID = CONTACT.CONTACT_ID

INNER JOIN STAFF ON STAFF.CONTACT_ID = CONTACT.CONTACT_ID
INNER JOIN STAFF_EMPLOYMENT SE ON SE.STAFF_ID = STAFF.STAFF_ID
INNER JOIN EMPLOYMENT_TYPE ET ON ET.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID

WHERE
  DATE(SESSION_GENERATOR.START_DATE) BETWEEN DATE('[[Report from=date]]') AND DATE('[[Report to=date]]')
  AND
  USERNAME != 'eduscheduler'
  
ORDER BY SESSION_GENERATOR.START_DATE ASC