SELECT
  LOWER(SYS_USER.USERNAME) AS "username",
  null AS "password",
  null AS "firstname",
  null AS "lastname",
  null AS "email",
  VSCE.COURSE AS "course1",
  VSCE.CLASS AS "group1"

FROM VIEW_STUDENT_CLASS_ENROLMENT VSCE

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = VSCE.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
INNER JOIN SYS_USER ON SYS_USER.CONTACT_ID = CONTACT.CONTACT_ID

WHERE
    ACADEMIC_YEAR = 2013
    AND
    (START_DATE < CURRENT DATE
    AND
    END_DATE > CURRENT DATE)
    AND
    VSCE.CLASS_TYPE_ID = 1
    AND
    (
      VSCE.COURSE NOT LIKE 'CS %'
      AND
      VSCE.COURSE NOT LIKE '% CC'
      AND
      VSCE.COURSE NOT LIKE 'SCC %'
      AND
      VSCE.COURSE NOT LIKE '%Hockey%'
      AND
      VSCE.COURSE NOT LIKE '%OzTag%'
      AND
      VSCE.COURSE NOT LIKE '%Pastoral%'
      AND
      VSCE.COURSE NOT LIKE '%CBSA%'
      AND
      VSCE.COURSE NOT LIKE '%Yoga%'
      AND
      VSCE.COURSE NOT LIKE '%Soccer%'
      AND
      VSCE.COURSE NOT LIKE '%Frisbee%'
      AND
      VSCE.COURSE NOT LIKE '%Early Leave%'
      AND
      VSCE.COURSE NOT LIKE '%Frisbee%'
    )

GROUP BY SYS_USER.USERNAME, VSCE.COURSE, VSCE.CLASS

ORDER BY SYS_USER.USERNAME