SELECT
  SUBJECT.SUBJECT,
  OUTLINE.OUTLINE,
  SO.LAST_UPDATED,
  (CASE
    WHEN SUBJECT.SUBJECT LIKE '07%' THEN '2013 S2 Year 07'
    WHEN SUBJECT.SUBJECT LIKE '08%' THEN '2013 S2 Year 08'
    WHEN SUBJECT.SUBJECT LIKE '09%' THEN '2013 S2 Year 10'
    WHEN SUBJECT.SUBJECT LIKE '10%' THEN '2013 S2 Year 10'
    WHEN SUBJECT.SUBJECT LIKE '11%' THEN '2013 S2 Year 11'
    WHEN SUBJECT.SUBJECT LIKE '12%' THEN '2013 S2 Year 11'
    ELSE NULL END
  ) AS "REPORT_PERIOD",
  COURSE.COURSE,
  class.class,
  COURSE.CODE || ' ' || CLASS.IDENTIFIER AS "CLASS_CODE"
  
FROM SUBJECT_OUTLINE SO

LEFT JOIN SUBJECT ON SUBJECT.SUBJECT_ID = SO.SUBJECT_ID
LEFT JOIN OUTLINE ON OUTLINE.OUTLINE_ID = SO.OUTLINE_ID
LEFT JOIN COURSE ON COURSE.SUBJECT_ID = SO.SUBJECT_ID
LEFT JOIN CLASS ON CLASS.COURSE_ID = COURSE.COURSE_ID AND CLASS.ACADEMIC_YEAR_ID = 45

WHERE
  YEAR(SO.LAST_UPDATED) = YEAR(CURRENT DATE)
  AND
  (SUBJECT.SUBJECT NOT IN ('Peer Support', 'EnrichED')
  AND
  SUBJECT.SUBJECT NOT LIKE '07%'
  AND
  SUBJECT.SUBJECT NOT LIKE '08%')

ORDER BY SUBJECT.SUBJECT