/* Status: Qualifications done, next up: emergency contacts - year started teaching */

WITH STAFFBASE AS
(
	SELECT
		STAFF_NUMBER,
		CONTACT.SURNAME,
		CONTACT.FIRSTNAME,
		EMPLOYMENT_TYPE.EMPLOYMENT_TYPE,
		SE.START_DATE,
		SE.END_DATE,
		QUALIFICATION.QUALIFICATION AS "QUALS"

	FROM STAFF

	INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
	INNER JOIN QUALIFICATION ON QUALIFICATION.CONTACT_ID = STAFF.CONTACT_ID
	INNER JOIN STAFF_EMPLOYMENT SE ON STAFF.STAFF_ID = SE.STAFF_ID
	INNER JOIN EMPLOYMENT_TYPE ON EMPLOYMENT_TYPE.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID
),

QUALS AS
(
	SELECT
		STAFF_NUMBER,
		substr( xmlserialize( xmlagg( xmltext( concat( ', ', QUALS ) ) ) as varchar( 1024 ) ), 3 ) AS "QUALIFICATIONS"
	
	FROM STAFFBASE
	GROUP BY STAFF_NUMBER, SURNAME, FIRSTNAME
)

SELECT DISTINCT
	SURNAME,
	FIRSTNAME,
	EMPLOYMENT_TYPE,
	START_DATE,
	END_DATE,
	QUALS.QUALIFICATIONS

FROM STAFFBASE

INNER JOIN QUALS ON QUALS.STAFF_NUMBER = STAFFBASE.STAFF_NUMBER

ORDER BY SURNAME