/* Status: To do: DUPES? */

WITH STAFFBASE AS
(
	SELECT
		STAFF_NUMBER,
		CONTACT.SURNAME,
		CONTACT.FIRSTNAME,
		(CASE
			WHEN VIEW_CONTACT_HOME_ADDRESS.ADDRESS1 = ''
			THEN VIEW_CONTACT_HOME_ADDRESS.ADDRESS2 || '<br>' || VIEW_CONTACT_HOME_ADDRESS.ADDRESS3
			ELSE VIEW_CONTACT_HOME_ADDRESS.ADDRESS1 || '<br>' || VIEW_CONTACT_HOME_ADDRESS.ADDRESS2 || '<br>' || VIEW_CONTACT_HOME_ADDRESS.ADDRESS3
		END) AS "HOME_ADDRESS",
		'(' || PHONE.AREA_CODE || ')' || ' ' || PHONE.PHONE AS "HOME_PHONE",
		CONTACT.MOBILE_PHONE,
		CAR.CAR_MAKE,
		CAR.CAR_MODEL,
		CAR.CAR_REGO,
		CONTACT.BIRTHDATE,
		SE.EMPLOYMENT_TYPE_ID,
		EMPLOYMENT_TYPE.EMPLOYMENT_TYPE,
		SE.START_DATE,
		SE.END_DATE,
		QUALIFICATION.QUALIFICATION || ' (' || QUALIFICATION.QYEAR || ')' AS "QUALS",
		CONTACT_QUALIFICATION.YEAR_TEACHING AS "YEAR_TEACHING",
		CASE STAFF_COURSE.STAFF_COURSE
			WHEN '(None)' THEN ''
			ELSE STAFF_COURSE.STAFF_COURSE END
		AS "COURSES",
		STAFF_COURSE.DETAILS || ' (' || TO_CHAR(STAFF_COURSE.STARTDATE, 'DD Month YYYY') || ' to ' || TO_CHAR(STAFF_COURSE.ENDDATE, 'DD Month YYYY') || ')' AS "DEETS",
		STAFF_COURSE.STARTDATE,
		STAFF_COURSE.ENDDATE

	FROM STAFF

	INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
	INNER JOIN CONTACT_ADDRESS ON CONTACT_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
	INNER JOIN ADDRESS ON ADDRESS.ADDRESS_ID = CONTACT_ADDRESS.ADDRESS_ID
	LEFT JOIN PHONE ON PHONE.PHONE_ID = ADDRESS.PHONE_NUMBER
	INNER JOIN VIEW_CONTACT_HOME_ADDRESS ON VIEW_CONTACT_HOME_ADDRESS.CONTACT_ID = STAFF.CONTACT_ID
	FULL JOIN CAR ON CAR.CONTACT_ID = STAFF.CONTACT_ID
	INNER JOIN STAFF_EMPLOYMENT SE ON STAFF.STAFF_ID = SE.STAFF_ID
	INNER JOIN EMPLOYMENT_TYPE ON EMPLOYMENT_TYPE.EMPLOYMENT_TYPE_ID = SE.EMPLOYMENT_TYPE_ID
	LEFT JOIN QUALIFICATION ON QUALIFICATION.CONTACT_ID = STAFF.CONTACT_ID
	LEFT JOIN CONTACT_QUALIFICATION ON CONTACT_QUALIFICATION.CONTACT_ID = STAFF.CONTACT_ID
	LEFT JOIN STAFF_COURSE ON STAFF_COURSE.CONTACT_ID = STAFF.CONTACT_ID
	
	WHERE
		CONTACT.SURNAME NOT LIKE 'Coach'
			AND
		SE.EMPLOYMENT_TYPE_ID IN (1,2,4)
			AND
		STAFF.STAFF_ID != '1'
			AND
		SE.START_DATE <= current_date
			AND
		SE.END_DATE IS NULL
			OR
		SE.END_DATE > current_date
),

QUALS AS
(
	SELECT
		STAFF_NUMBER,
		substr( xmlserialize( xmlagg( xmltext( concat( ', ', QUALS ) ) ) as varchar( 2048 ) ), 3 ) AS "QUALIFICATIONS"
	
	FROM STAFFBASE
	GROUP BY STAFF_NUMBER, SURNAME, FIRSTNAME
),

TRAINING_COURSES AS
(
	SELECT
		STAFF_NUMBER,
		LISTAGG(DEETS, ', ') AS "COURSES"
		--substr( xmlserialize( xmlagg( xmltext( concat( ', ', DEETS ) ) ) as varchar( 2048 ) ), 3 ) AS "COURSES"
	
	FROM STAFFBASE
	
	WHERE STARTDATE > (current_date - 1 YEAR)
	AND DEETS IS NOT NULL
	AND COURSES IS NOT NULL
	AND DEETS NOT LIKE '$%'
	AND DEETS NOT LIKE 'Free'
	AND DEETS NOT LIKE 'nil'

	GROUP BY STAFF_NUMBER, SURNAME, FIRSTNAME
),

GENCY AS
(
	SELECT
		STAFF_NUMBER,
	    C2.FIRSTNAME || ' ' || C2.SURNAME AS "EMERGENCY_CONTACT_NAME",
	    REPLACE(
	        CASE WHEN RELATIONSHIP_TYPE.SYSTEM = 'CHILD' THEN 'PARENT' 
	            WHEN RELATIONSHIP_TYPE.SYSTEM = 'SREPCHILD' THEN 'STEPPARENT'
	            WHEN RELATIONSHIP_TYPE.SYSTEM = 'NIECENEWPHE' THEN 'AUNT/UCLE'
	            WHEN RELATIONSHIP_TYPE.SYSTEM = 'GRANDCHILD' THEN 'GRANDPARENT'
	            WHEN RELATIONSHIP_TYPE.SYSTEM = 'GODCHILD' THEN 'GODPARENT'
	            WHEN RELATIONSHIP_TYPE.SYSTEM = 'CHARGE' THEN 'GUARDIAN'
	            WHEN RELATIONSHIP_TYPE.SYSTEM = 'HOMESTAYCH' THEN 'HOMESTAYPARENT'
	            WHEN RELATIONSHIP_TYPE.SYSTEM = 'GRANDNIECE' THEN 'GRAND AUNT/UNCLE'
	            WHEN RELATIONSHIP_TYPE.SYSTEM = 'GODNIECENE' THEN 'GOD AUNT/UNCLE'
	            WHEN RELATIONSHIP_TYPE.SYSTEM = 'CHILDINLAW' THEN 'PARENTINLAW'
	            WHEN RELATIONSHIP_TYPE.SYSTEM = 'FOSTERCHIL' THEN 'FOSTERPARENT'
	            ELSE RELATIONSHIP_TYPE.RELATIONSHIP_TYPE END,'_','/'
	    ) AS "EMERGENCY_CONTACT_RELATION",
	    CASE WHEN HOME2.PHONE != '' THEN 'Home: ' || HOME2.PHONE || (CASE WHEN WP2.PHONE IS NOT NULL OR C2.MOBILE_PHONE IS NOT NULL THEN ' | ' ELSE '' END) ELSE '' END ||
	    CASE WHEN WP2.PHONE IS NOT NULL THEN 'Work: ' || '(' || WP2.AREA_CODE || ')' || WP2.PHONE || (CASE WHEN C2.MOBILE_PHONE IS NOT NULL THEN ' | ' ELSE '' END) ELSE '' END ||
	    CASE WHEN C2.MOBILE_PHONE IS NOT NULL THEN 'Mobile: ' || C2.MOBILE_PHONE ELSE '' END
	    AS EMERGENCY_NUMBERS
	
	FROM STAFF
	
	INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
	INNER JOIN CONTACT_ADDRESS ON CONTACT_ADDRESS.CONTACT_ID = CONTACT.CONTACT_ID
	INNER JOIN ADDRESS ON ADDRESS.ADDRESS_ID = CONTACT_ADDRESS.ADDRESS_ID AND ADDRESS.ADDRESS_TYPE_ID = 1
	INNER JOIN RELATIONSHIP ON (RELATIONSHIP.CONTACT_ID1 = CONTACT.CONTACT_ID OR RELATIONSHIP.CONTACT_ID2 = CONTACT.CONTACT_ID)
	INNER JOIN RELATIONSHIP_TYPE ON RELATIONSHIP_TYPE.RELATIONSHIP_TYPE_ID = RELATIONSHIP.RELATIONSHIP_TYPE_ID AND CALL_ORDER IN (1,2,3,4,5)
	INNER JOIN CONTACT C2 ON (C2.CONTACT_ID = RELATIONSHIP.CONTACT_ID1 OR C2.CONTACT_ID = RELATIONSHIP.CONTACT_ID2) AND C2.CONTACT_ID != CONTACT.CONTACT_ID
	INNER JOIN CARER CAR2 ON CAR2.CONTACT_ID = C2.CONTACT_ID
	LEFT JOIN SALUTATION SAL2 ON SAL2.SALUTATION_ID = C2.SALUTATION_ID AND SAL2.SALUTATION != 'UNSPECIFIED'
	LEFT JOIN WORK_DETAIL WD2 ON WD2.CONTACT_ID = C2.CONTACT_ID
	LEFT JOIN PHONE WP2 ON WP2.PHONE_ID = WD2.DIRECT_LINE
	LEFT JOIN VIEW_CONTACT_HOME_ADDRESS HOME2 ON HOME2.CONTACT_ID = C2.CONTACT_ID
	
	ORDER BY EMERGENCY_CONTACT_NAME
)

SELECT DISTINCT
	SURNAME,
	FIRSTNAME,
	EMPLOYMENT_TYPE,
	HOME_ADDRESS,
	HOME_PHONE,
	MOBILE_PHONE,
	CAR_MAKE,
	CAR_MODEL,
	CAR_REGO,
	BIRTHDATE,
	GENCY.EMERGENCY_CONTACT_NAME,
	GENCY.EMERGENCY_CONTACT_RELATION,
	GENCY.EMERGENCY_NUMBERS,
	YEAR_TEACHING,
	EMPLOYMENT_TYPE,
	START_DATE,
	END_DATE,
	QUALS.QUALIFICATIONS,
	TRAINING_COURSES.COURSES

FROM STAFFBASE

LEFT JOIN QUALS ON QUALS.STAFF_NUMBER = STAFFBASE.STAFF_NUMBER
LEFT JOIN TRAINING_COURSES ON TRAINING_COURSES.STAFF_NUMBER = STAFFBASE.STAFF_NUMBER
LEFT JOIN GENCY ON GENCY.STAFF_NUMBER = STAFFBASE.STAFF_NUMBER

ORDER BY SURNAME