WITH TWELVES AS (
  SELECT S.STUDENT_ID, S.FORM_RUN_ID, CLASS.CLASS, CLASS.CLASS_ID
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) S

  INNER JOIN VIEW_STUDENT_CLASS_ENROLMENT VSCE ON VSCE.STUDENT_ID = S.STUDENT_ID
  INNER JOIN CLASS ON CLASS.CLASS_ID = VSCE.CLASS_ID

  WHERE
    S.FORM_RUN_ID = (SELECT FORM_RUN_ID FROM FORM_RUN WHERE FORM_RUN = '2014 Year 12')
    AND
    VSCE.END_DATE > DATE('2013-10-20')
    AND
    VSCE.START_DATE > DATE('2013-10-20')
    AND
    CLASS.CLASS LIKE '% Home Room %'
),

THE_REST AS (
  SELECT S.STUDENT_ID, S.FORM_RUN_ID, CLASS.CLASS, CLASS.CLASS_ID
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) S
  INNER JOIN VIEW_STUDENT_CLASS_ENROLMENT VSCE ON VSCE.STUDENT_ID = S.STUDENT_ID
  INNER JOIN CLASS ON CLASS.CLASS_ID = VSCE.CLASS_ID
  WHERE
    FORM_RUN_ID IN (SELECT FORM_RUN_ID FROM FORM_RUN WHERE FORM_RUN IN ('2013 Year 07', '2013 Year 08', '2013 Year 09', '2013 Year 10'))
    AND
    CLASS.CLASS_TYPE_ID = 2
    AND
    VSCE.END_DATE > (CURRENT DATE)
),

STUDENT_BODY AS (
  SELECT * FROM TWELVES
  UNION
  SELECT * FROM THE_REST
)

SELECT
  STUDENT.STUDENT_NUMBER AS "LOOKUP_CODE",
  CONTACT.SURNAME,
  (CASE WHEN CONTACT.PREFERRED_NAME IS NULL THEN CONTACT.FIRSTNAME ELSE CONTACT.PREFERRED_NAME END) AS "FIRSTNAME",
  LISTAGG(FORM_RUN.FORM_RUN, ' and ') WITHIN GROUP(ORDER BY FORM_RUN.FORM_RUN) AS "FORM_RUN",
  S.CLASS AS "HOMEROOM"

FROM STUDENT_BODY S

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = S.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = S.FORM_RUN_ID

GROUP BY FORM_RUN.FORM_RUN, STUDENT.STUDENT_NUMBER, CONTACT.SURNAME, CONTACT.FIRSTNAME, CONTACT.PREFERRED_NAME, S.CLASS, S.CLASS_ID

ORDER BY S.CLASS_ID, CONTACT.SURNAME, CONTACT.FIRSTNAME