WITH YEAR_COS AS (
  SELECT
    CONTACT.CONTACT_ID,
    FORM_RUN.FORM_RUN,
    'Year Coordinator' AS "ROLE"
  
  FROM FORM_RUN
  
  INNER JOIN STAFF ON STAFF.STAFF_ID = FORM_RUN.COORDINATOR_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
  
  WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') || ' %'
),

PASTORAL_ASSTS AS (
  SELECT
    CONTACT.CONTACT_ID,
    (CASE
      WHEN CONTACT.CONTACT_ID = 21811 THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 07'
      WHEN CONTACT.CONTACT_ID = 21313 THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 08'
      WHEN CONTACT.CONTACT_ID = 54764 THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 09'
      WHEN CONTACT.CONTACT_ID = 21450 THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 10'
      WHEN CONTACT.CONTACT_ID = 54761 THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 11'
      WHEN CONTACT.CONTACT_ID = 21725 THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 12'
      ELSE NULL
    END) AS "FORM_RUN",
    'Pastoral Assistant' AS "ROLE"
  
  FROM CONTACT
  
  WHERE CONTACT.CONTACT_ID IN (21811,21313,54764,21450,54761,21725)
),

BOTH_GROUPS AS (
  SELECT * FROM YEAR_COS
  UNION
  SELECT * FROM PASTORAL_ASSTS
)

SELECT
  BOTH_GROUPS.CONTACT_ID,
  CONTACT.SURNAME,
  CONTACT.FIRSTNAME,
  BOTH_GROUPS.FORM_RUN,
  BOTH_GROUPS.ROLE

FROM BOTH_GROUPS

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = BOTH_GROUPS.CONTACT_ID

ORDER BY FORM_RUN, ROLE DESC