-- Year 12 References (year-12-references.sql)

-- A list of Year 12 students and the subjects they studied in their graduating year, sorted by surname.
-- This data is used as part of the writing process for the reference letters received by Year 12 students at the end of the year.
WITH ALL_STUDENTS AS (
  SELECT
    STUDENT.STUDENT_ID,
  	CONTACT.SURNAME,
  	CONTACT.FIRSTNAME,
  	CONTACT.PREFERRED_NAME,
  	CONTACT.BIRTHDATE,
  	GASS.START_DATE,
  	CAST((((DATE(CURRENT DATE)) - DATE((GASS.START_DATE))) / 10000) AS DECIMAL(3,2)) AS "TIME_AT_RBC"
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT_DATE)) REFERENCES

  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = REFERENCES.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID =
  (
    SELECT FORM_RUN.FORM_RUN_ID
    FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) GRSFR
    INNER JOIN FORM_RUN ON GRSFR.FORM_RUN_ID = FORM_RUN.FORM_RUN_ID
    WHERE GRSFR.STUDENT_ID = STUDENT.STUDENT_ID
    FETCH FIRST 1 ROW ONLY
  )
  INNER JOIN TABLE(EDUMATE.GETALLSTUDENTSTATUS(CURRENT DATE)) GASS ON GASS.STUDENT_ID = REFERENCES.STUDENT_ID
  
  WHERE FORM_RUN.FORM_RUN = TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 12'
  
  ORDER BY FORM_RUN.FORM_RUN ASC, CONTACT.SURNAME ASC
),

HOMEROOMS AS (
  SELECT
    VSCE.STUDENT_ID,
    VSCE.CLASS AS "HOMEROOM"
    
  FROM VIEW_STUDENT_CLASS_ENROLMENT VSCE
  
  INNER JOIN ALL_STUDENTS ON ALL_STUDENTS.STUDENT_ID = VSCE.STUDENT_ID

  WHERE
    VSCE.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY')
    AND
    VSCE.CLASS_TYPE_ID = 2
),

PRELIMS AS (
  SELECT
    VSCE.STUDENT_ID,
    LISTAGG(VSCE.COURSE, ', ') WITHIN GROUP(ORDER BY VSCE.STUDENT_ID) AS "PRELIM_CLASSES"

  FROM VIEW_STUDENT_CLASS_ENROLMENT VSCE

  INNER JOIN ALL_STUDENTS ON ALL_STUDENTS.STUDENT_ID = VSCE.STUDENT_ID

  WHERE
    (
      COURSE NOT LIKE '%%%%tudy%' AND
      COURSE NOT LIKE '%% Early Leave' AND
      COURSE NOT LIKE '%% Pastoral Care' AND
      COURSE NOT LIKE 'CS %' AND
      COURSE NOT LIKE 'CBSA %' AND
      COURSE NOT LIKE 'SCC %' AND
      COURSE NOT LIKE '% Yoga %' AND
      COURSE NOT LIKE 'Yoga%' AND
      COURSE NOT LIKE '%Lawn%' AND
      COURSE NOT LIKE '%Gym%' AND
      COURSE NOT LIKE '%Softball%' AND
      COURSE NOT LIKE '%Gym%' AND
      COURSE NOT LIKE '%Soccer%' AND
      COURSE NOT LIKE '%% Saturday School Languages' AND
      COURSE NOT LIKE 'LearningSupport %' AND
      COURSE NOT LIKE  'Photography Group'
    )
    AND
    (
      VSCE.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE - 1 YEAR), 'YYYY')
      AND
      VSCE.CLASS_TYPE_ID IN (1,9,10)
    )
    

  GROUP BY VSCE.STUDENT_ID
),

SENIORS AS (
  SELECT
    VSCE.STUDENT_ID,
    LISTAGG(VSCE.COURSE, ', ') WITHIN GROUP(ORDER BY VSCE.STUDENT_ID) AS "SENIOR_CLASSES"

  FROM VIEW_STUDENT_CLASS_ENROLMENT VSCE

  INNER JOIN ALL_STUDENTS ON ALL_STUDENTS.STUDENT_ID = VSCE.STUDENT_ID

  WHERE
    (
      COURSE NOT LIKE '%%%%tudy%' AND
      COURSE NOT LIKE '%% Early Leave' AND
      COURSE NOT LIKE '%% Pastoral Care' AND
      COURSE NOT LIKE 'CS %' AND
      COURSE NOT LIKE 'CBSA %' AND
      COURSE NOT LIKE 'SCC %' AND
      COURSE NOT LIKE '% Yoga %' AND
      COURSE NOT LIKE 'Yoga%' AND
      COURSE NOT LIKE '%Lawn%' AND
      COURSE NOT LIKE '%Gym%' AND
      COURSE NOT LIKE '%Softball%' AND
      COURSE NOT LIKE '%Gym%' AND
      COURSE NOT LIKE '%Soccer%' AND
      COURSE NOT LIKE '%% Saturday School Languages' AND
      COURSE NOT LIKE 'LearningSupport %' AND
      COURSE NOT LIKE  'Photography Group'
    )
    AND
    (
      VSCE.ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY')
      AND
      VSCE.CLASS_TYPE_ID IN (1,9,10)
    )
    

  GROUP BY VSCE.STUDENT_ID
)

SELECT
  ALL_STUDENTS.SURNAME,
  ALL_STUDENTS.FIRSTNAME,
  ALL_STUDENTS.PREFERRED_NAME,
  HOMEROOMS.HOMEROOM,
  ALL_STUDENTS.BIRTHDATE AS "DOB",
  ALL_STUDENTS.START_DATE,
  CASE WHEN
    ALL_STUDENTS.TIME_AT_RBC < 1.00 THEN CAST(ALL_STUDENTS.TIME_AT_RBC AS DECIMAL(3,2))
    ELSE
    CAST(ALL_STUDENTS.TIME_AT_RBC AS DECIMAL(3,1))
  END AS "TIME_AT_RBC",
  
  PRELIMS.PRELIM_CLASSES,
  SENIORS.SENIOR_CLASSES

FROM ALL_STUDENTS

INNER JOIN HOMEROOMS ON HOMEROOMS.STUDENT_ID = ALL_STUDENTS.STUDENT_ID
INNER JOIN PRELIMS ON PRELIMS.STUDENT_ID = ALL_STUDENTS.STUDENT_ID
INNER JOIN SENIORS ON SENIORS.STUDENT_ID = ALL_STUDENTS.STUDENT_ID

ORDER BY SURNAME