WITH REPORT_VARS AS (
  SELECT
    (SELECT
      (SUM(CASE WHEN GTRD.TERM_DATE <= (CURRENT DATE) THEN 1 ELSE 0 END) / 10)
    FROM TABLE(EDUMATE.GET_TIMETABLE_RUNNING_DATES(
      (SELECT TIMETABLE_ID
      FROM TERM WHERE TERM = 'Term 1'
      AND
      START_DATE LIKE (TO_CHAR((CURRENT DATE), 'YYYY')) || '-%%-%%' FETCH FIRST 1 ROW ONLY))) GTRD
    INNER JOIN TERM ON TERM.TERM_ID = GTRD.TERM_ID
    WHERE GTRD.DAY_INDEX NOT IN (888, 999)
    ) AS "FN",
    (DATE(CURRENT DATE)) AS "REPORT_END",
    (DATE(CURRENT DATE) - 11 DAYS) AS "REPORT_FN_START",
    -- Variables for Year Coordinators/Pastoral Assistants
    21811 AS "SEVEN_PA",
    21313 AS "EIGHT_PA",
    54764 AS "NINE_PA",
    21450 AS "TEN_PA",
    54761 AS "ELEVEN_PA",
    21725 AS "TWELVE_PA"
  
  FROM SYSIBM.SYSDUMMY1
),

YEAR_COS AS (
  SELECT
    CONTACT.CONTACT_ID,
    FORM_RUN.FORM_RUN,
    'Year Coordinator' AS "ROLE"
  
  FROM FORM_RUN
  
  INNER JOIN STAFF ON STAFF.STAFF_ID = FORM_RUN.COORDINATOR_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STAFF.CONTACT_ID
  
  WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') || ' %'
),

PASTORAL_ASSTS AS (
  SELECT
    CONTACT.CONTACT_ID,
    (CASE
      WHEN CONTACT.CONTACT_ID = REPORT_VARS.SEVEN_PA THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 07'
      WHEN CONTACT.CONTACT_ID = REPORT_VARS.EIGHT_PA THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 08'
      WHEN CONTACT.CONTACT_ID = REPORT_VARS.NINE_PA THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 09'
      WHEN CONTACT.CONTACT_ID = REPORT_VARS.TEN_PA THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 10'
      WHEN CONTACT.CONTACT_ID = REPORT_VARS.ELEVEN_PA THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 11'
      WHEN CONTACT.CONTACT_ID = REPORT_VARS.TWELVE_PA THEN TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 12'
      ELSE NULL
    END) AS "FORM_RUN",
    'Pastoral Assistant' AS "ROLE"
  
  FROM CONTACT
  
  CROSS JOIN REPORT_VARS
  
  WHERE CONTACT.CONTACT_ID IN (REPORT_VARS.SEVEN_PA, REPORT_VARS.EIGHT_PA, REPORT_VARS.NINE_PA, REPORT_VARS.TEN_PA, REPORT_VARS.ELEVEN_PA, REPORT_VARS.TWELVE_PA)
),

BOTH_GROUPS AS (
  SELECT * FROM YEAR_COS
  UNION
  SELECT * FROM PASTORAL_ASSTS
)

SELECT
  BOTH_GROUPS.CONTACT_ID,
  CONTACT.SURNAME,
  CONTACT.FIRSTNAME,
  BOTH_GROUPS.FORM_RUN,
  BOTH_GROUPS.ROLE,
  REPORT_VARS.REPORT_FN_START,
  REPORT_VARS.REPORT_END,
  REPORT_VARS.FN

FROM BOTH_GROUPS

INNER JOIN CONTACT ON CONTACT.CONTACT_ID = BOTH_GROUPS.CONTACT_ID
CROSS JOIN REPORT_VARS

ORDER BY FORM_RUN, ROLE DESC