CREATE OR REPLACE VIEW DB2INST1.VIEW_DASHBOARD (
  TIMETABLE,
  DEFAULT_FLAG,
  COMPUTED_V_START_DATE,
  COMPUTED_START_DATE,
  COMPUTED_END_DATE,
  CYCLE_WEEK
) AS

WITH CYCLE_WEEK AS (
  SELECT
    EDUMATE.GETDAYINDEX(TERM.START_DATE,TERM.CYCLE_START_DAY,CYCLE.DAYS_IN_CYCLE, (CURRENT DATE)) AS DAY_INDEX,
    (JULIAN_DAY(CURRENT DATE + 7 DAYS) / 7 - JULIAN_DAY((SELECT START_DATE FROM TERM WHERE (CURRENT DATE) BETWEEN TERM.START_DATE AND TERM.END_DATE FETCH FIRST 1 ROW ONLY)) / 7) AS "TERM_WEEK"
  
  FROM SYSIBM.SYSDUMMY1
  
  INNER JOIN TERM ON (CURRENT DATE) BETWEEN TERM.START_DATE AND TERM.END_DATE
  INNER JOIN TERM_GROUP ON TERM_GROUP.TERM_ID = TERM.TERM_ID
  INNER JOIN CYCLE ON CYCLE.CYCLE_ID = TERM_GROUP.CYCLE_ID
  INNER JOIN TIMETABLE ON TIMETABLE.TIMETABLE_ID = TERM.TIMETABLE_ID
  
  FETCH FIRST 1 ROW ONLY
)

SELECT
  TIMETABLE,
  DEFAULT_FLAG,
  COMPUTED_V_START_DATE,
  COMPUTED_START_DATE,
  COMPUTED_END_DATE,
  (SELECT 'Week ' || TERM_WEEK || (CASE WHEN DAY_INDEX BETWEEN 1 AND 5 THEN 'A' ELSE 'B' END) AS "CYCLE_WEEK" FROM CYCLE_WEEK) AS "CYCLE_WEEK"

FROM TIMETABLE

WHERE
  ACADEMIC_YEAR_ID IN (
    SELECT ACADEMIC_YEAR_ID
    FROM ACADEMIC_YEAR
    WHERE
      ACADEMIC_YEAR = YEAR(CURRENT DATE)
      OR
      ACADEMIC_YEAR = YEAR(CURRENT DATE + 1 YEAR)
  )