WITH ROLLS AS (
  SELECT DISTINCT
    ROLL_STATUS.CLASS_ID,
    ROLL_STATUS.COMPLETED
  
  FROM TABLE(EDUMATE.GET_NEED_ROLL_MARKED_CLASS((CURRENT DATE), (CURRENT DATE))) ROLL_STATUS
  
  WHERE
    ROLL_STATUS.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD IN ('Home Room 1', 'Period 1', 'Period 2'))
    AND
    ROLL_STATUS.DATE_ON = (CURRENT DATE)
),

EVENTS AS (
  SELECT
    ES.STUDENT_ID,
    --EVENT.EVENT
    LISTAGG(EVENT.EVENT, ', ') WITHIN GROUP(ORDER BY EVENT.EVENT) AS "EVENT" 
  
  FROM EVENT_STUDENT ES
  
  INNER JOIN EVENT ON EVENT.EVENT_ID = ES.EVENT_ID
  
  WHERE
    DATE(EVENT.START_DATE) = (CURRENT DATE)
    AND
    TIME(EVENT.START_DATE) < (SELECT TIME(START_TIME) FROM PERIOD WHERE PERIOD = 'Period 2' ORDER BY START_TIME DESC FETCH FIRST 1 ROW ONLY)
    
  GROUP BY ES.STUDENT_ID
),

TIMETABLED_HOMEROOM AS (
  SELECT
    VSCE.STUDENT_ID,
    GTOD.PERIOD_ID,
    GTOD.CLASS_ID,
    GTOD.CLASS
  
  FROM VIEW_STUDENT_CLASS_ENROLMENT VSCE
  
  INNER JOIN TABLE(EDUMATE.GET_TIMETABLE_ON_DATE(CURRENT DATE)) GTOD ON GTOD.CLASS_ID = VSCE.CLASS_ID

  WHERE
    GTOD.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD = 'Home Room 1')
    AND
    VSCE.END_DATE > (CURRENT DATE)
),

TIMETABLED_PERIOD_ONE AS (
  SELECT
    VSCE.STUDENT_ID,
    GTOD.PERIOD_ID,
    GTOD.CLASS_ID,
    GTOD.CLASS
  
  FROM VIEW_STUDENT_CLASS_ENROLMENT VSCE
  
  INNER JOIN TABLE(EDUMATE.GET_TIMETABLE_ON_DATE(CURRENT DATE)) GTOD ON GTOD.CLASS_ID = VSCE.CLASS_ID

  WHERE
    GTOD.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD = 'Period 1')
    AND
    VSCE.END_DATE > (CURRENT DATE)
),

TIMETABLED_PERIOD_TWO AS (
  SELECT
    VSCE.STUDENT_ID,
    GTOD.PERIOD_ID,
    GTOD.CLASS_ID,
    GTOD.CLASS
  
  FROM VIEW_STUDENT_CLASS_ENROLMENT VSCE
  
  INNER JOIN TABLE(EDUMATE.GET_TIMETABLE_ON_DATE(CURRENT DATE)) GTOD ON GTOD.CLASS_ID = VSCE.CLASS_ID

  WHERE
    GTOD.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD = 'Period 2')
    AND
    VSCE.END_DATE > (CURRENT DATE)
),

HOMEROOM AS (
  SELECT DISTINCT
    VA.PERIOD_ID,
    VA.CLASS_ID,
    VA.STUDENT_ID,
    CLASS.CLASS,
    ROLLS.COMPLETED

  FROM VIEW_ATTENDANCE VA

  INNER JOIN CLASS ON CLASS.CLASS_ID = VA.CLASS_ID
  INNER JOIN ROLLS ON ROLLS.CLASS_ID = VA.CLASS_ID

  WHERE
    DATE(VA.DATE_ON) = (CURRENT DATE)
    AND
    VA.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD = 'Home Room 1')
),

PERIOD_ONE AS (
  SELECT DISTINCT
    VA.PERIOD_ID,
    VA.CLASS_ID,
    VA.STUDENT_ID,
    CLASS.CLASS,
    ROLLS.COMPLETED
  
  FROM VIEW_ATTENDANCE VA
  
  INNER JOIN CLASS ON CLASS.CLASS_ID = VA.CLASS_ID
  INNER JOIN ROLLS ON ROLLS.CLASS_ID = VA.CLASS_ID
  
  WHERE
    DATE(VA.DATE_ON) = (CURRENT DATE)
    AND
    VA.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD = 'Period 1')
),

PERIOD_TWO AS (
  SELECT DISTINCT
    VA.PERIOD_ID,
    VA.CLASS_ID,
    VA.STUDENT_ID,
    CLASS.CLASS,
    ROLLS.COMPLETED
  
  FROM VIEW_ATTENDANCE VA
  
  INNER JOIN CLASS ON CLASS.CLASS_ID = VA.CLASS_ID
  INNER JOIN ROLLS ON ROLLS.CLASS_ID = VA.CLASS_ID
  
  WHERE
    DATE(VA.DATE_ON) = (CURRENT DATE)
    AND
    VA.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD = 'Period 2')
),

ABSENTS AS (
  SELECT DA.STUDENT_ID
  
  FROM DAILY_ATTENDANCE DA
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = DA.STUDENT_ID
  
  WHERE
    DA.DATE_ON = (CURRENT DATE)
    AND
    --Only students with unexplained absences
    DA.DAILY_ATTENDANCE_STATUS_ID = 2
    AND
    --This is a double check if an operator forgot to use the 'All Day' flag when entering a reason
    STUDENT.STUDENT_ID NOT IN (
      SELECT STUDENT_ID
      FROM ABSENTEE_REASON
      WHERE DATE(CURRENT DATE) BETWEEN DATE(EFFECTIVE_START) AND DATE(EFFECTIVE_END)
    )
),

TOTALS AS (
  SELECT COUNT(STUDENT_ID) AS "TOTAL_STUDENTS"
  FROM ABSENTS
)

SELECT
  STUDENT.STUDENT_NUMBER AS "LOOKUP_CODE",
  
  UPPER(CONTACT.SURNAME) AS "SURNAME",
  (CASE WHEN CONTACT.PREFERRED_NAME IS NULL THEN CONTACT.FIRSTNAME ELSE CONTACT.PREFERRED_NAME END) AS "FIRSTNAME",

  (CASE
    WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 07' THEN 'Year 7'
    WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 08' THEN 'Year 8'
    WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 09' THEN 'Year 9'
    WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 10' THEN 'Year 10'
    WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 11' THEN 'Year 11'
    WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 12' THEN 'Year 12'
  ELSE NULL END) AS "FORM_RUN",

  (CASE
    WHEN HOMEROOM.CLASS IS NULL THEN '! ' || REPLACE(TIMETABLED_HOMEROOM.CLASS, ' Home Room', '') || ' !'
    ELSE REPLACE(HOMEROOM.CLASS, ' Home Room', '')
  END) AS "HOMEROOM",
  
  (CASE
    WHEN HOMEROOM.COMPLETED = 1 THEN 'Yes'
    WHEN HOMEROOM.COMPLETED = 0 THEN 'No'
    WHEN HOMEROOM.COMPLETED IS NULL THEN 'No'
    ELSE NULL
  END) AS "HOMEROOM_ROLL",
  
  (CASE WHEN EVENTS.EVENT IS NULL THEN
    (CASE
      WHEN PERIOD_ONE.CLASS IS NULL THEN '! ' || TIMETABLED_PERIOD_ONE.CLASS || ' !'
      ELSE PERIOD_ONE.CLASS
    END)
  ELSE 'On event: ' || EVENTS.EVENT END) AS "PERIOD_ONE",
  
  (CASE
    WHEN PERIOD_ONE.COMPLETED = 1 THEN 'Yes'
    WHEN PERIOD_ONE.COMPLETED = 0 THEN 'No'
    WHEN PERIOD_ONE.COMPLETED IS NULL THEN 'No'
    ELSE NULL
  END) AS "PERIOD_ONE_ROLL",

  (CASE WHEN EVENTS.EVENT IS NULL THEN
    (CASE
      WHEN PERIOD_TWO.CLASS IS NULL THEN '! ' || TIMETABLED_PERIOD_TWO.CLASS || ' !'
      ELSE PERIOD_TWO.CLASS
    END)
  ELSE 'On event: ' || EVENTS.EVENT END) AS "PERIOD_TWO",

  (CASE
    WHEN PERIOD_TWO.COMPLETED = 1 THEN 'Yes'
    WHEN PERIOD_TWO.COMPLETED = 0 THEN 'No'
    WHEN PERIOD_TWO.COMPLETED IS NULL THEN 'No'
    ELSE NULL
  END) AS "PERIOD_TWO_ROLL",
  
  CHAR(TIME(CURRENT TIMESTAMP),USA) AS "PRINT_TIME",
  TO_CHAR((CURRENT DATE), 'DD Month, YYYY') AS "PRINT_DATE",
  TOTALS.TOTAL_STUDENTS

FROM ABSENTS

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = ABSENTS.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID

INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID =
(
  SELECT FORM_RUN.FORM_RUN_ID
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) GRSFR
  INNER JOIN FORM_RUN ON GRSFR.FORM_RUN_ID = FORM_RUN.FORM_RUN_ID
  WHERE GRSFR.STUDENT_ID = ABSENTS.STUDENT_ID
  FETCH FIRST 1 ROW ONLY
)

LEFT JOIN HOMEROOM ON HOMEROOM.STUDENT_ID = ABSENTS.STUDENT_ID
LEFT JOIN TIMETABLED_HOMEROOM ON TIMETABLED_HOMEROOM.STUDENT_ID = ABSENTS.STUDENT_ID

LEFT JOIN PERIOD_ONE ON PERIOD_ONE.STUDENT_ID = ABSENTS.STUDENT_ID
LEFT JOIN TIMETABLED_PERIOD_ONE ON TIMETABLED_PERIOD_ONE.STUDENT_ID = ABSENTS.STUDENT_ID

LEFT JOIN PERIOD_TWO ON PERIOD_TWO.STUDENT_ID = ABSENTS.STUDENT_ID
LEFT JOIN TIMETABLED_PERIOD_TWO ON TIMETABLED_PERIOD_TWO.STUDENT_ID = ABSENTS.STUDENT_ID

LEFT JOIN EVENTS ON EVENTS.STUDENT_ID = ABSENTS.STUDENT_ID

CROSS JOIN TOTALS

ORDER BY FORM_RUN.FORM_RUN, HOMEROOM.CLASS_ID, CONTACT.SURNAME, CONTACT.FIRSTNAME