SELECT
  GNRMC.FIRSTNAME AS "TEACHER_FIRSTNAME",
  GNRMC.SURNAME AS "TEACHER_SURNAME",
  GNRMC.CLASS,
  GNRMC.PERIOD,
  GNRMC.DATE_ON

FROM TABLE(EDUMATE.GET_NEED_ROLL_MARKED_CLASS((CURRENT DATE), (CURRENT DATE))) GNRMC

WHERE
  GNRMC.COMPLETED IS NULL
  AND
  GNRMC.PERIOD IN ('Home Room 1', 'Period 1', 'Period 2')
  AND
  GNRMC.CLASS != 'CASPE R'

ORDER BY GNRMC.START_TIME, GNRMC.CLASS, GNRMC.SURNAME