WITH ROLLS AS (
  SELECT DISTINCT
    ROLL_STATUS.CLASS_ID,
    ROLL_STATUS.COMPLETED
  
  FROM TABLE(EDUMATE.GET_NEED_ROLL_MARKED_CLASS((CURRENT DATE), (CURRENT DATE))) ROLL_STATUS
  
  WHERE
    ROLL_STATUS.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD IN ('Home Room 1', 'Period 1', 'Period 2'))
    AND
    ROLL_STATUS.DATE_ON = (CURRENT DATE)
),

HOMEROOM AS (
  SELECT DISTINCT
    VA.PERIOD_ID,
    VA.CLASS_ID,
    VA.STUDENT_ID,
    CLASS.CLASS,
    ROLLS.COMPLETED

  FROM VIEW_ATTENDANCE VA

  INNER JOIN CLASS ON CLASS.CLASS_ID = VA.CLASS_ID
  INNER JOIN ROLLS ON ROLLS.CLASS_ID = VA.CLASS_ID

  WHERE
    DATE(VA.DATE_ON) = (CURRENT DATE)
    AND
    VA.EVENT_ID IS NULL
    AND
    VA.AM_PM_ID = 1
    AND
    VA.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD = 'Home Room 1')
),

PERIOD_ONE AS (
  SELECT DISTINCT
    VA.PERIOD_ID,
    VA.CLASS_ID,
    VA.STUDENT_ID,
    CLASS.CLASS,
    ROLLS.COMPLETED
  
  FROM VIEW_ATTENDANCE VA
  
  INNER JOIN CLASS ON CLASS.CLASS_ID = VA.CLASS_ID
  INNER JOIN ROLLS ON ROLLS.CLASS_ID = VA.CLASS_ID
  
  WHERE
    DATE(VA.DATE_ON) = (CURRENT DATE)
    AND
    VA.EVENT_ID IS NULL
    AND
    VA.AM_PM_ID = 1
    AND
    VA.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD = 'Period 1')
),

PERIOD_TWO AS (
  SELECT DISTINCT
    VA.PERIOD_ID,
    VA.CLASS_ID,
    VA.STUDENT_ID,
    CLASS.CLASS,
    ROLLS.COMPLETED
  
  FROM VIEW_ATTENDANCE VA
  
  INNER JOIN CLASS ON CLASS.CLASS_ID = VA.CLASS_ID
  INNER JOIN ROLLS ON ROLLS.CLASS_ID = VA.CLASS_ID
  
  WHERE
    DATE(VA.DATE_ON) = (CURRENT DATE)
    AND
    VA.EVENT_ID IS NULL
    AND
    VA.AM_PM_ID = 1
    AND
    VA.PERIOD_ID IN (SELECT DISTINCT PERIOD_ID FROM PERIOD WHERE PERIOD = 'Period 2')
),

ABSENTS AS (
  SELECT DA.STUDENT_ID
  
  FROM DAILY_ATTENDANCE DA
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = DA.STUDENT_ID
  
  WHERE
    DA.DATE_ON = (CURRENT DATE)
    AND
    --Only students with unexplained absences
    DA.DAILY_ATTENDANCE_STATUS_ID = 2
    AND
    --This is a double check if an operator forgot to use the 'All Day' flag when entering a reason
    STUDENT.STUDENT_ID NOT IN (
      SELECT STUDENT_ID
      FROM ABSENTEE_REASON
      WHERE DATE(CURRENT DATE) BETWEEN DATE(EFFECTIVE_START) AND DATE(EFFECTIVE_END)
    )
)

SELECT
  STUDENT.STUDENT_NUMBER,
  
  CONTACT.SURNAME,
  CONTACT.FIRSTNAME,
  
  HOMEROOM.CLASS AS "HOMEROOM",
  (CASE
    WHEN HOMEROOM.COMPLETED = 1 THEN 'þ'
    WHEN HOMEROOM.COMPLETED = 0 THEN 'ý'
    WHEN HOMEROOM.COMPLETED = NULL THEN '?'
    ELSE NULL
  END)AS "HOMEROOM_ROLL",
  
  PERIOD_ONE.CLASS AS "PERIOD_ONE",
  (CASE
    WHEN PERIOD_ONE.COMPLETED = 1 THEN 'þ'
    WHEN PERIOD_ONE.COMPLETED = 0 THEN 'ý'
    WHEN PERIOD_ONE.COMPLETED = NULL THEN '?'
    ELSE NULL
  END)AS "PERIOD_ONE_ROLL",

  PERIOD_TWO.CLASS AS "PERIOD_TWO",
  (CASE
    WHEN PERIOD_TWO.COMPLETED = 1 THEN 'þ'
    WHEN PERIOD_TWO.COMPLETED = 0 THEN 'ý'
    WHEN PERIOD_TWO.COMPLETED = NULL THEN '?'
    ELSE NULL
  END)AS "PERIOD_TWO_ROLL"

FROM ABSENTS

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = ABSENTS.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
INNER JOIN HOMEROOM ON HOMEROOM.STUDENT_ID = ABSENTS.STUDENT_ID
INNER JOIN PERIOD_ONE ON PERIOD_ONE.STUDENT_ID = ABSENTS.STUDENT_ID
INNER JOIN PERIOD_TWO ON PERIOD_TWO.STUDENT_ID = ABSENTS.STUDENT_ID

ORDER BY HOMEROOM.CLASS_ID, CONTACT.SURNAME, CONTACT.FIRSTNAME