WITH REPORT_VARS AS (
-- Table: Reporting Periods - Start and End Dates
-- NOTE: These will need to be turned into Edumate's [[Date picker]] style selectors before launch.

  SELECT
    TO_CHAR((CURRENT DATE), 'YYYY') AS "CURRENT_YEAR",
    (DATE('2013-01-31')) AS "SEVEN_START",
    (DATE('2013-06-06')) AS "SEVEN_END",
    (DATE('2013-01-31')) AS "EIGHT_START",
    (DATE('2013-06-06')) AS "EIGHT_END",
    (DATE('2013-01-31')) AS "NINE_START",
    (DATE('2013-06-06')) AS "NINE_END",
  
    (DATE('2013-01-31')) AS "TEN_START",
    (DATE('2013-05-13')) AS "TEN_END",
    (DATE('2013-01-31')) AS "ELEVEN_START",
    (DATE('2013-05-13')) AS "ELEVEN_END",
    (DATE('2012-10-10')) AS "TWELVE_START",
    (DATE('2013-05-13')) AS "TWELVE_END"

  FROM SYSIBM.SYSDUMMY1
),

SEVEN_ATTENDANCE_DATA AS (
  SELECT
    REPORT_VARS.SEVEN_START,
    REPORT_VARS.SEVEN_END,
    GSFR.STUDENT_ID,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    FORM_RUN.FORM_RUN,
    ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS AS "ABSENCES",
    ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS AS "LATES"  
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT_DATE)) GSFR
  
  INNER JOIN DAILY_ATTENDANCE DA ON DA.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN REPORT_VARS
  
  -- Absences join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DA.DAILY_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS LIKE '%Absence%' AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS NOT LIKE '%Partial Absence%'
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID NOT IN (20,21,22,23,24,25,26,27)
    AND DA.DATE_ON BETWEEN REPORT_VARS.SEVEN_START AND REPORT_VARS.SEVEN_END
  
  -- Lates join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DA.AM_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS LIKE '%Late%'
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID NOT IN (28,29,30,31)
    AND DA.DATE_ON BETWEEN REPORT_VARS.SEVEN_START AND REPORT_VARS.SEVEN_END
  
  WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 07'

  ORDER BY SURNAME, FORM_RUN
),

EIGHT_ATTENDANCE_DATA AS (
  SELECT
    REPORT_VARS.EIGHT_START,
    REPORT_VARS.EIGHT_END,
    GSFR.STUDENT_ID,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    FORM_RUN.FORM_RUN,
    ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS AS "ABSENCES",
    ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS AS "LATES"  
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT_DATE)) GSFR
  
  INNER JOIN DAILY_ATTENDANCE DA ON DA.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN REPORT_VARS
  
  -- Absences join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DA.DAILY_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS LIKE '%Absence%' AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS NOT LIKE '%Partial Absence%'
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID NOT IN (20,21,22,23,24,25,26,27)
    AND DA.DATE_ON BETWEEN REPORT_VARS.EIGHT_START AND REPORT_VARS.EIGHT_END
  
  -- Lates join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DA.AM_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS LIKE '%Late%'
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID NOT IN (28,29,30,31)
    AND DA.DATE_ON BETWEEN REPORT_VARS.EIGHT_START AND REPORT_VARS.EIGHT_END
  
  WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 08'

  ORDER BY SURNAME, FORM_RUN
),

NINE_ATTENDANCE_DATA AS (
  SELECT
    REPORT_VARS.NINE_START,
    REPORT_VARS.NINE_END,
    GSFR.STUDENT_ID,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    FORM_RUN.FORM_RUN,
    ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS AS "ABSENCES",
    ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS AS "LATES"  
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT_DATE)) GSFR
  
  INNER JOIN DAILY_ATTENDANCE DA ON DA.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN REPORT_VARS
  
  -- Absences join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DA.DAILY_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS LIKE '%Absence%' AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS NOT LIKE '%Partial Absence%'
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID NOT IN (20,21,22,23,24,25,26,27)
    AND DA.DATE_ON BETWEEN REPORT_VARS.NINE_START AND REPORT_VARS.NINE_END
  
  -- Lates join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DA.AM_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS LIKE '%Late%'
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID NOT IN (28,29,30,31)
    AND DA.DATE_ON BETWEEN REPORT_VARS.NINE_START AND REPORT_VARS.NINE_END
  
  WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 09'

  ORDER BY SURNAME, FORM_RUN
),

TEN_ATTENDANCE_DATA AS (
  SELECT
    REPORT_VARS.TEN_START,
    REPORT_VARS.TEN_END,
    GSFR.STUDENT_ID,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    FORM_RUN.FORM_RUN,
    ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS AS "ABSENCES",
    ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS AS "LATES"  
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT_DATE)) GSFR
  
  INNER JOIN DAILY_ATTENDANCE DA ON DA.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN REPORT_VARS
  
  -- Absences join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DA.DAILY_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS LIKE '%Absence%' AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS NOT LIKE '%Partial Absence%'
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID NOT IN (20,21,22,23,24,25,26,27)
    AND DA.DATE_ON BETWEEN REPORT_VARS.TEN_START AND REPORT_VARS.TEN_END
  
  -- Lates join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DA.AM_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS LIKE '%Late%'
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID NOT IN (28,29,30,31)
    AND DA.DATE_ON BETWEEN REPORT_VARS.TEN_START AND REPORT_VARS.TEN_END
  
  WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 10'

  ORDER BY SURNAME, FORM_RUN
),

ELEVEN_ATTENDANCE_DATA AS (
  SELECT
    REPORT_VARS.ELEVEN_START,
    REPORT_VARS.ELEVEN_END,
    GSFR.STUDENT_ID,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    FORM_RUN.FORM_RUN,
    ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS AS "ABSENCES",
    ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS AS "LATES"  
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT_DATE)) GSFR
  
  INNER JOIN DAILY_ATTENDANCE DA ON DA.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN REPORT_VARS
  
  -- Absences join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DA.DAILY_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS LIKE '%Absence%' AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS NOT LIKE '%Partial Absence%'
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID NOT IN (20,21,22,23,24,25,26,27)
    AND DA.DATE_ON BETWEEN REPORT_VARS.ELEVEN_START AND REPORT_VARS.ELEVEN_END
  
  -- Lates join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DA.AM_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS LIKE '%Late%'
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID NOT IN (28,29,30,31)
    AND DA.DATE_ON BETWEEN REPORT_VARS.ELEVEN_START AND REPORT_VARS.ELEVEN_END
  
  WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 11'

  ORDER BY SURNAME, FORM_RUN
),

TWELVE_ATTENDANCE_DATA AS (
  SELECT
    REPORT_VARS.TWELVE_START,
    REPORT_VARS.TWELVE_END,
    GSFR.STUDENT_ID,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    FORM_RUN.FORM_RUN,
    ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS AS "ABSENCES",
    ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS AS "LATES"  
  
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT_DATE)) GSFR
  
  INNER JOIN DAILY_ATTENDANCE DA ON DA.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GSFR.FORM_RUN_ID
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = GSFR.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN REPORT_VARS
  
  -- Absences join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DA.DAILY_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS LIKE '%Absence%' AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS NOT LIKE '%Partial Absence%'
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID NOT IN (20,21,22,23,24,25,26,27)
    AND DA.DATE_ON BETWEEN REPORT_VARS.TWELVE_START AND REPORT_VARS.TWELVE_END
  
  -- Lates join
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DA.AM_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS LIKE '%Late%'
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID NOT IN (28,29,30,31)
    AND DA.DATE_ON BETWEEN REPORT_VARS.TWELVE_START AND REPORT_VARS.TWELVE_END
  
  WHERE FORM_RUN LIKE TO_CHAR((CURRENT DATE), 'YYYY') || ' Year 12'

  ORDER BY SURNAME, FORM_RUN
),

SEVEN_ABSENCES_LATES_COUNT AS (
  SELECT
    ROWNUMBER() OVER () AS "ROWNUMBER",
    SEVEN.STUDENT_ID,
    SEVEN.SURNAME,
    SEVEN.FORM_RUN,
    COUNT(ABSENCES) AS "SEVEN_ABSENCES_COUNT",
    COUNT(LATES) AS "SEVEN_LATES_COUNT",
    COUNT(STUDENT_ID) AS "TOTAL_SEVEN_STUDENTS"
  
  FROM SEVEN_ATTENDANCE_DATA SEVEN
  
  GROUP BY SEVEN.STUDENT_ID, SEVEN.SURNAME, SEVEN.FORM_RUN
  
  ORDER BY SEVEN.SURNAME
),

SEVEN_ABSENCES_LATES_AVG_TOTAL AS (
  SELECT
    ROW_NUMBER() OVER (),
    TOTAL_SEVEN_STUDENTS,
    AVG(SEVEN_ABSENCES_COUNT) AS "SEVEN_ABSENCES_AVG",
    SUM(SEVEN_ABSENCES_COUNT) AS "SEVEN_ABSENCES_TOTAL",
    AVG(SEVEN_LATES_COUNT) AS "SEVEN_LATES_AVG",
    SUM(SEVEN_LATES_COUNT) AS "SEVEN_LATES_TOTAL"
  
  FROM SEVEN_ABSENCES_LATES_COUNT
),

EIGHT_ABSENCES_LATES_COUNT AS (
  SELECT
    ROWNUMBER() OVER () AS "ROWNUMBER",
    EIGHT.STUDENT_ID,
    EIGHT.SURNAME,
    EIGHT.FORM_RUN,
    COUNT(ABSENCES) AS "EIGHT_ABSENCES_COUNT",
    COUNT(LATES) AS "EIGHT_LATES_COUNT",
    COUNT(STUDENT_ID) AS "TOTAL_EIGHT_STUDENTS"
  
  FROM EIGHT_ATTENDANCE_DATA EIGHT
  
  GROUP BY EIGHT.STUDENT_ID, EIGHT.SURNAME, EIGHT.FORM_RUN
  
  ORDER BY EIGHT.SURNAME
),

EIGHT_ABSENCES_LATES_AVG_TOTAL AS (
  SELECT
    ROW_NUMBER() OVER (),
    TOTAL_EIGHT_STUDENTS,
    AVG(EIGHT_ABSENCES_COUNT) AS "EIGHT_ABSENCES_AVG",
    SUM(EIGHT_ABSENCES_COUNT) AS "EIGHT_ABSENCES_TOTAL",
    AVG(EIGHT_LATES_COUNT) AS "EIGHT_LATES_AVG",
    SUM(EIGHT_LATES_COUNT) AS "EIGHT_LATES_TOTAL"
  
  FROM EIGHT_ABSENCES_LATES_COUNT
),

NINE_ABSENCES_LATES_COUNT AS (
  SELECT
    ROWNUMBER() OVER () AS "ROWNUMBER",
    NINE.STUDENT_ID,
    NINE.SURNAME,
    NINE.FORM_RUN,
    COUNT(ABSENCES) AS "NINE_ABSENCES_COUNT",
    COUNT(LATES) AS "NINE_LATES_COUNT",
    COUNT(STUDENT_ID) AS "TOTAL_NINE_STUDENTS"
  
  FROM NINE_ATTENDANCE_DATA NINE
  
  GROUP BY NINE.STUDENT_ID, NINE.SURNAME, NINE.FORM_RUN
  
  ORDER BY NINE.SURNAME
),

NINE_ABSENCES_LATES_AVG_TOTAL AS (
  SELECT
    ROW_NUMBER() OVER (),
    TOTAL_NINE_STUDENTS,
    AVG(NINE_ABSENCES_COUNT) AS "NINE_ABSENCES_AVG",
    SUM(NINE_ABSENCES_COUNT) AS "NINE_ABSENCES_TOTAL",
    AVG(NINE_LATES_COUNT) AS "NINE_LATES_AVG",
    SUM(NINE_LATES_COUNT) AS "NINE_LATES_TOTAL"
  
  FROM NINE_ABSENCES_LATES_COUNT
),

TEN_ABSENCES_LATES_COUNT AS (
  SELECT
    ROWNUMBER() OVER () AS "ROWNUMBER",
    TEN.STUDENT_ID,
    TEN.SURNAME,
    TEN.FORM_RUN,
    COUNT(ABSENCES) AS "TEN_ABSENCES_COUNT",
    COUNT(LATES) AS "TEN_LATES_COUNT",
    COUNT(STUDENT_ID) AS "TOTAL_TEN_STUDENTS"
  
  FROM TEN_ATTENDANCE_DATA TEN
  
  GROUP BY TEN.STUDENT_ID, TEN.SURNAME, TEN.FORM_RUN
  
  ORDER BY TEN.SURNAME
),

TEN_ABSENCES_LATES_AVG_TOTAL AS (
  SELECT
    ROW_NUMBER() OVER (),
    TOTAL_TEN_STUDENTS,
    AVG(TEN_ABSENCES_COUNT) AS "TEN_ABSENCES_AVG",
    SUM(TEN_ABSENCES_COUNT) AS "TEN_ABSENCES_TOTAL",
    AVG(TEN_LATES_COUNT) AS "TEN_LATES_AVG",
    SUM(TEN_LATES_COUNT) AS "TEN_LATES_TOTAL"
  
  FROM TEN_ABSENCES_LATES_COUNT
),

ELEVEN_ABSENCES_LATES_COUNT AS (
  SELECT
    ROWNUMBER() OVER () AS "ROWNUMBER",
    ELEVEN.STUDENT_ID,
    ELEVEN.SURNAME,
    ELEVEN.FORM_RUN,
    COUNT(ABSENCES) AS "ELEVEN_ABSENCES_COUNT",
    COUNT(LATES) AS "ELEVEN_LATES_COUNT",
    COUNT(STUDENT_ID) AS "TOTAL_ELEVEN_STUDENTS"
  
  FROM ELEVEN_ATTENDANCE_DATA ELEVEN
  
  GROUP BY ELEVEN.STUDENT_ID, ELEVEN.SURNAME, ELEVEN.FORM_RUN
  
  ORDER BY ELEVEN.SURNAME
),

ELEVEN_ABSENCES_LATES_AVG_TOTAL AS (
  SELECT
    ROW_NUMBER() OVER (),
    TOTAL_ELEVEN_STUDENTS,
    AVG(ELEVEN_ABSENCES_COUNT) AS "ELEVEN_ABSENCES_AVG",
    SUM(ELEVEN_ABSENCES_COUNT) AS "ELEVEN_ABSENCES_TOTAL",
    AVG(ELEVEN_LATES_COUNT) AS "ELEVEN_LATES_AVG",
    SUM(ELEVEN_LATES_COUNT) AS "ELEVEN_LATES_TOTAL"
  
  FROM ELEVEN_ABSENCES_LATES_COUNT
),

TWELVE_ABSENCES_LATES_COUNT AS (
  SELECT
    ROWNUMBER() OVER () AS "ROWNUMBER",
    TWELVE.STUDENT_ID,
    TWELVE.SURNAME,
    TWELVE.FORM_RUN,
    COUNT(ABSENCES) AS "TWELVE_ABSENCES_COUNT",
    COUNT(LATES) AS "TWELVE_LATES_COUNT",
    COUNT(STUDENT_ID) AS "TOTAL_TWELVE_STUDENTS"
  
  FROM TWELVE_ATTENDANCE_DATA TWELVE
  
  GROUP BY TWELVE.STUDENT_ID, TWELVE.SURNAME, TWELVE.FORM_RUN
  
  ORDER BY TWELVE.SURNAME
),

TWELVE_ABSENCES_LATES_AVG_TOTAL AS (
  SELECT
    ROW_NUMBER() OVER (),
    TOTAL_TWELVE_STUDENTS,
    AVG(TWELVE_ABSENCES_COUNT) AS "TWELVE_ABSENCES_AVG",
    SUM(TWELVE_ABSENCES_COUNT) AS "TWELVE_ABSENCES_TOTAL",
    AVG(TWELVE_LATES_COUNT) AS "TWELVE_LATES_AVG",
    SUM(TWELVE_LATES_COUNT) AS "TWELVE_LATES_TOTAL"
  
  FROM TWELVE_ABSENCES_LATES_COUNT
)

SELECT DISTINCT
  FIRSTNAME,
  SURNAME,
  FORM_RUN,
----------------------------------
  SEVEN_ALC.SEVEN_ABSENCES_COUNT AS "SEVEN_ABSENCES",
  SEVEN_ALC.SEVEN_LATES_COUNT AS "SEVEN_LATES",

  (CASE WHEN SEVEN_ALC.ROWNUMBER = 1 THEN SEVEN_ALC.TOTAL_SEVEN_STUDENTS ELSE NULL END) AS "TOTAL_SEVEN_STUDENTS",
  (CASE WHEN SEVEN_ALC.ROWNUMBER = 1 THEN SEVEN_ALAT.SEVEN_ABSENCES_AVG ELSE NULL END) AS "SEVEN_ABSENCES_AVG",
  (CASE WHEN SEVEN_ALC.ROWNUMBER = 1 THEN SEVEN_ALAT.SEVEN_ABSENCES_TOTAL ELSE NULL END) AS "TOTAL_SEVEN_ABSENCES",
  (CASE WHEN SEVEN_ALC.ROWNUMBER = 1 THEN SEVEN_ALAT.SEVEN_LATES_AVG ELSE NULL END) AS "SEVEN_LATES_AVG",
  (CASE WHEN SEVEN_ALC.ROWNUMBER = 1 THEN SEVEN_ALAT.SEVEN_LATES_TOTAL ELSE NULL END) AS "TOTAL_SEVEN_LATES",

  (CASE WHEN SEVEN_ALC.ROWNUMBER = 1 THEN TO_CHAR((SEVEN_DATA.SEVEN_START), 'DD Month YYYY') ELSE NULL END) AS "SEVEN_REPORT_PERIOD_START",
  (CASE WHEN SEVEN_ALC.ROWNUMBER = 1 THEN TO_CHAR((SEVEN_DATA.SEVEN_END), 'DD Month YYYY') ELSE NULL END) AS "SEVEN_REPORT_PERIOD_END"
----------------------------------

FROM SEVEN_ATTENDANCE_DATA SEVEN_DATA
/*EIGHT_ATTENDANCE_DATA EIGHT_DATA, NINE_ATTENDANCE_DATA NINE_DATA, TEN_ATTENDANCE_DATA TEN_DATA, ELEVEN_ATTENDANCE_DATA ELEVEN_DATA, TWELVE_ATTENDANCE_DATA TWELVE_DATA
*/

INNER JOIN SEVEN_ABSENCES_LATES_COUNT SEVEN_ALC ON SEVEN_ALC.STUDENT_ID = SEVEN_DATA.STUDENT_ID
INNER JOIN EIGHT_ABSENCES_LATES_COUNT EIGHT_ALC ON EIGHT_ALC.STUDENT_ID = EIGHT_DATA.STUDENT_ID
INNER JOIN NINE_ABSENCES_LATES_COUNT NINE_ALC ON NINE_ALC.STUDENT_ID = NINE_DATA.STUDENT_ID
INNER JOIN TEN_ABSENCES_LATES_COUNT TEN_ALC ON TEN_ALC.STUDENT_ID = TEN_DATA.STUDENT_ID
INNER JOIN ELEVEN_ABSENCES_LATES_COUNT ELEVEN_ALC ON ELEVEN_ALC.STUDENT_ID = ELEVEN_DATA.STUDENT_ID
INNER JOIN TWELVE_ABSENCES_LATES_COUNT TWELVE_ALC ON TWELVE_ALC.STUDENT_ID = TWELVE_DATA.STUDENT_ID

INNER JOIN SEVEN_ABSENCES_LATES_AVG_TOTAL SEVEN_ALAT ON SEVEN_ALC.STUDENT_ID = SEVEN_DATA.STUDENT_ID
INNER JOIN EIGHT_ABSENCES_LATES_AVG_TOTAL EIGHT_ALAT ON EIGHT_ALC.STUDENT_ID = EIGHT_DATA.STUDENT_ID
INNER JOIN NINE_ABSENCES_LATES_AVG_TOTAL NINE_ALAT ON NINE_ALC.STUDENT_ID = NINE_DATA.STUDENT_ID
INNER JOIN TEN_ABSENCES_LATES_AVG_TOTAL TEN_ALAT ON TEN_ALC.STUDENT_ID = TEN_DATA.STUDENT_ID
INNER JOIN ELEVEN_ABSENCES_LATES_AVG_TOTAL ELEVEN_ALAT ON ELEVEN_ALC.STUDENT_ID = ELEVEN_DATA.STUDENT_ID
INNER JOIN TWELVE_ABSENCES_LATES_AVG_TOTAL TWELVE_ALAT ON TWELVE_ALC.STUDENT_ID = TWELVE_DATA.STUDENT_ID

ORDER BY FORM_RUN, SURNAME