SELECT
  CLASS.CLASS,
  PERIOD.PERIOD,
  CONTACT.SURNAME,
  CONTACT.FIRSTNAME,
  (CASE WHEN CONTACT.PREFERRED_NAME IS NULL THEN NULL ELSE '(' END) || CONTACT.PREFERRED_NAME || (CASE WHEN CONTACT.PREFERRED_NAME IS NULL THEN NULL ELSE ')' END) AS "PREFERRED_NAME",
  GENDER.GENDER,
  ATS.ATTEND_STATUS

FROM LESSON

INNER JOIN PERIOD_CLASS PC ON PC.PERIOD_CLASS_ID = LESSON.PERIOD_CLASS_ID
INNER JOIN PERIOD_CYCLE_DAY PCD ON PCD.PERIOD_CYCLE_DAY_ID = PC.PERIOD_CYCLE_DAY_ID
INNER JOIN PERIOD ON PERIOD.PERIOD_ID = PCD.PERIOD_ID AND PERIOD.PERIOD = 'Home Room 1'

INNER JOIN CLASS ON CLASS.CLASS_ID = PC.CLASS_ID
INNER JOIN ATTENDANCE ON ATTENDANCE.LESSON_ID = LESSON.LESSON_ID
INNER JOIN ATTEND_STATUS ATS ON ATS.ATTEND_STATUS_ID = ATTENDANCE.ATTEND_STATUS_ID

INNER JOIN STUDENT ON STUDENT.STUDENT_ID = ATTENDANCE.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
INNER JOIN GENDER ON GENDER.GENDER_ID = CONTACT.GENDER_ID

WHERE DATE(DATE_ON) = DATE(CURRENT DATE)

ORDER BY CLASS.CLASS_ID, CONTACT.SURNAME