-- Co-Curricular Batch Rolls

-- Provides the Co-Curricular Coordinator and the Printery an easy way to produce pre-class and post-class rolls for all Co-Curricular groups for a given date.
-- Feeds to (attendance/co-curricular_batch-rolls.sxw)

WITH STUDENT_ATTENDANCE AS (
  SELECT
    DA.STUDENT_ID,
    DAS.DAILY_ATTENDANCE_STATUS

  FROM DAILY_ATTENDANCE DA
  
  INNER JOIN DAILY_ATTENDANCE_STATUS DAS ON DAS.DAILY_ATTENDANCE_STATUS_ID = DA.AM_ATTENDANCE_STATUS_ID

  WHERE
    DA.DATE_ON = ('[[As at=date]]')
    AND
    DA.AM_ATTENDANCE_STATUS_ID IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23)
),

CC_DATA AS (
  SELECT
    CCG.STUDENT_ID,
  	TO_CHAR(DATE(START_DATE), 'DD/MM/YYYY') AS "START_DATE",
  	TO_CHAR(DATE(END_DATE), 'DD/MM/YYYY') AS "END_DATE",
    TO_CHAR(DATE('[[As at=date]]'), 'DD/MM/YYYY') AS "TODAY",
  	TO_CHAR(DATE(CURRENT DATE), 'Month DD, YYYY - ') || CHAR(TIME(CURRENT TIMESTAMP),USA) AS "PRINT_DATE",
  	CCG.CLASS AS "CC_GROUP",
    COURSE.CODE || '.' || CLASS.IDENTIFIER AS "TIMETABLE_CODE",
  	(CASE WHEN CONTACT.PREFERRED_NAME IS NULL THEN CONTACT.FIRSTNAME ELSE CONTACT.PREFERRED_NAME END) AS "STUDENT_FIRSTNAME",
  	CONTACT.SURNAME AS "STUDENT_SURNAME",
  	SA.DAILY_ATTENDANCE_STATUS,
  	
  	/*
  	-- Hack to generate rooms for wet weather
    (CASE
      WHEN COURSE.CODE || ' ' || CLASS.IDENTIFIER = 'CRBAF 03I' THEN '16'
      WHEN COURSE.CODE || ' ' || CLASS.IDENTIFIER = 'CRBAF 03J' THEN '16'
      ELSE NULL
    END) AS "CC_ROOM"
  	*/
  	
  	NULL AS "CC_ROOM"

  FROM VIEW_STUDENT_CLASS_ENROLMENT CCG
  
  INNER JOIN STUDENT ON CCG.STUDENT_ID = STUDENT.STUDENT_ID
  INNER JOIN CONTACT ON STUDENT.CONTACT_ID = CONTACT.CONTACT_ID
  INNER JOIN STUDENT_ATTENDANCE SA ON SA.STUDENT_ID = CCG.STUDENT_ID
  INNER JOIN CLASS ON CLASS.CLASS_ID = CCG.CLASS_ID
  INNER JOIN COURSE ON COURSE.COURSE_ID = CLASS.COURSE_ID
  
  WHERE
  	ACADEMIC_YEAR = TO_CHAR((CURRENT DATE), 'YYYY')
    AND
    (START_DATE < (CURRENT DATE)
    AND
    END_DATE > (CURRENT DATE))
    AND
    -- Another hack to get around the issue of Co-Curricular classes set as 'Normal' instead of 'Co-curricular'
    COURSE.CODE || ' ' || CLASS.IDENTIFIER IN
    ('CRBTF 04I', 'CRBTF 04J', 'CRBTF 04S', 'CRBVB 04I', 'CRBVB 04J', 'CRBVB 04S', 'CRGSB 04I', 'CRGSB 04J', 'CRGTF 04I', 'CRGTF 04J', 'CRGVB 04S', 'CSALC 04A', 'CSART 04A', 'CSBSC 04A', 'CSCHL 04A', 'CSDAN 04A', 'CSDRB 04A', 'CSFTB 04A', 'CSFUT 04A', 'CSGYM 04A', 'CSHOZ 04A', 'CSLSC 04A', 'CSMCB 04A', 'CSNTF 04A', 'CSOFR 04A', 'CSOFR 04B', 'CSOHO 04A', 'CSOSC 04A', 'CSOZV 04A', 'CSPHO 04A', 'CSSAF 04A', 'CSSAF 04B', 'CSSCB 04A', 'CSSOZ 04A', 'CSSTF 04A', 'CSSTF 04B', 'CSSWI 04A', 'CSTAF 04A', 'CSTEN 04A', 'CSTEN 04B', 'CSTOZ 04A', 'CSTSC 04A', 'CSVOZ 04A', 'CSYOG 04A')
  ORDER BY CC_GROUP ASC, STUDENT_SURNAME ASC
)

SELECT
  CCD.TODAY,
  CCD.PRINT_DATE,
  CCD.CC_GROUP || '<br> Room: ' || CCD.CC_ROOM AS "CC_GROUP",
  CCD.TIMETABLE_CODE,
  CCD.STUDENT_FIRSTNAME,
  CCD.STUDENT_SURNAME,
  CCD.DAILY_ATTENDANCE_STATUS
  
FROM CC_DATA CCD