SELECT
	TO_CHAR((current date), 'Month DD, YYYY') as "TODAY_DATE",
	TO_CHAR((current date - 7 DAYS), 'Month DD, YYYY') as "REPORT_START",

	--Absences by gender, then form
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 07' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "07_BOYS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 07' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "07_GIRLS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 08' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "08_BOYS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 08' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "08_GIRLS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 09' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "09_BOYS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 09' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "09_GIRLS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 10' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "10_BOYS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 10' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "10_GIRLS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 11' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "11_BOYS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 11' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "11_GIRLS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 12' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "12_BOYS_ABSENCES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 12' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "12_GIRLS_ABSENCES",

	--Lates by gender, then form
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 07' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "07_BOYS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 07' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "07_GIRLS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 08' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "08_BOYS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 08' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "08_GIRLS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 09' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "09_BOYS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 09' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "09_GIRLS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 10' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "10_BOYS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 10' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "10_GIRLS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 11' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "11_BOYS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 11' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "11_GIRLS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 12' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "12_BOYS_LATES",
	COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 12' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "12_GIRLS_LATES",

	--Sub-totals of absences - boys
	COUNT(CASE WHEN GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "ALL_BOYS_ABSENCES",

	--Sub-totals of lates - boys
	COUNT(CASE WHEN GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "ALL_BOYS_LATES",

	--Sub-totals of absences - girls
	COUNT(CASE WHEN GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "ALL_GIRLS_ABSENCES",

	--Sub-totals of lates - girls
	COUNT(CASE WHEN GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "ALL_GIRLS_LATES",

	--Totals of absences and lates - boys
	COUNT(CASE WHEN GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) + COUNT(CASE WHEN GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "ALL_BOYS_ABSENCES_AND_LATES",

	--Totals of absences and lates - girls
	COUNT(CASE WHEN GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) + COUNT(CASE WHEN GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "ALL_GIRLS_ABSENCES_AND_LATES",

	--Grand-totals of absences
	COUNT(ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS) AS "ALL_ABSENCES",

	--Grand-totals of lates
	COUNT(ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS) AS "ALL_LATES"

FROM 
    TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT_DATE)) A

	INNER JOIN FORM_RUN ON A.FORM_RUN_ID = FORM_RUN.FORM_RUN_ID
    INNER JOIN STUDENT ON A.STUDENT_ID = STUDENT.STUDENT_ID
    INNER JOIN CONTACT ON STUDENT.CONTACT_ID = CONTACT.CONTACT_ID
    INNER JOIN GENDER ON CONTACT.GENDER_ID = GENDER.GENDER_ID

    INNER JOIN DAILY_ATTENDANCE ON A.STUDENT_ID = DAILY_ATTENDANCE.STUDENT_ID

    LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DAILY_ATTENDANCE.DAILY_ATTENDANCE_STATUS_ID
            AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS LIKE '%Absence%' AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS NOT LIKE '%Partial Absence%'
            AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID NOT IN (20,21,22,23,24,25,26,27)
			
    LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DAILY_ATTENDANCE.AM_ATTENDANCE_STATUS_ID
            AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS LIKE '%Late%'
   			AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID NOT IN (28,29,30,31)

WHERE
    DAILY_ATTENDANCE.DATE_ON >= (CURRENT_DATE - 7 DAYS)
    AND (ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS IS NOT NULL OR ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS IS NOT NULL)