/*
'A weekly summative report of attendance and lates for the school.'
To do: Counts, maybe period HR1 + HR2 only? Consult with Paul Hardwick
*/
WITH RAW_DATA AS
(
	SELECT
		STUDENT.STUDENT_ID,
		CONTACT.SURNAME,
		CONTACT.FIRSTNAME,
		CONTACT.GENDER_ID,
		FORM_RUN.FORM_RUN,
		DATE_ON,
		LATE_TIME_IN,
		ATTEND_STATUS_ID,
		CASE ABSENT_STATUS
		  WHEN 0 THEN 'Not absent/Unexplained'
		  WHEN 1 THEN 'Explained - Unverified'
		  WHEN 2 THEN 'Explained - Verified'
		  WHEN 3 THEN 'Explained - Verified (Sick)'
		  WHEN 4 THEN 'Explained - Verified (Suspended)'
		  WHEN 5 THEN 'Explained - Verified (Approved By Principal)'
		  WHEN 6 THEN 'Explained - Verified (School Business)'
		  WHEN 7 THEN 'Explained - Verified (Flexible Timetable)'
		  WHEN 8 THEN 'Explained - Verified (External Education)'
		  WHEN 9 THEN 'Explained - Verified (Exempt)'
		END AS "ABSENT_STATUS",
		PERIOD.PERIOD
	
	FROM VIEW_ATTENDANCE VATTEND
	
	INNER JOIN STUDENT ON STUDENT.STUDENT_ID = VATTEND.STUDENT_ID
	INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
	
	INNER JOIN TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(current_date)) GESF ON VATTEND.STUDENT_ID = GESF.STUDENT_ID
	INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = GESF.FORM_RUN_ID

	INNER JOIN PERIOD ON PERIOD.PERIOD_ID = VATTEND.PERIOD_ID AND PERIOD.PERIOD = 'Home Room 1'

)
/*
SELECT
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 2 THEN 1 ELSE null END) AS "BOYS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 2 THEN 1 ELSE null END) AS "BOYS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (3,4,5) AND GENDER_ID = 2 THEN 1 ELSE null END) AS "BOYS_TOTAL",
	
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 3 THEN 1 ELSE null END) AS "GIRLS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 3 THEN 1 ELSE null END) AS "GIRLS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (3,4,5) AND GENDER_ID = 3 THEN 1 ELSE null END) AS "GIRLS_TOTAL",

	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year %7' THEN 1 ELSE null END) AS "07_BOYS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year %7' THEN 1 ELSE null END) AS "07_BOYS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year %8' THEN 1 ELSE null END) AS "08_BOYS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year %8' THEN 1 ELSE null END) AS "08_BOYS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year %9' THEN 1 ELSE null END) AS "09_BOYS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year %9' THEN 1 ELSE null END) AS "09_BOYS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year 10' THEN 1 ELSE null END) AS "10_BOYS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year 10' THEN 1 ELSE null END) AS "10_BOYS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year 11' THEN 1 ELSE null END) AS "11_BOYS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year 11' THEN 1 ELSE null END) AS "11_BOYS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year 12' THEN 1 ELSE null END) AS "12_BOYS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 2 AND FORM_RUN LIKE '%%%% Year 12' THEN 1 ELSE null END) AS "12_BOYS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year %7' THEN 1 ELSE null END) AS "07_GIRLS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year %7' THEN 1 ELSE null END) AS "07_GIRLS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year %8' THEN 1 ELSE null END) AS "08_GIRLS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year %8' THEN 1 ELSE null END) AS "08_GIRLS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year %9' THEN 1 ELSE null END) AS "09_GIRLS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year %9' THEN 1 ELSE null END) AS "09_GIRLS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year 10' THEN 1 ELSE null END) AS "10_GIRLS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year 10' THEN 1 ELSE null END) AS "10_GIRLS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year 11' THEN 1 ELSE null END) AS "11_GIRLS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year 11' THEN 1 ELSE null END) AS "11_GIRLS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year 12' THEN 1 ELSE null END) AS "12_GIRLS_TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) AND GENDER_ID = 3 AND FORM_RUN LIKE '%%%% Year 12' THEN 1 ELSE null END) AS "12_GIRLS_TOTAL_LATES",
	COUNT(CASE WHEN ATTEND_STATUS_ID = 3 THEN 1 ELSE null END) AS "TOTAL_ABSENCES",
	COUNT(CASE WHEN ATTEND_STATUS_ID IN (4,5) THEN 1 ELSE null END) AS "TOTAL_LATES"

FROM RAW_DATA
*/
SELECT * FROM RAW_DATA
WHERE
	STUDENT_ID = 21349
		AND
	DATE_ON >= (CURRENT_DATE - 7 DAYS)
		AND
	ATTEND_STATUS_ID IN (3,4,5)
	
ORDER BY DATE_ON DESC