WITH SEVEN_EIGHT_NINE AS
(
  SELECT

  --Absences by gender, then form
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 07' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "07_BOYS_ABSENCES",
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 07' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "07_GIRLS_ABSENCES",
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 08' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "08_BOYS_ABSENCES",
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 08' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "08_GIRLS_ABSENCES",
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 09' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "09_BOYS_ABSENCES",
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 09' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS ELSE null END) AS "09_GIRLS_ABSENCES",

  --Lates by gender, then form
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 07' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "07_BOYS_LATES",
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 07' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "07_GIRLS_LATES",
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 08' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "08_BOYS_LATES",
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 08' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "08_GIRLS_LATES",
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 09' AND GENDER.GENDER_ID = 2 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "09_BOYS_LATES",
  COUNT(CASE WHEN FORM_RUN.FORM_RUN LIKE '%%%% Year 09' AND GENDER.GENDER_ID = 3 THEN ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS ELSE null END) AS "09_GIRLS_LATES"

  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT_DATE)) A
  
  INNER JOIN FORM_RUN ON A.FORM_RUN_ID = FORM_RUN.FORM_RUN_ID
  INNER JOIN STUDENT ON A.STUDENT_ID = STUDENT.STUDENT_ID
  INNER JOIN CONTACT ON STUDENT.CONTACT_ID = CONTACT.CONTACT_ID
  INNER JOIN GENDER ON CONTACT.GENDER_ID = GENDER.GENDER_ID

  INNER JOIN DAILY_ATTENDANCE ON A.STUDENT_ID = DAILY_ATTENDANCE.STUDENT_ID

  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_DAILY ON ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID = DAILY_ATTENDANCE.DAILY_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS LIKE '%Absence%' AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS NOT LIKE '%Partial Absence%'
    AND ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS_ID NOT IN (20,21,22,23,24,25,26,27)
    AND DAILY_ATTENDANCE.DATE_ON BETWEEN '2013-01-31' AND '2013-06-06'
      
  LEFT JOIN DAILY_ATTENDANCE_STATUS ATTENDANCE_STATUS_AM ON ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID = DAILY_ATTENDANCE.AM_ATTENDANCE_STATUS_ID
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS LIKE '%Late%'
    AND ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS_ID NOT IN (28,29,30,31)
    AND DAILY_ATTENDANCE.DATE_ON BETWEEN '2013-01-31' AND '2013-06-06'
  
  WHERE (ATTENDANCE_STATUS_DAILY.DAILY_ATTENDANCE_STATUS IS NOT NULL OR ATTENDANCE_STATUS_AM.DAILY_ATTENDANCE_STATUS IS NOT NULL)
)

SELECT
  '31/01/2013' AS "REPORT_START",
  '06/06/2013' AS "REPORT_END",
  "07_BOYS_ABSENCES",
  "07_GIRLS_ABSENCES",
  SUM("07_BOYS_ABSENCES"+"07_GIRLS_ABSENCES") AS "07_ABSENCES",
  "08_BOYS_ABSENCES",
  "08_GIRLS_ABSENCES",
  SUM("08_BOYS_ABSENCES"+"08_GIRLS_ABSENCES") AS "08_ABSENCES",
  "09_BOYS_ABSENCES",
  "09_GIRLS_ABSENCES",
  SUM("09_BOYS_ABSENCES"+"09_GIRLS_ABSENCES") AS "09_ABSENCES",
  "07_BOYS_LATES",
  "07_GIRLS_LATES",
  SUM("07_BOYS_LATES"+"07_GIRLS_LATES") AS "07_LATES",
  "08_BOYS_LATES",
  "08_GIRLS_LATES",
  SUM("08_BOYS_LATES"+"08_GIRLS_LATES") AS "08_LATES",
  "09_BOYS_LATES",
  "09_GIRLS_LATES",
  SUM("09_BOYS_LATES"+"09_GIRLS_LATES") AS "09_LATES",

  SUM("07_BOYS_ABSENCES"+"08_BOYS_ABSENCES"+"09_BOYS_ABSENCES") AS "ALL_BOYS_ABSENCES",
  SUM("07_BOYS_LATES"+"08_BOYS_LATES"+"09_BOYS_LATES") AS "ALL_BOYS_LATES",
  SUM("07_GIRLS_ABSENCES"+"08_GIRLS_ABSENCES"+"09_GIRLS_ABSENCES") AS "ALL_GIRLS_ABSENCES",
  SUM("07_GIRLS_LATES"+"08_GIRLS_LATES"+"09_GIRLS_LATES") AS "ALL_GIRLS_LATES",
  SUM("07_BOYS_ABSENCES"+"08_BOYS_ABSENCES"+"09_BOYS_ABSENCES"+"07_BOYS_LATES"+"08_BOYS_LATES"+"09_BOYS_LATES") AS "ALL_BOYS_ABSENCES_AND_LATES",
  SUM("07_GIRLS_ABSENCES"+"08_GIRLS_ABSENCES"+"09_GIRLS_ABSENCES"+"07_GIRLS_LATES"+"08_GIRLS_LATES"+"09_GIRLS_LATES") AS "ALL_GIRLS_ABSENCES_AND_LATES",
  SUM("07_BOYS_ABSENCES"+"08_BOYS_ABSENCES"+"09_BOYS_ABSENCES"+"07_GIRLS_ABSENCES"+"08_GIRLS_ABSENCES"+"09_GIRLS_ABSENCES") AS "ALL_ABSENCES",
  SUM("07_BOYS_LATES"+"08_BOYS_LATES"+"09_BOYS_LATES"+"07_GIRLS_LATES"+"08_GIRLS_LATES"+"09_GIRLS_LATES") AS "ALL_LATES"

FROM SEVEN_EIGHT_NINE

GROUP BY
  "07_BOYS_ABSENCES",
  "07_GIRLS_ABSENCES",
  "08_BOYS_ABSENCES",
  "08_GIRLS_ABSENCES",
  "09_BOYS_ABSENCES",
  "09_GIRLS_ABSENCES",
  "07_BOYS_LATES",
  "07_GIRLS_LATES",
  "08_BOYS_LATES",
  "08_GIRLS_LATES",
  "09_BOYS_LATES",
  "09_GIRLS_LATES"