-- Lists all classes with the type of 'NormalAssessmentOnly'.

SELECT
  CLASS.CLASS_ID,
  CLASS.CLASS,
  CLASS.CLASS_TYPE_ID,
  CLASS_TYPE.CLASS_TYPE

FROM CLASS

INNER JOIN CLASS_TYPE ON CLASS_TYPE.CLASS_TYPE_ID = CLASS.CLASS_TYPE_ID

WHERE CLASS.ACADEMIC_YEAR_ID = 45 AND CLASS.CLASS_TYPE_ID = 1 AND CLASS.CLASS LIKE '11%'

-- CLASS_TYPE_ID of 1028 is for 'NormalAssessmentOnly'
-- CLASS_TYPE_ID should be 1 for 'Normal'