UPDATE EDUMATE.HEARD_ABOUT_SCHOOL SET HEARD_ABOUT_SCHOOL = 'WPA' WHERE HEARD_ABOUT_SCHOOL_ID = 1;
UPDATE EDUMATE.HEARD_ABOUT_SCHOOL SET HEARD_ABOUT_SCHOOL = 'WPA3' WHERE HEARD_ABOUT_SCHOOL_ID = 2;
UPDATE EDUMATE.HEARD_ABOUT_SCHOOL SET HEARD_ABOUT_SCHOOL = 'WPA5' WHERE HEARD_ABOUT_SCHOOL_ID = 3;
UPDATE EDUMATE.HEARD_ABOUT_SCHOOL SET HEARD_ABOUT_SCHOOL = 'WCO' WHERE HEARD_ABOUT_SCHOOL_ID = 4;

DELETE FROM EDUMATE.HEARD_ABOUT_SCHOOL WHERE HEARD_ABOUT_SCHOOL_ID = 5;
DELETE FROM EDUMATE.HEARD_ABOUT_SCHOOL WHERE HEARD_ABOUT_SCHOOL_ID = 6;