-- Restores the original stock data contained in the 'HEARD_ABOUT_SCHOOL' table.
-- Note: Execute this with Ctrl + 3 when using RazorSQL

DELETE FROM EDUMATE.HEARD_ABOUT_SCHOOL WHERE HEARD_ABOUT_SCHOOL_ID = 1;
DELETE FROM EDUMATE.HEARD_ABOUT_SCHOOL WHERE HEARD_ABOUT_SCHOOL_ID = 2;
DELETE FROM EDUMATE.HEARD_ABOUT_SCHOOL WHERE HEARD_ABOUT_SCHOOL_ID = 3;
DELETE FROM EDUMATE.HEARD_ABOUT_SCHOOL WHERE HEARD_ABOUT_SCHOOL_ID = 4;

INSERT INTO EDUMATE.HEARD_ABOUT_SCHOOL(HEARD_ABOUT_SCHOOL_ID, HEARD_ABOUT_SCHOOL, LAST_UPDATED, SESSION_GENERATOR_ID) VALUES (1, 'Radio', '2012-03-15 16:57:02.014155', 0);
INSERT INTO EDUMATE.HEARD_ABOUT_SCHOOL(HEARD_ABOUT_SCHOOL_ID, HEARD_ABOUT_SCHOOL, LAST_UPDATED, SESSION_GENERATOR_ID) VALUES (2, 'Press', '2012-03-15 16:57:02.027622', 0);
INSERT INTO EDUMATE.HEARD_ABOUT_SCHOOL(HEARD_ABOUT_SCHOOL_ID, HEARD_ABOUT_SCHOOL, LAST_UPDATED, SESSION_GENERATOR_ID) VALUES (3, 'TV', '2012-03-15 16:57:02.036378', 0);
INSERT INTO EDUMATE.HEARD_ABOUT_SCHOOL(HEARD_ABOUT_SCHOOL_ID, HEARD_ABOUT_SCHOOL, LAST_UPDATED, SESSION_GENERATOR_ID) VALUES (4, 'Word of Mouth', '2012-03-15 16:57:02.044367', 0);
INSERT INTO EDUMATE.HEARD_ABOUT_SCHOOL(HEARD_ABOUT_SCHOOL_ID, HEARD_ABOUT_SCHOOL, LAST_UPDATED, SESSION_GENERATOR_ID) VALUES (5, 'Existing Family', '2012-03-15 16:57:02.052444', 0);
INSERT INTO EDUMATE.HEARD_ABOUT_SCHOOL(HEARD_ABOUT_SCHOOL_ID, HEARD_ABOUT_SCHOOL, LAST_UPDATED, SESSION_GENERATOR_ID) VALUES (6, 'Other', '2012-03-15 16:57:02.060573', 0);