WITH REPORT_VARS AS (
  SELECT
    (SELECT DATE_RANGE FROM TABLE(DB2INST1.DATE_RANGE((CURRENT DATE - 1 DAY), (CURRENT DATE + 10 DAYS))) WHERE ROWNUM = 1) AS "DAY01",
    (SELECT DATE_RANGE FROM TABLE(DB2INST1.DATE_RANGE((CURRENT DATE - 1 DAY), (CURRENT DATE + 10 DAYS))) WHERE ROWNUM = 2) AS "DAY02",
    (SELECT DATE_RANGE FROM TABLE(DB2INST1.DATE_RANGE((CURRENT DATE - 1 DAY), (CURRENT DATE + 10 DAYS))) WHERE ROWNUM = 3) AS "DAY03",
    (SELECT DATE_RANGE FROM TABLE(DB2INST1.DATE_RANGE((CURRENT DATE - 1 DAY), (CURRENT DATE + 10 DAYS))) WHERE ROWNUM = 4) AS "DAY04",
    (SELECT DATE_RANGE FROM TABLE(DB2INST1.DATE_RANGE((CURRENT DATE - 1 DAY), (CURRENT DATE + 10 DAYS))) WHERE ROWNUM = 5) AS "DAY05",
    (SELECT DATE_RANGE FROM TABLE(DB2INST1.DATE_RANGE((CURRENT DATE - 1 DAY), (CURRENT DATE + 10 DAYS))) WHERE ROWNUM = 6) AS "DAY06",
    (SELECT DATE_RANGE FROM TABLE(DB2INST1.DATE_RANGE((CURRENT DATE - 1 DAY), (CURRENT DATE + 10 DAYS))) WHERE ROWNUM = 7) AS "DAY07",
    (SELECT DATE_RANGE FROM TABLE(DB2INST1.DATE_RANGE((CURRENT DATE - 1 DAY), (CURRENT DATE + 10 DAYS))) WHERE ROWNUM = 8) AS "DAY08",
    (SELECT DATE_RANGE FROM TABLE(DB2INST1.DATE_RANGE((CURRENT DATE - 1 DAY), (CURRENT DATE + 10 DAYS))) WHERE ROWNUM = 9) AS "DAY09",
    (SELECT DATE_RANGE FROM TABLE(DB2INST1.DATE_RANGE((CURRENT DATE - 1 DAY), (CURRENT DATE + 10 DAYS))) WHERE ROWNUM = 10) AS "DAY10"
  FROM SYSIBM.SYSDUMMY1
),

TERMS AS (
  SELECT DISTINCT TERM.TERM_ID, TIMETABLE.TIMETABLE
  FROM TABLE(EDUMATE.GET_TIMETABLE_CYCLE_DAY_DATE(
    (SELECT DAY01 FROM REPORT_VARS),
    (SELECT DAY10 FROM REPORT_VARS)
    )
  ) TT

  INNER JOIN TIMETABLE ON TIMETABLE.TIMETABLE_ID = TT.TIMETABLE_ID
  INNER JOIN TERM ON TERM.TIMETABLE_ID = TT.TIMETABLE_ID AND TERM.TERM = 'Term 4'
  WHERE TIMETABLE NOT IN ('2013 Year 11', '2013 Year 12')
),

STUDENT_DATA AS (
  SELECT
    S.STUDENT_ID,
    FORM_RUN.FORM_RUN,
    (CASE
      WHEN FORM_RUN.FORM_RUN LIKE '% Year 0%'
        THEN (SELECT TERMS.TERM_ID FROM TERMS WHERE TERMS.TIMETABLE LIKE '% Year 7-10')
      WHEN FORM_RUN.FORM_RUN LIKE '% Year 10'
        THEN (SELECT TERMS.TERM_ID FROM TERMS WHERE TERMS.TIMETABLE LIKE '% Year 7-10')
      WHEN FORM_RUN.FORM_RUN = '2014 Year 12'
        THEN (SELECT TERM_ID FROM TERM WHERE START_DATE = DATE('2013-10-21'))
      ELSE NULL
    END) AS "TERM_ID"
  FROM TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN((SELECT DAY01 FROM REPORT_VARS))) S
  INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = S.FORM_RUN_ID AND FORM_RUN.FORM_RUN NOT IN ('2013 Year 11', '2013 Year 12')
),

DAY01_TIMETABLE AS (
  SELECT
    (SELECT DAY01 FROM REPORT_VARS) AS "DAY",
    (SELECT CYCLE_DAY_ID FROM TABLE(EDUMATE.GETCYCLEDAYID((SD.TERM_ID), (SELECT DAY01 FROM REPORT_VARS)))) AS "DAY_INDEX",
    STUDENT.STUDENT_NUMBER,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SD.FORM_RUN,
    GSPC.CLASS,
    CT.TEACHER_FORMAL AS "TEACHER",
    GSPC.ROOM,
    GSPC.PERIOD,
    GSPC.PERIOD_ID
    
  FROM STUDENT_DATA SD
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = SD.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN TABLE(EDUMATE.GET_STUDENT_PERIOD_CLASSES(
      (SD.STUDENT_ID),
      (SELECT DAY01 FROM REPORT_VARS),
      (CASE WHEN SD.FORM_RUN = '2014 Year 12' THEN
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2014)
      ELSE
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2013)
      END
      ),
      (SD.TERM_ID),
      NULL)
    ) GSPC
  INNER JOIN VIEW_STUDENT_CLASS_TEACHERS CT ON CT.CLASS_ID = GSPC.CLASS_ID
),

DAY02_TIMETABLE AS (
  SELECT
    (SELECT DAY02 FROM REPORT_VARS) AS "DAY",
    (SELECT CYCLE_DAY_ID FROM TABLE(EDUMATE.GETCYCLEDAYID((SD.TERM_ID), (SELECT DAY02 FROM REPORT_VARS)))) AS "DAY_INDEX",
    STUDENT.STUDENT_NUMBER,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SD.FORM_RUN,
    GSPC.CLASS,
    CT.TEACHER_FORMAL AS "TEACHER",
    GSPC.ROOM,
    GSPC.PERIOD,
    GSPC.PERIOD_ID
    
  FROM STUDENT_DATA SD
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = SD.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN TABLE(EDUMATE.GET_STUDENT_PERIOD_CLASSES(
      (SD.STUDENT_ID),
      (SELECT DAY02 FROM REPORT_VARS),
      (CASE WHEN SD.FORM_RUN = '2014 Year 12' THEN
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2014)
      ELSE
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2013)
      END
      ),
      (SD.TERM_ID),
      NULL)
    ) GSPC
  INNER JOIN VIEW_STUDENT_CLASS_TEACHERS CT ON CT.CLASS_ID = GSPC.CLASS_ID
),

DAY03_TIMETABLE AS (
  SELECT
    (SELECT DAY03 FROM REPORT_VARS) AS "DAY",
    (SELECT CYCLE_DAY_ID FROM TABLE(EDUMATE.GETCYCLEDAYID((SD.TERM_ID), (SELECT DAY03 FROM REPORT_VARS)))) AS "DAY_INDEX",
    STUDENT.STUDENT_NUMBER,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SD.FORM_RUN,
    GSPC.CLASS,
    CT.TEACHER_FORMAL AS "TEACHER",
    GSPC.ROOM,
    GSPC.PERIOD,
    GSPC.PERIOD_ID
    
  FROM STUDENT_DATA SD
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = SD.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN TABLE(EDUMATE.GET_STUDENT_PERIOD_CLASSES(
      (SD.STUDENT_ID),
      (SELECT DAY03 FROM REPORT_VARS),
      (CASE WHEN SD.FORM_RUN = '2014 Year 12' THEN
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2014)
      ELSE
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2013)
      END
      ),
      (SD.TERM_ID),
      NULL)
    ) GSPC
  INNER JOIN VIEW_STUDENT_CLASS_TEACHERS CT ON CT.CLASS_ID = GSPC.CLASS_ID
),

DAY04_TIMETABLE AS (
  SELECT
    (SELECT DAY04 FROM REPORT_VARS) AS "DAY",
    (SELECT CYCLE_DAY_ID FROM TABLE(EDUMATE.GETCYCLEDAYID((SD.TERM_ID), (SELECT DAY04 FROM REPORT_VARS)))) AS "DAY_INDEX",
    STUDENT.STUDENT_NUMBER,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SD.FORM_RUN,
    GSPC.CLASS,
    CT.TEACHER_FORMAL AS "TEACHER",
    GSPC.ROOM,
    GSPC.PERIOD,
    GSPC.PERIOD_ID
    
  FROM STUDENT_DATA SD
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = SD.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN TABLE(EDUMATE.GET_STUDENT_PERIOD_CLASSES(
      (SD.STUDENT_ID),
      (SELECT DAY04 FROM REPORT_VARS),
      (CASE WHEN SD.FORM_RUN = '2014 Year 12' THEN
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2014)
      ELSE
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2013)
      END
      ),
      (SD.TERM_ID),
      NULL)
    ) GSPC
  INNER JOIN VIEW_STUDENT_CLASS_TEACHERS CT ON CT.CLASS_ID = GSPC.CLASS_ID
),

DAY05_TIMETABLE AS (
  SELECT
    (SELECT DAY05 FROM REPORT_VARS) AS "DAY",
    (SELECT CYCLE_DAY_ID FROM TABLE(EDUMATE.GETCYCLEDAYID((SD.TERM_ID), (SELECT DAY05 FROM REPORT_VARS)))) AS "DAY_INDEX",
    STUDENT.STUDENT_NUMBER,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SD.FORM_RUN,
    GSPC.CLASS,
    CT.TEACHER_FORMAL AS "TEACHER",
    GSPC.ROOM,
    GSPC.PERIOD,
    GSPC.PERIOD_ID
    
  FROM STUDENT_DATA SD
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = SD.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN TABLE(EDUMATE.GET_STUDENT_PERIOD_CLASSES(
      (SD.STUDENT_ID),
      (SELECT DAY05 FROM REPORT_VARS),
      (CASE WHEN SD.FORM_RUN = '2014 Year 12' THEN
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2014)
      ELSE
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2013)
      END
      ),
      (SD.TERM_ID),
      NULL)
    ) GSPC
  INNER JOIN VIEW_STUDENT_CLASS_TEACHERS CT ON CT.CLASS_ID = GSPC.CLASS_ID
),

DAY06_TIMETABLE AS (
  SELECT
    (SELECT DAY06 FROM REPORT_VARS) AS "DAY",
    (SELECT CYCLE_DAY_ID FROM TABLE(EDUMATE.GETCYCLEDAYID((SD.TERM_ID), (SELECT DAY06 FROM REPORT_VARS)))) AS "DAY_INDEX",
    STUDENT.STUDENT_NUMBER,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SD.FORM_RUN,
    GSPC.CLASS,
    CT.TEACHER_FORMAL AS "TEACHER",
    GSPC.ROOM,
    GSPC.PERIOD,
    GSPC.PERIOD_ID
    
  FROM STUDENT_DATA SD
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = SD.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN TABLE(EDUMATE.GET_STUDENT_PERIOD_CLASSES(
      (SD.STUDENT_ID),
      (SELECT DAY06 FROM REPORT_VARS),
      (CASE WHEN SD.FORM_RUN = '2014 Year 12' THEN
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2014)
      ELSE
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2013)
      END
      ),
      (SD.TERM_ID),
      NULL)
    ) GSPC
  INNER JOIN VIEW_STUDENT_CLASS_TEACHERS CT ON CT.CLASS_ID = GSPC.CLASS_ID
),

DAY07_TIMETABLE AS (
  SELECT
    (SELECT DAY07 FROM REPORT_VARS) AS "DAY",
    (SELECT CYCLE_DAY_ID FROM TABLE(EDUMATE.GETCYCLEDAYID((SD.TERM_ID), (SELECT DAY07 FROM REPORT_VARS)))) AS "DAY_INDEX",
    STUDENT.STUDENT_NUMBER,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SD.FORM_RUN,
    GSPC.CLASS,
    CT.TEACHER_FORMAL AS "TEACHER",
    GSPC.ROOM,
    GSPC.PERIOD,
    GSPC.PERIOD_ID
    
  FROM STUDENT_DATA SD
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = SD.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN TABLE(EDUMATE.GET_STUDENT_PERIOD_CLASSES(
      (SD.STUDENT_ID),
      (SELECT DAY07 FROM REPORT_VARS),
      (CASE WHEN SD.FORM_RUN = '2014 Year 12' THEN
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2014)
      ELSE
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2013)
      END
      ),
      (SD.TERM_ID),
      NULL)
    ) GSPC
  INNER JOIN VIEW_STUDENT_CLASS_TEACHERS CT ON CT.CLASS_ID = GSPC.CLASS_ID
),

DAY08_TIMETABLE AS (
  SELECT
    (SELECT DAY08 FROM REPORT_VARS) AS "DAY",
    (SELECT CYCLE_DAY_ID FROM TABLE(EDUMATE.GETCYCLEDAYID((SD.TERM_ID), (SELECT DAY08 FROM REPORT_VARS)))) AS "DAY_INDEX",
    STUDENT.STUDENT_NUMBER,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SD.FORM_RUN,
    GSPC.CLASS,
    CT.TEACHER_FORMAL AS "TEACHER",
    GSPC.ROOM,
    GSPC.PERIOD,
    GSPC.PERIOD_ID
    
  FROM STUDENT_DATA SD
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = SD.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN TABLE(EDUMATE.GET_STUDENT_PERIOD_CLASSES(
      (SD.STUDENT_ID),
      (SELECT DAY08 FROM REPORT_VARS),
      (CASE WHEN SD.FORM_RUN = '2014 Year 12' THEN
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2014)
      ELSE
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2013)
      END
      ),
      (SD.TERM_ID),
      NULL)
    ) GSPC
  INNER JOIN VIEW_STUDENT_CLASS_TEACHERS CT ON CT.CLASS_ID = GSPC.CLASS_ID
),

DAY09_TIMETABLE AS (
  SELECT
    (SELECT DAY09 FROM REPORT_VARS) AS "DAY",
    (SELECT CYCLE_DAY_ID FROM TABLE(EDUMATE.GETCYCLEDAYID((SD.TERM_ID), (SELECT DAY09 FROM REPORT_VARS)))) AS "DAY_INDEX",
    STUDENT.STUDENT_NUMBER,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SD.FORM_RUN,
    GSPC.CLASS,
    CT.TEACHER_FORMAL AS "TEACHER",
    GSPC.ROOM,
    GSPC.PERIOD,
    GSPC.PERIOD_ID
    
  FROM STUDENT_DATA SD
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = SD.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN TABLE(EDUMATE.GET_STUDENT_PERIOD_CLASSES(
      (SD.STUDENT_ID),
      (SELECT DAY09 FROM REPORT_VARS),
      (CASE WHEN SD.FORM_RUN = '2014 Year 12' THEN
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2014)
      ELSE
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2013)
      END
      ),
      (SD.TERM_ID),
      NULL)
    ) GSPC
  INNER JOIN VIEW_STUDENT_CLASS_TEACHERS CT ON CT.CLASS_ID = GSPC.CLASS_ID
),

DAY10_TIMETABLE AS (
  SELECT
    (SELECT DAY10 FROM REPORT_VARS) AS "DAY",
    (SELECT CYCLE_DAY_ID FROM TABLE(EDUMATE.GETCYCLEDAYID((SD.TERM_ID), (SELECT DAY10 FROM REPORT_VARS)))) AS "DAY_INDEX",
    STUDENT.STUDENT_NUMBER,
    CONTACT.FIRSTNAME,
    CONTACT.SURNAME,
    SD.FORM_RUN,
    GSPC.CLASS,
    CT.TEACHER_FORMAL AS "TEACHER",
    GSPC.ROOM,
    GSPC.PERIOD,
    GSPC.PERIOD_ID
    
  FROM STUDENT_DATA SD
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = SD.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN TABLE(EDUMATE.GET_STUDENT_PERIOD_CLASSES(
      (SD.STUDENT_ID),
      (SELECT DAY10 FROM REPORT_VARS),
      (CASE WHEN SD.FORM_RUN = '2014 Year 12' THEN
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2014)
      ELSE
        (SELECT ACADEMIC_YEAR_ID FROM ACADEMIC_YEAR WHERE ACADEMIC_YEAR = 2013)
      END
      ),
      (SD.TERM_ID),
      NULL)
    ) GSPC
  INNER JOIN VIEW_STUDENT_CLASS_TEACHERS CT ON CT.CLASS_ID = GSPC.CLASS_ID
),

FULL_CYCLE AS (
  SELECT * FROM DAY01_TIMETABLE
  UNION
  SELECT * FROM DAY02_TIMETABLE
  UNION
  SELECT * FROM DAY03_TIMETABLE
  UNION
  SELECT * FROM DAY04_TIMETABLE
  UNION
  SELECT * FROM DAY05_TIMETABLE
  UNION
  SELECT * FROM DAY06_TIMETABLE
  UNION
  SELECT * FROM DAY07_TIMETABLE
  UNION
  SELECT * FROM DAY08_TIMETABLE
  UNION
  SELECT * FROM DAY09_TIMETABLE
  UNION
  SELECT * FROM DAY10_TIMETABLE
),

CURRENT_STUDENTS AS (
  SELECT DISTINCT STUDENT_NUMBER, FORM_RUN FROM FULL_CYCLE
)

SELECT
  CS.STUDENT_NUMBER,
  CS.FORM_RUN,
  -- Monday A Columns
  MON_A_BS1.CLASS AS "MON_A_BS1_CLASS",
  MON_A_BS1.ROOM AS "MON_A_BS1_ROOM",
  MON_A_BS1.TEACHER AS "MON_A_BS1_TEACHER",
  MON_A_BS2.CLASS AS "MON_A_BS2_CLASS",
  MON_A_BS2.ROOM AS "MON_A_BS2_ROOM",
  MON_A_BS2.TEACHER AS "MON_A_BS2_TEACHER",
  MON_A_HR1.CLASS AS "MON_A_HR1_CLASS",
  MON_A_HR1.ROOM AS "MON_A_HR1_ROOM",
  MON_A_HR1.TEACHER AS "MON_A_HR1_TEACHER",
  MON_A_P1.CLASS AS "MON_A_P1_CLASS",
  MON_A_P1.ROOM AS "MON_A_P1_ROOM",
  MON_A_P1.TEACHER AS "MON_A_P1_TEACHER",
  MON_A_P2.CLASS AS "MON_A_P2_CLASS",
  MON_A_P2.ROOM AS "MON_A_P2_ROOM",
  MON_A_P2.TEACHER AS "MON_A_P2_TEACHER",
  MON_A_P3.CLASS AS "MON_A_P3_CLASS",
  MON_A_P3.ROOM AS "MON_A_P3_ROOM",
  MON_A_P3.TEACHER AS "MON_A_P3_TEACHER",
  MON_A_P4.CLASS AS "MON_A_P4_CLASS",
  MON_A_P4.ROOM AS "MON_A_P4_ROOM",
  MON_A_P4.TEACHER AS "MON_A_P4_TEACHER",
  MON_A_P5.CLASS AS "MON_A_P5_CLASS",
  MON_A_P5.ROOM AS "MON_A_P5_ROOM",
  MON_A_P5.TEACHER AS "MON_A_P5_TEACHER",
  MON_A_P6.CLASS AS "MON_A_P6_CLASS",
  MON_A_P6.ROOM AS "MON_A_P6_ROOM",
  MON_A_P6.TEACHER AS "MON_A_P6_TEACHER",
  MON_A_P7.CLASS AS "MON_A_P7_CLASS",
  MON_A_P7.ROOM AS "MON_A_P7_ROOM",
  MON_A_P7.TEACHER AS "MON_A_P7_TEACHER",
  -- Tuesday A Columns
  TUE_A_BS1.CLASS AS "TUE_A_BS1_CLASS",
  TUE_A_BS1.ROOM AS "TUE_A_BS1_ROOM",
  TUE_A_BS1.TEACHER AS "TUE_A_BS1_TEACHER",
  TUE_A_BS2.CLASS AS "TUE_A_BS2_CLASS",
  TUE_A_BS2.ROOM AS "TUE_A_BS2_ROOM",
  TUE_A_BS2.TEACHER AS "TUE_A_BS2_TEACHER",
  TUE_A_HR1.CLASS AS "TUE_A_HR1_CLASS",
  TUE_A_HR1.ROOM AS "TUE_A_HR1_ROOM",
  TUE_A_HR1.TEACHER AS "TUE_A_HR1_TEACHER",
  TUE_A_P1.CLASS AS "TUE_A_P1_CLASS",
  TUE_A_P1.ROOM AS "TUE_A_P1_ROOM",
  TUE_A_P1.TEACHER AS "TUE_A_P1_TEACHER",
  TUE_A_P2.CLASS AS "TUE_A_P2_CLASS",
  TUE_A_P2.ROOM AS "TUE_A_P2_ROOM",
  TUE_A_P2.TEACHER AS "TUE_A_P2_TEACHER",
  TUE_A_P3.CLASS AS "TUE_A_P3_CLASS",
  TUE_A_P3.ROOM AS "TUE_A_P3_ROOM",
  TUE_A_P3.TEACHER AS "TUE_A_P3_TEACHER",
  TUE_A_P4.CLASS AS "TUE_A_P4_CLASS",
  TUE_A_P4.ROOM AS "TUE_A_P4_ROOM",
  TUE_A_P4.TEACHER AS "TUE_A_P4_TEACHER",
  TUE_A_P5.CLASS AS "TUE_A_P5_CLASS",
  TUE_A_P5.ROOM AS "TUE_A_P5_ROOM",
  TUE_A_P5.TEACHER AS "TUE_A_P5_TEACHER",
  TUE_A_P6.CLASS AS "TUE_A_P6_CLASS",
  TUE_A_P6.ROOM AS "TUE_A_P6_ROOM",
  TUE_A_P6.TEACHER AS "TUE_A_P6_TEACHER",
  TUE_A_P7.CLASS AS "TUE_A_P7_CLASS",
  TUE_A_P7.ROOM AS "TUE_A_P7_ROOM",
  TUE_A_P7.TEACHER AS "TUE_A_P7_TEACHER",
  -- Wednesday A Columns
  WED_A_BS1.CLASS AS "WED_A_BS1_CLASS",
  WED_A_BS1.ROOM AS "WED_A_BS1_ROOM",
  WED_A_BS1.TEACHER AS "WED_A_BS1_TEACHER",
  WED_A_BS2.CLASS AS "WED_A_BS2_CLASS",
  WED_A_BS2.ROOM AS "WED_A_BS2_ROOM",
  WED_A_BS2.TEACHER AS "WED_A_BS2_TEACHER",
  WED_A_HR1.CLASS AS "WED_A_HR1_CLASS",
  WED_A_HR1.ROOM AS "WED_A_HR1_ROOM",
  WED_A_HR1.TEACHER AS "WED_A_HR1_TEACHER",
  WED_A_P1.CLASS AS "WED_A_P1_CLASS",
  WED_A_P1.ROOM AS "WED_A_P1_ROOM",
  WED_A_P1.TEACHER AS "WED_A_P1_TEACHER",
  WED_A_P2.CLASS AS "WED_A_P2_CLASS",
  WED_A_P2.ROOM AS "WED_A_P2_ROOM",
  WED_A_P2.TEACHER AS "WED_A_P2_TEACHER",
  WED_A_P3.CLASS AS "WED_A_P3_CLASS",
  WED_A_P3.ROOM AS "WED_A_P3_ROOM",
  WED_A_P3.TEACHER AS "WED_A_P3_TEACHER",
  WED_A_P4.CLASS AS "WED_A_P4_CLASS",
  WED_A_P4.ROOM AS "WED_A_P4_ROOM",
  WED_A_P4.TEACHER AS "WED_A_P4_TEACHER",
  WED_A_P5.CLASS AS "WED_A_P5_CLASS",
  WED_A_P5.ROOM AS "WED_A_P5_ROOM",
  WED_A_P5.TEACHER AS "WED_A_P5_TEACHER",
  WED_A_P6.CLASS AS "WED_A_P6_CLASS",
  WED_A_P6.ROOM AS "WED_A_P6_ROOM",
  WED_A_P6.TEACHER AS "WED_A_P6_TEACHER",
  WED_A_P7.CLASS AS "WED_A_P7_CLASS",
  WED_A_P7.ROOM AS "WED_A_P7_ROOM",
  WED_A_P7.TEACHER AS "WED_A_P7_TEACHER",
  -- Thursday A Columns
  THU_A_BS1.CLASS AS "THU_A_BS1_CLASS",
  THU_A_BS1.ROOM AS "THU_A_BS1_ROOM",
  THU_A_BS1.TEACHER AS "THU_A_BS1_TEACHER",
  THU_A_BS2.CLASS AS "THU_A_BS2_CLASS",
  THU_A_BS2.ROOM AS "THU_A_BS2_ROOM",
  THU_A_BS2.TEACHER AS "THU_A_BS2_TEACHER",
  THU_A_HR1.CLASS AS "THU_A_HR1_CLASS",
  THU_A_HR1.ROOM AS "THU_A_HR1_ROOM",
  THU_A_HR1.TEACHER AS "THU_A_HR1_TEACHER",
  THU_A_P1.CLASS AS "THU_A_P1_CLASS",
  THU_A_P1.ROOM AS "THU_A_P1_ROOM",
  THU_A_P1.TEACHER AS "THU_A_P1_TEACHER",
  THU_A_P2.CLASS AS "THU_A_P2_CLASS",
  THU_A_P2.ROOM AS "THU_A_P2_ROOM",
  THU_A_P2.TEACHER AS "THU_A_P2_TEACHER",
  THU_A_P3.CLASS AS "THU_A_P3_CLASS",
  THU_A_P3.ROOM AS "THU_A_P3_ROOM",
  THU_A_P3.TEACHER AS "THU_A_P3_TEACHER",
  THU_A_P4.CLASS AS "THU_A_P4_CLASS",
  THU_A_P4.ROOM AS "THU_A_P4_ROOM",
  THU_A_P4.TEACHER AS "THU_A_P4_TEACHER",
  THU_A_P5.CLASS AS "THU_A_P5_CLASS",
  THU_A_P5.ROOM AS "THU_A_P5_ROOM",
  THU_A_P5.TEACHER AS "THU_A_P5_TEACHER",
  THU_A_CC.CLASS AS "THU_A_CC_CLASS",
  THU_A_CC.ROOM AS "THU_A_CC_ROOM",
  THU_A_CC.TEACHER AS "THU_A_CC_TEACHER",
  THU_A_P7.CLASS AS "THU_A_P7_CLASS",
  THU_A_P7.ROOM AS "THU_A_P7_ROOM",
  THU_A_P7.TEACHER AS "THU_A_P7_TEACHER",
  -- Friday A Columns
  FRI_A_BS1.CLASS AS "FRI_A_BS1_CLASS",
  FRI_A_BS1.ROOM AS "FRI_A_BS1_ROOM",
  FRI_A_BS1.TEACHER AS "FRI_A_BS1_TEACHER",
  FRI_A_BS2.CLASS AS "FRI_A_BS2_CLASS",
  FRI_A_BS2.ROOM AS "FRI_A_BS2_ROOM",
  FRI_A_BS2.TEACHER AS "FRI_A_BS2_TEACHER",
  FRI_A_HR1.CLASS AS "FRI_A_HR1_CLASS",
  FRI_A_HR1.ROOM AS "FRI_A_HR1_ROOM",
  FRI_A_HR1.TEACHER AS "FRI_A_HR1_TEACHER",
  FRI_A_P1.CLASS AS "FRI_A_P1_CLASS",
  FRI_A_P1.ROOM AS "FRI_A_P1_ROOM",
  FRI_A_P1.TEACHER AS "FRI_A_P1_TEACHER",
  FRI_A_P2.CLASS AS "FRI_A_P2_CLASS",
  FRI_A_P2.ROOM AS "FRI_A_P2_ROOM",
  FRI_A_P2.TEACHER AS "FRI_A_P2_TEACHER",
  FRI_A_P3.CLASS AS "FRI_A_P3_CLASS",
  FRI_A_P3.ROOM AS "FRI_A_P3_ROOM",
  FRI_A_P3.TEACHER AS "FRI_A_P3_TEACHER",
  FRI_A_P4.CLASS AS "FRI_A_P4_CLASS",
  FRI_A_P4.ROOM AS "FRI_A_P4_ROOM",
  FRI_A_P4.TEACHER AS "FRI_A_P4_TEACHER",
  FRI_A_P5.CLASS AS "FRI_A_P5_CLASS",
  FRI_A_P5.ROOM AS "FRI_A_P5_ROOM",
  FRI_A_P5.TEACHER AS "FRI_A_P5_TEACHER",
  FRI_A_P6.CLASS AS "FRI_A_P6_CLASS",
  FRI_A_P6.ROOM AS "FRI_A_P6_ROOM",
  FRI_A_P6.TEACHER AS "FRI_A_P6_TEACHER",
  FRI_A_P7.CLASS AS "FRI_A_P7_CLASS",
  FRI_A_P7.ROOM AS "FRI_A_P7_ROOM",
  FRI_A_P7.TEACHER AS "FRI_A_P7_TEACHER",
  -- Monday B Columns
  MON_B_BS1.CLASS AS "MON_B_BS1_CLASS",
  MON_B_BS1.ROOM AS "MON_B_BS1_ROOM",
  MON_B_BS1.TEACHER AS "MON_B_BS1_TEACHER",
  MON_B_BS2.CLASS AS "MON_B_BS2_CLASS",
  MON_B_BS2.ROOM AS "MON_B_BS2_ROOM",
  MON_B_BS2.TEACHER AS "MON_B_BS2_TEACHER",
  MON_B_HR1.CLASS AS "MON_B_HR1_CLASS",
  MON_B_HR1.ROOM AS "MON_B_HR1_ROOM",
  MON_B_HR1.TEACHER AS "MON_B_HR1_TEACHER",
  MON_B_P1.CLASS AS "MON_B_P1_CLASS",
  MON_B_P1.ROOM AS "MON_B_P1_ROOM",
  MON_B_P1.TEACHER AS "MON_B_P1_TEACHER",
  MON_B_P2.CLASS AS "MON_B_P2_CLASS",
  MON_B_P2.ROOM AS "MON_B_P2_ROOM",
  MON_B_P2.TEACHER AS "MON_B_P2_TEACHER",
  MON_B_P3.CLASS AS "MON_B_P3_CLASS",
  MON_B_P3.ROOM AS "MON_B_P3_ROOM",
  MON_B_P3.TEACHER AS "MON_B_P3_TEACHER",
  MON_B_P4.CLASS AS "MON_B_P4_CLASS",
  MON_B_P4.ROOM AS "MON_B_P4_ROOM",
  MON_B_P4.TEACHER AS "MON_B_P4_TEACHER",
  MON_B_P5.CLASS AS "MON_B_P5_CLASS",
  MON_B_P5.ROOM AS "MON_B_P5_ROOM",
  MON_B_P5.TEACHER AS "MON_B_P5_TEACHER",
  MON_B_P6.CLASS AS "MON_B_P6_CLASS",
  MON_B_P6.ROOM AS "MON_B_P6_ROOM",
  MON_B_P6.TEACHER AS "MON_B_P6_TEACHER",
  MON_B_P7.CLASS AS "MON_B_P7_CLASS",
  MON_B_P7.ROOM AS "MON_B_P7_ROOM",
  MON_B_P7.TEACHER AS "MON_B_P7_TEACHER",
  -- Tuesday B Columns
  TUE_B_BS1.CLASS AS "TUE_B_BS1_CLASS",
  TUE_B_BS1.ROOM AS "TUE_B_BS1_ROOM",
  TUE_B_BS1.TEACHER AS "TUE_B_BS1_TEACHER",
  TUE_B_BS2.CLASS AS "TUE_B_BS2_CLASS",
  TUE_B_BS2.ROOM AS "TUE_B_BS2_ROOM",
  TUE_B_BS2.TEACHER AS "TUE_B_BS2_TEACHER",
  TUE_B_HR1.CLASS AS "TUE_B_HR1_CLASS",
  TUE_B_HR1.ROOM AS "TUE_B_HR1_ROOM",
  TUE_B_HR1.TEACHER AS "TUE_B_HR1_TEACHER",
  TUE_B_P1.CLASS AS "TUE_B_P1_CLASS",
  TUE_B_P1.ROOM AS "TUE_B_P1_ROOM",
  TUE_B_P1.TEACHER AS "TUE_B_P1_TEACHER",
  TUE_B_P2.CLASS AS "TUE_B_P2_CLASS",
  TUE_B_P2.ROOM AS "TUE_B_P2_ROOM",
  TUE_B_P2.TEACHER AS "TUE_B_P2_TEACHER",
  TUE_B_P3.CLASS AS "TUE_B_P3_CLASS",
  TUE_B_P3.ROOM AS "TUE_B_P3_ROOM",
  TUE_B_P3.TEACHER AS "TUE_B_P3_TEACHER",
  TUE_B_P4.CLASS AS "TUE_B_P4_CLASS",
  TUE_B_P4.ROOM AS "TUE_B_P4_ROOM",
  TUE_B_P4.TEACHER AS "TUE_B_P4_TEACHER",
  TUE_B_P5.CLASS AS "TUE_B_P5_CLASS",
  TUE_B_P5.ROOM AS "TUE_B_P5_ROOM",
  TUE_B_P5.TEACHER AS "TUE_B_P5_TEACHER",
  TUE_B_P6.CLASS AS "TUE_B_P6_CLASS",
  TUE_B_P6.ROOM AS "TUE_B_P6_ROOM",
  TUE_B_P6.TEACHER AS "TUE_B_P6_TEACHER",
  TUE_B_P7.CLASS AS "TUE_B_P7_CLASS",
  TUE_B_P7.ROOM AS "TUE_B_P7_ROOM",
  TUE_B_P7.TEACHER AS "TUE_B_P7_TEACHER",
  -- Wednesday B Columns
  WED_B_BS1.CLASS AS "WED_B_BS1_CLASS",
  WED_B_BS1.ROOM AS "WED_B_BS1_ROOM",
  WED_B_BS1.TEACHER AS "WED_B_BS1_TEACHER",
  WED_B_BS2.CLASS AS "WED_B_BS2_CLASS",
  WED_B_BS2.ROOM AS "WED_B_BS2_ROOM",
  WED_B_BS2.TEACHER AS "WED_B_BS2_TEACHER",
  WED_B_HR1.CLASS AS "WED_B_HR1_CLASS",
  WED_B_HR1.ROOM AS "WED_B_HR1_ROOM",
  WED_B_HR1.TEACHER AS "WED_B_HR1_TEACHER",
  WED_B_P1.CLASS AS "WED_B_P1_CLASS",
  WED_B_P1.ROOM AS "WED_B_P1_ROOM",
  WED_B_P1.TEACHER AS "WED_B_P1_TEACHER",
  WED_B_P2.CLASS AS "WED_B_P2_CLASS",
  WED_B_P2.ROOM AS "WED_B_P2_ROOM",
  WED_B_P2.TEACHER AS "WED_B_P2_TEACHER",
  WED_B_P3.CLASS AS "WED_B_P3_CLASS",
  WED_B_P3.ROOM AS "WED_B_P3_ROOM",
  WED_B_P3.TEACHER AS "WED_B_P3_TEACHER",
  WED_B_P4.CLASS AS "WED_B_P4_CLASS",
  WED_B_P4.ROOM AS "WED_B_P4_ROOM",
  WED_B_P4.TEACHER AS "WED_B_P4_TEACHER",
  WED_B_P5.CLASS AS "WED_B_P5_CLASS",
  WED_B_P5.ROOM AS "WED_B_P5_ROOM",
  WED_B_P5.TEACHER AS "WED_B_P5_TEACHER",
  WED_B_P6.CLASS AS "WED_B_P6_CLASS",
  WED_B_P6.ROOM AS "WED_B_P6_ROOM",
  WED_B_P6.TEACHER AS "WED_B_P6_TEACHER",
  WED_B_P7.CLASS AS "WED_B_P7_CLASS",
  WED_B_P7.ROOM AS "WED_B_P7_ROOM",
  WED_B_P7.TEACHER AS "WED_B_P7_TEACHER",
  -- Thursday B Columns
  THU_B_BS1.CLASS AS "THU_B_BS1_CLASS",
  THU_B_BS1.ROOM AS "THU_B_BS1_ROOM",
  THU_B_BS1.TEACHER AS "THU_B_BS1_TEACHER",
  THU_B_BS2.CLASS AS "THU_B_BS2_CLASS",
  THU_B_BS2.ROOM AS "THU_B_BS2_ROOM",
  THU_B_BS2.TEACHER AS "THU_B_BS2_TEACHER",
  THU_B_HR1.CLASS AS "THU_B_HR1_CLASS",
  THU_B_HR1.ROOM AS "THU_B_HR1_ROOM",
  THU_B_HR1.TEACHER AS "THU_B_HR1_TEACHER",
  THU_B_P1.CLASS AS "THU_B_P1_CLASS",
  THU_B_P1.ROOM AS "THU_B_P1_ROOM",
  THU_B_P1.TEACHER AS "THU_B_P1_TEACHER",
  THU_B_P2.CLASS AS "THU_B_P2_CLASS",
  THU_B_P2.ROOM AS "THU_B_P2_ROOM",
  THU_B_P2.TEACHER AS "THU_B_P2_TEACHER",
  THU_B_P3.CLASS AS "THU_B_P3_CLASS",
  THU_B_P3.ROOM AS "THU_B_P3_ROOM",
  THU_B_P3.TEACHER AS "THU_B_P3_TEACHER",
  THU_B_P4.CLASS AS "THU_B_P4_CLASS",
  THU_B_P4.ROOM AS "THU_B_P4_ROOM",
  THU_B_P4.TEACHER AS "THU_B_P4_TEACHER",
  THU_B_P5.CLASS AS "THU_B_P5_CLASS",
  THU_B_P5.ROOM AS "THU_B_P5_ROOM",
  THU_B_P5.TEACHER AS "THU_B_P5_TEACHER",
  THU_B_CC.CLASS AS "THU_B_CC_CLASS",
  THU_B_CC.ROOM AS "THU_B_CC_ROOM",
  THU_B_CC.TEACHER AS "THU_B_CC_TEACHER",
  THU_B_P7.CLASS AS "THU_B_P7_CLASS",
  THU_B_P7.ROOM AS "THU_B_P7_ROOM",
  THU_B_P7.TEACHER AS "THU_B_P7_TEACHER",
  -- Friday B Columns
  FRI_B_BS1.CLASS AS "FRI_B_BS1_CLASS",
  FRI_B_BS1.ROOM AS "FRI_B_BS1_ROOM",
  FRI_B_BS1.TEACHER AS "FRI_B_BS1_TEACHER",
  FRI_B_BS2.CLASS AS "FRI_B_BS2_CLASS",
  FRI_B_BS2.ROOM AS "FRI_B_BS2_ROOM",
  FRI_B_BS2.TEACHER AS "FRI_B_BS2_TEACHER",
  FRI_B_HR1.CLASS AS "FRI_B_HR1_CLASS",
  FRI_B_HR1.ROOM AS "FRI_B_HR1_ROOM",
  FRI_B_HR1.TEACHER AS "FRI_B_HR1_TEACHER",
  FRI_B_P1.CLASS AS "FRI_B_P1_CLASS",
  FRI_B_P1.ROOM AS "FRI_B_P1_ROOM",
  FRI_B_P1.TEACHER AS "FRI_B_P1_TEACHER",
  FRI_B_P2.CLASS AS "FRI_B_P2_CLASS",
  FRI_B_P2.ROOM AS "FRI_B_P2_ROOM",
  FRI_B_P2.TEACHER AS "FRI_B_P2_TEACHER",
  FRI_B_P3.CLASS AS "FRI_B_P3_CLASS",
  FRI_B_P3.ROOM AS "FRI_B_P3_ROOM",
  FRI_B_P3.TEACHER AS "FRI_B_P3_TEACHER",
  FRI_B_P4.CLASS AS "FRI_B_P4_CLASS",
  FRI_B_P4.ROOM AS "FRI_B_P4_ROOM",
  FRI_B_P4.TEACHER AS "FRI_B_P4_TEACHER",
  FRI_B_P5.CLASS AS "FRI_B_P5_CLASS",
  FRI_B_P5.ROOM AS "FRI_B_P5_ROOM",
  FRI_B_P5.TEACHER AS "FRI_B_P5_TEACHER",
  FRI_B_P6.CLASS AS "FRI_B_P6_CLASS",
  FRI_B_P6.ROOM AS "FRI_B_P6_ROOM",
  FRI_B_P6.TEACHER AS "FRI_B_P6_TEACHER",
  FRI_B_P7.CLASS AS "FRI_B_P7_CLASS",
  FRI_B_P7.ROOM AS "FRI_B_P7_ROOM",
  FRI_B_P7.TEACHER AS "FRI_B_P7_TEACHER"

FROM CURRENT_STUDENTS CS

-- Monday A
LEFT JOIN FULL_CYCLE MON_A_BS1 ON MON_A_BS1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_A_BS1.DAY_INDEX = 1 AND MON_A_BS1.PERIOD = 'Before School 1')
LEFT JOIN FULL_CYCLE MON_A_BS2 ON MON_A_BS2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_A_BS2.DAY_INDEX = 1 AND MON_A_BS2.PERIOD = 'Before School 2')
LEFT JOIN FULL_CYCLE MON_A_HR1 ON MON_A_HR1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_A_HR1.DAY_INDEX = 1 AND MON_A_HR1.PERIOD = 'Home Room 1')
LEFT JOIN FULL_CYCLE MON_A_P1 ON MON_A_P1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_A_P1.DAY_INDEX = 1 AND MON_A_P1.PERIOD = 'Period 1')
LEFT JOIN FULL_CYCLE MON_A_P2 ON MON_A_P2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_A_P2.DAY_INDEX = 1 AND MON_A_P2.PERIOD = 'Period 2')
LEFT JOIN FULL_CYCLE MON_A_P3 ON MON_A_P3.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_A_P3.DAY_INDEX = 1 AND MON_A_P3.PERIOD = 'Period 3')
LEFT JOIN FULL_CYCLE MON_A_P4 ON MON_A_P4.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_A_P4.DAY_INDEX = 1 AND MON_A_P4.PERIOD = 'Period 4')
LEFT JOIN FULL_CYCLE MON_A_P5 ON MON_A_P5.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_A_P5.DAY_INDEX = 1 AND MON_A_P5.PERIOD = 'Period 5')
LEFT JOIN FULL_CYCLE MON_A_P6 ON MON_A_P6.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_A_P6.DAY_INDEX = 1 AND MON_A_P6.PERIOD = 'Period 6')
LEFT JOIN FULL_CYCLE MON_A_P7 ON MON_A_P7.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_A_P7.DAY_INDEX = 1 AND MON_A_P7.PERIOD = 'Period 7')

-- Tuesday A
LEFT JOIN FULL_CYCLE TUE_A_BS1 ON TUE_A_BS1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_A_BS1.DAY_INDEX = 2 AND TUE_A_BS1.PERIOD = 'Before School 1')
LEFT JOIN FULL_CYCLE TUE_A_BS2 ON TUE_A_BS2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_A_BS2.DAY_INDEX = 2 AND TUE_A_BS2.PERIOD = 'Before School 2')
LEFT JOIN FULL_CYCLE TUE_A_HR1 ON TUE_A_HR1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_A_HR1.DAY_INDEX = 2 AND TUE_A_HR1.PERIOD = 'Home Room 1')
LEFT JOIN FULL_CYCLE TUE_A_P1 ON TUE_A_P1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_A_P1.DAY_INDEX = 2 AND TUE_A_P1.PERIOD = 'Period 1')
LEFT JOIN FULL_CYCLE TUE_A_P2 ON TUE_A_P2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_A_P2.DAY_INDEX = 2 AND TUE_A_P2.PERIOD = 'Period 2')
LEFT JOIN FULL_CYCLE TUE_A_P3 ON TUE_A_P3.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_A_P3.DAY_INDEX = 2 AND TUE_A_P3.PERIOD = 'Period 3')
LEFT JOIN FULL_CYCLE TUE_A_P4 ON TUE_A_P4.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_A_P4.DAY_INDEX = 2 AND TUE_A_P4.PERIOD = 'Period 4')
LEFT JOIN FULL_CYCLE TUE_A_P5 ON TUE_A_P5.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_A_P5.DAY_INDEX = 2 AND TUE_A_P5.PERIOD = 'Period 5')
LEFT JOIN FULL_CYCLE TUE_A_P6 ON TUE_A_P6.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_A_P6.DAY_INDEX = 2 AND TUE_A_P6.PERIOD = 'Period 6')
LEFT JOIN FULL_CYCLE TUE_A_P7 ON TUE_A_P7.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_A_P7.DAY_INDEX = 2 AND TUE_A_P7.PERIOD = 'Period 7')

-- Wednesday A
LEFT JOIN FULL_CYCLE WED_A_BS1 ON WED_A_BS1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_A_BS1.DAY_INDEX = 3 AND WED_A_BS1.PERIOD = 'Before School 1')
LEFT JOIN FULL_CYCLE WED_A_BS2 ON WED_A_BS2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_A_BS2.DAY_INDEX = 3 AND WED_A_BS2.PERIOD = 'Before School 2')
LEFT JOIN FULL_CYCLE WED_A_HR1 ON WED_A_HR1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_A_HR1.DAY_INDEX = 3 AND WED_A_HR1.PERIOD = 'Home Room 1')
LEFT JOIN FULL_CYCLE WED_A_P1 ON WED_A_P1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_A_P1.DAY_INDEX = 3 AND WED_A_P1.PERIOD = 'Period 1')
LEFT JOIN FULL_CYCLE WED_A_P2 ON WED_A_P2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_A_P2.DAY_INDEX = 3 AND WED_A_P2.PERIOD = 'Period 2')
LEFT JOIN FULL_CYCLE WED_A_P3 ON WED_A_P3.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_A_P3.DAY_INDEX = 3 AND WED_A_P3.PERIOD = 'Period 3')
LEFT JOIN FULL_CYCLE WED_A_P4 ON WED_A_P4.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_A_P4.DAY_INDEX = 3 AND WED_A_P4.PERIOD = 'Period 4')
LEFT JOIN FULL_CYCLE WED_A_P5 ON WED_A_P5.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_A_P5.DAY_INDEX = 3 AND WED_A_P5.PERIOD = 'Period 5')
LEFT JOIN FULL_CYCLE WED_A_P6 ON WED_A_P6.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_A_P6.DAY_INDEX = 3 AND WED_A_P6.PERIOD = 'Period 6')
LEFT JOIN FULL_CYCLE WED_A_P7 ON WED_A_P7.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_A_P7.DAY_INDEX = 3 AND WED_A_P7.PERIOD = 'Period 7')

-- Thursday A
LEFT JOIN FULL_CYCLE THU_A_BS1 ON THU_A_BS1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_A_BS1.DAY_INDEX = 4 AND THU_A_BS1.PERIOD = 'Before School 1')
LEFT JOIN FULL_CYCLE THU_A_BS2 ON THU_A_BS2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_A_BS2.DAY_INDEX = 4 AND THU_A_BS2.PERIOD = 'Before School 2')
LEFT JOIN FULL_CYCLE THU_A_HR1 ON THU_A_HR1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_A_HR1.DAY_INDEX = 4 AND THU_A_HR1.PERIOD = 'Home Room 1')
LEFT JOIN FULL_CYCLE THU_A_P1 ON THU_A_P1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_A_P1.DAY_INDEX = 4 AND THU_A_P1.PERIOD = 'Period 1')
LEFT JOIN FULL_CYCLE THU_A_P2 ON THU_A_P2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_A_P2.DAY_INDEX = 4 AND THU_A_P2.PERIOD = 'Period 2')
LEFT JOIN FULL_CYCLE THU_A_P3 ON THU_A_P3.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_A_P3.DAY_INDEX = 4 AND THU_A_P3.PERIOD = 'Period 3')
LEFT JOIN FULL_CYCLE THU_A_P4 ON THU_A_P4.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_A_P4.DAY_INDEX = 4 AND THU_A_P4.PERIOD = 'Period 4')
LEFT JOIN FULL_CYCLE THU_A_P5 ON THU_A_P5.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_A_P5.DAY_INDEX = 4 AND THU_A_P5.PERIOD = 'Period 5')
LEFT JOIN FULL_CYCLE THU_A_CC ON THU_A_CC.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_A_CC.DAY_INDEX = 4 AND THU_A_CC.PERIOD = 'CoCurricular')
LEFT JOIN FULL_CYCLE THU_A_P7 ON THU_A_P7.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_A_P7.DAY_INDEX = 4 AND THU_A_P7.PERIOD = 'Period 7')

-- Friday A
LEFT JOIN FULL_CYCLE FRI_A_BS1 ON FRI_A_BS1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_A_BS1.DAY_INDEX = 5 AND FRI_A_BS1.PERIOD = 'Before School 1')
LEFT JOIN FULL_CYCLE FRI_A_BS2 ON FRI_A_BS2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_A_BS2.DAY_INDEX = 5 AND FRI_A_BS2.PERIOD = 'Before School 2')
LEFT JOIN FULL_CYCLE FRI_A_HR1 ON FRI_A_HR1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_A_HR1.DAY_INDEX = 5 AND FRI_A_HR1.PERIOD = 'Home Room 1')
LEFT JOIN FULL_CYCLE FRI_A_P1 ON FRI_A_P1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_A_P1.DAY_INDEX = 5 AND FRI_A_P1.PERIOD = 'Period 1')
LEFT JOIN FULL_CYCLE FRI_A_P2 ON FRI_A_P2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_A_P2.DAY_INDEX = 5 AND FRI_A_P2.PERIOD = 'Period 2')
LEFT JOIN FULL_CYCLE FRI_A_P3 ON FRI_A_P3.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_A_P3.DAY_INDEX = 5 AND FRI_A_P3.PERIOD = 'Period 3')
LEFT JOIN FULL_CYCLE FRI_A_P4 ON FRI_A_P4.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_A_P4.DAY_INDEX = 5 AND FRI_A_P4.PERIOD = 'Period 4')
LEFT JOIN FULL_CYCLE FRI_A_P5 ON FRI_A_P5.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_A_P5.DAY_INDEX = 5 AND FRI_A_P5.PERIOD = 'Period 5')
LEFT JOIN FULL_CYCLE FRI_A_P6 ON FRI_A_P6.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_A_P6.DAY_INDEX = 5 AND FRI_A_P6.PERIOD = 'Period 6')
LEFT JOIN FULL_CYCLE FRI_A_P7 ON FRI_A_P7.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_A_P7.DAY_INDEX = 5 AND FRI_A_P7.PERIOD = 'Period 7')

-- Monday B
LEFT JOIN FULL_CYCLE MON_B_BS1 ON MON_B_BS1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_B_BS1.DAY_INDEX = 6 AND MON_B_BS1.PERIOD = 'Before School 1')
LEFT JOIN FULL_CYCLE MON_B_BS2 ON MON_B_BS2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_B_BS2.DAY_INDEX = 6 AND MON_B_BS2.PERIOD = 'Before School 2')
LEFT JOIN FULL_CYCLE MON_B_HR1 ON MON_B_HR1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_B_HR1.DAY_INDEX = 6 AND MON_B_HR1.PERIOD = 'Home Room 1')
LEFT JOIN FULL_CYCLE MON_B_P1 ON MON_B_P1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_B_P1.DAY_INDEX = 6 AND MON_B_P1.PERIOD = 'Period 1')
LEFT JOIN FULL_CYCLE MON_B_P2 ON MON_B_P2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_B_P2.DAY_INDEX = 6 AND MON_B_P2.PERIOD = 'Period 2')
LEFT JOIN FULL_CYCLE MON_B_P3 ON MON_B_P3.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_B_P3.DAY_INDEX = 6 AND MON_B_P3.PERIOD = 'Period 3')
LEFT JOIN FULL_CYCLE MON_B_P4 ON MON_B_P4.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_B_P4.DAY_INDEX = 6 AND MON_B_P4.PERIOD = 'Period 4')
LEFT JOIN FULL_CYCLE MON_B_P5 ON MON_B_P5.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_B_P5.DAY_INDEX = 6 AND MON_B_P5.PERIOD = 'Period 5')
LEFT JOIN FULL_CYCLE MON_B_P6 ON MON_B_P6.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_B_P6.DAY_INDEX = 6 AND MON_B_P6.PERIOD = 'Period 6')
LEFT JOIN FULL_CYCLE MON_B_P7 ON MON_B_P7.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (MON_B_P7.DAY_INDEX = 6 AND MON_B_P7.PERIOD = 'Period 7')

-- Tuesday B
LEFT JOIN FULL_CYCLE TUE_B_BS1 ON TUE_B_BS1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_B_BS1.DAY_INDEX = 7 AND TUE_B_BS1.PERIOD = 'Before School 1')
LEFT JOIN FULL_CYCLE TUE_B_BS2 ON TUE_B_BS2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_B_BS2.DAY_INDEX = 7 AND TUE_B_BS2.PERIOD = 'Before School 2')
LEFT JOIN FULL_CYCLE TUE_B_HR1 ON TUE_B_HR1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_B_HR1.DAY_INDEX = 7 AND TUE_B_HR1.PERIOD = 'Home Room 1')
LEFT JOIN FULL_CYCLE TUE_B_P1 ON TUE_B_P1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_B_P1.DAY_INDEX = 7 AND TUE_B_P1.PERIOD = 'Period 1')
LEFT JOIN FULL_CYCLE TUE_B_P2 ON TUE_B_P2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_B_P2.DAY_INDEX = 7 AND TUE_B_P2.PERIOD = 'Period 2')
LEFT JOIN FULL_CYCLE TUE_B_P3 ON TUE_B_P3.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_B_P3.DAY_INDEX = 7 AND TUE_B_P3.PERIOD = 'Period 3')
LEFT JOIN FULL_CYCLE TUE_B_P4 ON TUE_B_P4.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_B_P4.DAY_INDEX = 7 AND TUE_B_P4.PERIOD = 'Period 4')
LEFT JOIN FULL_CYCLE TUE_B_P5 ON TUE_B_P5.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_B_P5.DAY_INDEX = 7 AND TUE_B_P5.PERIOD = 'Period 5')
LEFT JOIN FULL_CYCLE TUE_B_P6 ON TUE_B_P6.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_B_P6.DAY_INDEX = 7 AND TUE_B_P6.PERIOD = 'Period 6')
LEFT JOIN FULL_CYCLE TUE_B_P7 ON TUE_B_P7.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (TUE_B_P7.DAY_INDEX = 7 AND TUE_B_P7.PERIOD = 'Period 7')

-- Wednesday B
LEFT JOIN FULL_CYCLE WED_B_BS1 ON WED_B_BS1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_B_BS1.DAY_INDEX = 8 AND WED_B_BS1.PERIOD = 'Before School 1')
LEFT JOIN FULL_CYCLE WED_B_BS2 ON WED_B_BS2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_B_BS2.DAY_INDEX = 8 AND WED_B_BS2.PERIOD = 'Before School 2')
LEFT JOIN FULL_CYCLE WED_B_HR1 ON WED_B_HR1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_B_HR1.DAY_INDEX = 8 AND WED_B_HR1.PERIOD = 'Home Room 1')
LEFT JOIN FULL_CYCLE WED_B_P1 ON WED_B_P1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_B_P1.DAY_INDEX = 8 AND WED_B_P1.PERIOD = 'Period 1')
LEFT JOIN FULL_CYCLE WED_B_P2 ON WED_B_P2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_B_P2.DAY_INDEX = 8 AND WED_B_P2.PERIOD = 'Period 2')
LEFT JOIN FULL_CYCLE WED_B_P3 ON WED_B_P3.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_B_P3.DAY_INDEX = 8 AND WED_B_P3.PERIOD = 'Period 3')
LEFT JOIN FULL_CYCLE WED_B_P4 ON WED_B_P4.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_B_P4.DAY_INDEX = 8 AND WED_B_P4.PERIOD = 'Period 4')
LEFT JOIN FULL_CYCLE WED_B_P5 ON WED_B_P5.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_B_P5.DAY_INDEX = 8 AND WED_B_P5.PERIOD = 'Period 5')
LEFT JOIN FULL_CYCLE WED_B_P6 ON WED_B_P6.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_B_P6.DAY_INDEX = 8 AND WED_B_P6.PERIOD = 'Period 6')
LEFT JOIN FULL_CYCLE WED_B_P7 ON WED_B_P7.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (WED_B_P7.DAY_INDEX = 8 AND WED_B_P7.PERIOD = 'Period 7')

-- Thursday B
LEFT JOIN FULL_CYCLE THU_B_BS1 ON THU_B_BS1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_B_BS1.DAY_INDEX = 9 AND THU_B_BS1.PERIOD = 'Before School 1')
LEFT JOIN FULL_CYCLE THU_B_BS2 ON THU_B_BS2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_B_BS2.DAY_INDEX = 9 AND THU_B_BS2.PERIOD = 'Before School 2')
LEFT JOIN FULL_CYCLE THU_B_HR1 ON THU_B_HR1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_B_HR1.DAY_INDEX = 9 AND THU_B_HR1.PERIOD = 'Home Room 1')
LEFT JOIN FULL_CYCLE THU_B_P1 ON THU_B_P1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_B_P1.DAY_INDEX = 9 AND THU_B_P1.PERIOD = 'Period 1')
LEFT JOIN FULL_CYCLE THU_B_P2 ON THU_B_P2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_B_P2.DAY_INDEX = 9 AND THU_B_P2.PERIOD = 'Period 2')
LEFT JOIN FULL_CYCLE THU_B_P3 ON THU_B_P3.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_B_P3.DAY_INDEX = 9 AND THU_B_P3.PERIOD = 'Period 3')
LEFT JOIN FULL_CYCLE THU_B_P4 ON THU_B_P4.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_B_P4.DAY_INDEX = 9 AND THU_B_P4.PERIOD = 'Period 4')
LEFT JOIN FULL_CYCLE THU_B_P5 ON THU_B_P5.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_B_P5.DAY_INDEX = 9 AND THU_B_P5.PERIOD = 'Period 5')
LEFT JOIN FULL_CYCLE THU_B_CC ON THU_B_CC.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_B_CC.DAY_INDEX = 9 AND THU_B_CC.PERIOD = 'CoCurricular')
LEFT JOIN FULL_CYCLE THU_B_P7 ON THU_B_P7.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (THU_B_P7.DAY_INDEX = 9 AND THU_B_P7.PERIOD = 'Period 7')

-- Friday B
LEFT JOIN FULL_CYCLE FRI_B_BS1 ON FRI_B_BS1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_B_BS1.DAY_INDEX = 10 AND FRI_B_BS1.PERIOD = 'Before School 1')
LEFT JOIN FULL_CYCLE FRI_B_BS2 ON FRI_B_BS2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_B_BS2.DAY_INDEX = 10 AND FRI_B_BS2.PERIOD = 'Before School 2')
LEFT JOIN FULL_CYCLE FRI_B_HR1 ON FRI_B_HR1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_B_HR1.DAY_INDEX = 10 AND FRI_B_HR1.PERIOD = 'Home Room 1')
LEFT JOIN FULL_CYCLE FRI_B_P1 ON FRI_B_P1.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_B_P1.DAY_INDEX = 10 AND FRI_B_P1.PERIOD = 'Period 1')
LEFT JOIN FULL_CYCLE FRI_B_P2 ON FRI_B_P2.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_B_P2.DAY_INDEX = 10 AND FRI_B_P2.PERIOD = 'Period 2')
LEFT JOIN FULL_CYCLE FRI_B_P3 ON FRI_B_P3.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_B_P3.DAY_INDEX = 10 AND FRI_B_P3.PERIOD = 'Period 3')
LEFT JOIN FULL_CYCLE FRI_B_P4 ON FRI_B_P4.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_B_P4.DAY_INDEX = 10 AND FRI_B_P4.PERIOD = 'Period 4')
LEFT JOIN FULL_CYCLE FRI_B_P5 ON FRI_B_P5.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_B_P5.DAY_INDEX = 10 AND FRI_B_P5.PERIOD = 'Period 5')
LEFT JOIN FULL_CYCLE FRI_B_P6 ON FRI_B_P6.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_B_P6.DAY_INDEX = 10 AND FRI_B_P6.PERIOD = 'Period 6')
LEFT JOIN FULL_CYCLE FRI_B_P7 ON FRI_B_P7.STUDENT_NUMBER = CS.STUDENT_NUMBER AND (FRI_B_P7.DAY_INDEX = 10 AND FRI_B_P7.PERIOD = 'Period 7')

WHERE CS.FORM_RUN = '2013 Year 07'

ORDER BY CS.FORM_RUN, MON_A_HR1.CLASS