-- To assign SELECT only access use this example:
-- GRANT SELECT ON "DB2INST1"."VIEW_REPORT_SCOPE" TO USER IDCARDS

CREATE OR REPLACE VIEW DB2INST1.VIEW_REPORT_SCOPE (
  SORT_ORDER,
  SCOPE
) AS

SELECT 1 AS "SORT_ORDER", 'All students' AS "SCOPE" FROM SYSIBM.sysdummy1
UNION ALL
SELECT 2 AS "SORT_ORDER", 'Middle School' AS "SCOPE" FROM SYSIBM.sysdummy1
UNION ALL
SELECT 2 AS "SORT_ORDER", 'Senior School' AS "SCOPE" FROM SYSIBM.sysdummy1
UNION ALL
(SELECT 3 AS "SORT_ORDER", (CASE WHEN house LIKE '%Connor' THEN 'OConnor' ELSE house END) AS "SCOPE" FROM house WHERE status_flag = 0 ORDER BY (CASE WHEN house LIKE '%Connor' THEN 'OConnor' ELSE house END))