SELECT
  VA.CLASS_ID,
  STUDENT.STUDENT_NUMBER AS "LOOKUP_CODE",
  STUDENT.STUDENT_ID,
  (CASE WHEN CONTACT.PREFERRED_NAME IS NULL THEN CONTACT.FIRSTNAME ELSE CONTACT.PREFERRED_NAME END) AS "FIRSTNAME",
  CONTACT.SURNAME,
  FORM_RUN.FORM_RUN,
  (CASE WHEN VA.ATTEND_STATUS_ID IN (3, 4, 5) THEN
    (CASE
      WHEN VA.ABSENT_STATUS = 0 THEN 'Absent from Co-Curricular'
      WHEN VA.ABSENT_STATUS = 1 THEN 'Absent (Explained - Unverified)'
      WHEN VA.ABSENT_STATUS = 2 THEN 'Absent (Explained - Verified)'
      WHEN VA.ABSENT_STATUS = 3 THEN 'Absent (Explained - Verified - Sick)'
      WHEN VA.ABSENT_STATUS = 4 THEN 'Absent<br>(Explained - Verified - Suspended)'
      WHEN VA.ABSENT_STATUS = 5 THEN 'Absent<br>(Explained - Verified - Principal Approved)'
      WHEN VA.ABSENT_STATUS = 6 THEN 'Absent<br>(Explained - Verified - School Business)'
      WHEN VA.ABSENT_STATUS = 7 THEN 'Absent<br>(Explained - Verified - Flexible Timetable)'
      WHEN VA.ABSENT_STATUS = 8 THEN 'Absent<br>(Explained - Verified - External Education)'
      WHEN VA.ABSENT_STATUS = 9 THEN 'Absent<br>(Explained - Verified - Exempt)'
    ELSE NULL END)
  ELSE ATTEND_STATUS.ATTEND_STATUS END) AS "ATTENDANCE"

FROM VIEW_ATTENDANCE VA

INNER JOIN CLASS ON CLASS.CLASS_ID = VA.CLASS_ID
INNER JOIN STUDENT ON STUDENT.STUDENT_ID = VA.STUDENT_ID
INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID

INNER JOIN TABLE(EDUMATE.GET_ENROLED_STUDENTS_FORM_RUN(CURRENT DATE)) CURRENTS ON CURRENTS.STUDENT_ID = VA.STUDENT_ID
INNER JOIN FORM_RUN ON FORM_RUN.FORM_RUN_ID = CURRENTS.FORM_RUN_ID

INNER JOIN ATTEND_STATUS ON ATTEND_STATUS.ATTEND_STATUS_ID = VA.ATTEND_STATUS_ID


WHERE
  VA.CLASS_ID = [[mainquery.CLASS_ID]]
  AND
  VA.DATE_ON = DATE('[[mainquery.THURSDAY]]')
  AND
  VA.PERIOD_ID IN (SELECT PERIOD_ID FROM PERIOD WHERE PERIOD LIKE 'CoCurricular')

ORDER BY CLASS.CLASS, VA.ABSENT_STATUS ASC, VA.ATTEND_STATUS_ID DESC, CONTACT.SURNAME, CONTACT.PREFERRED_NAME, CONTACT.FIRSTNAME