WITH REPORT_VARS AS (
  SELECT '[[Attendance for=date]]' as "THURSDAY" FROM SYSIBM.SYSDUMMY1
  --SELECT (CURRENT DATE) AS "THURSDAY" FROM SYSIBM.SYSDUMMY1
),

MARKED_ROLL_LOG AS (
  SELECT DISTINCT
    ATTENDANCE.LESSON_ID,
    ATTENDANCE.RECORDED_BY,
    ATTENDANCE.LAST_UPDATED,
    DATE_ON
  
  FROM ATTENDANCE
  
  INNER JOIN LESSON ON LESSON.LESSON_ID = ATTENDANCE.LESSON_ID
  INNER JOIN PERIOD_CLASS ON PERIOD_CLASS.PERIOD_CLASS_ID = LESSON.PERIOD_CLASS_ID
  INNER JOIN PERIOD ON PERIOD.PERIOD_ID = PERIOD_CLASS.PERIOD_CYCLE_DAY_ID
  CROSS JOIN REPORT_VARS
  
  WHERE
    PERIOD.PERIOD = 'CoCurricular'
    AND
    DATE_ON = REPORT_VARS.THURSDAY
),

MARKED_ROLLS AS (
  SELECT DISTINCT
    MARKED_ROLL_LOG.LESSON_ID,
    CLASS.CLASS_ID,
    CONTACT.FIRSTNAME AS "MARKER_FIRSTNAME",
    CONTACT.SURNAME AS "MARKER_SURNAME",
    (SELECT ATTENDANCE.LAST_UPDATED
      FROM ATTENDANCE
      WHERE ATTENDANCE.LESSON_ID = MARKED_ROLL_LOG.LESSON_ID
      ORDER BY ATTENDANCE.LAST_UPDATED DESC
      FETCH FIRST 1 ROW ONLY) AS "LAST_MARKED"
  
  FROM MARKED_ROLL_LOG
  
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = MARKED_ROLL_LOG.RECORDED_BY
  INNER JOIN LESSON ON LESSON.LESSON_ID = MARKED_ROLL_LOG.LESSON_ID
  INNER JOIN PERIOD_CLASS ON PERIOD_CLASS.PERIOD_CLASS_ID = LESSON.PERIOD_CLASS_ID
  INNER JOIN CLASS ON CLASS.CLASS_ID = PERIOD_CLASS.CLASS_ID

  GROUP BY MARKED_ROLL_LOG.LESSON_ID, CLASS.CLASS_ID, CONTACT.FIRSTNAME, CONTACT.SURNAME, MARKED_ROLL_LOG.LAST_UPDATED
),

CC_ATTEND AS (
  SELECT DISTINCT
    VA.CLASS_ID,
    VA.LESSON_ID,
    TO_CHAR((VA.DATE_ON), 'DD Month YYYY') AS "DATE_ON",
    TO_CHAR((CURRENT DATE), 'DD Month YYYY') AS "DATE_PRINTED",
    CHAR(TIME(CURRENT TIMESTAMP),USA) AS "TIME_PRINTED",
    CLASS.CLASS,
    VA.ATTEND_STATUS_ID,
    (CASE WHEN COACH.PREFERRED_NAME IS NULL THEN COACH.FIRSTNAME ELSE COACH.PREFERRED_NAME END) AS "COACH_FIRSTNAME",
    COACH.SURNAME AS "COACH_SURNAME",
    MARKED_ROLLS.MARKER_FIRSTNAME,
    MARKED_ROLLS.MARKER_SURNAME,
    TO_CHAR((MARKED_ROLLS.LAST_MARKED), 'DD Month, YYYY') AS "DATE_MARKED",
    CHAR(TIME(MARKED_ROLLS.LAST_MARKED), USA) AS "TIME_MARKED",
    REPORT_VARS.THURSDAY
  
  FROM VIEW_ATTENDANCE VA
  
  INNER JOIN CLASS ON CLASS.CLASS_ID = VA.CLASS_ID
  INNER JOIN CLASS_TEACHER ON CLASS_TEACHER.CLASS_ID = VA.CLASS_ID
  INNER JOIN TEACHER ON TEACHER.TEACHER_ID = CLASS_TEACHER.TEACHER_ID
  INNER JOIN CONTACT COACH ON COACH.CONTACT_ID = TEACHER.CONTACT_ID
  
  INNER JOIN MARKED_ROLLS ON MARKED_ROLLS.LESSON_ID = VA.LESSON_ID
  
  CROSS JOIN REPORT_VARS
  
  WHERE
    VA.DATE_ON = REPORT_VARS.THURSDAY
    AND
    VA.PERIOD_ID IN (SELECT PERIOD_ID FROM PERIOD WHERE PERIOD LIKE 'CoCurricular')
    
  ORDER BY CLASS
),

CC_ATTEND_RAW AS (
  SELECT
    VA.CLASS_ID,
    CONTACT.CONTACT_ID,
    VA.ATTEND_STATUS_ID
  
  FROM VIEW_ATTENDANCE VA
  
  INNER JOIN STUDENT ON STUDENT.STUDENT_ID = VA.STUDENT_ID
  INNER JOIN CONTACT ON CONTACT.CONTACT_ID = STUDENT.CONTACT_ID
  CROSS JOIN REPORT_VARS
  
  WHERE
    VA.DATE_ON = REPORT_VARS.THURSDAY
    AND
    VA.PERIOD_ID IN (SELECT PERIOD_ID FROM PERIOD WHERE PERIOD LIKE 'CoCurricular')
),

CLASS_COUNTS AS (
  SELECT
    COUNT(CC_ATTEND_RAW.CONTACT_ID) AS "TOTAL_STUDENTS",
    COUNT(CASE WHEN CC_ATTEND_RAW.ATTEND_STATUS_ID = 2 THEN 1 ELSE NULL END) AS "TOTAL_PRESENT",
    COUNT(CASE WHEN CC_ATTEND_RAW.ATTEND_STATUS_ID = 3 THEN 1 ELSE NULL END) AS "TOTAL_ABSENT",
    CC_ATTEND_RAW.CLASS_ID

  FROM CC_ATTEND_RAW
  
  GROUP BY CC_ATTEND_RAW.CLASS_ID, CC_ATTEND_RAW.CONTACT_ID
),

CLASS_TOTALS AS (
  SELECT
    SUM(TOTAL_STUDENTS) AS "TOTAL_STUDENTS",
    SUM(TOTAL_PRESENT) AS "TOTAL_PRESENT",
    SUM(TOTAL_ABSENT) AS "TOTAL_ABSENT",
    CLASS_ID
  
  FROM CLASS_COUNTS
  
  GROUP BY CLASS_ID
),

FINAL AS (
  SELECT DISTINCT
    CC_ATTEND.CLASS_ID,
    CC_ATTEND.LESSON_ID,
    CC_ATTEND.DATE_ON,
    CC_ATTEND.DATE_PRINTED,
    CC_ATTEND.TIME_PRINTED,
    CC_ATTEND.CLASS,
    CC_ATTEND.COACH_FIRSTNAME,
    CC_ATTEND.COACH_SURNAME,
    CC_ATTEND.MARKER_FIRSTNAME,
    CC_ATTEND.MARKER_SURNAME,
    CC_ATTEND.DATE_MARKED,
    CC_ATTEND.TIME_MARKED,
    CC_ATTEND.THURSDAY,
    CLASS_TOTALS.TOTAL_STUDENTS,
    CLASS_TOTALS.TOTAL_PRESENT,
    CLASS_TOTALS.TOTAL_ABSENT
  
  FROM CC_ATTEND
  
  INNER JOIN CLASS_TOTALS ON CLASS_TOTALS.CLASS_ID = CC_ATTEND.CLASS_ID
),

CLASSES AS (
  SELECT
    COUNT(DISTINCT CLASS) AS "COUNT"
  FROM CC_ATTEND
)

SELECT
  FINAL.CLASS_ID,
  FINAL.LESSON_ID,
  FINAL.DATE_ON,
  FINAL.DATE_PRINTED,
  FINAL.TIME_PRINTED,
  FINAL.CLASS,
  FINAL.COACH_FIRSTNAME,
  FINAL.COACH_SURNAME,
  FINAL.MARKER_FIRSTNAME,
  FINAL.MARKER_SURNAME,
  FINAL.DATE_MARKED,
  FINAL.TIME_MARKED,
  FINAL.THURSDAY,
  FINAL.TOTAL_STUDENTS,
  FINAL.TOTAL_PRESENT,
  FINAL.TOTAL_ABSENT,
  ROW_NUMBER() OVER () AS "PAGE",
  CLASSES.COUNT AS "PAGE_TOTAL"

FROM FINAL

CROSS JOIN CLASSES

ORDER BY FINAL.CLASS